package com.pnfsoftware.jebglobal;

import com.pnfsoftware.jeb.core.units.code.asm.analyzer.IMethodStackMemoryModel;
import com.pnfsoftware.jeb.core.units.code.asm.cfg.BasicBlock;
import com.pnfsoftware.jeb.core.units.code.asm.cfg.CFG;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.IERoutineContext;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEGeneric;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEMem;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEStackManager;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEStatement;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEVar;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IWildcardType;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IWildcardTypeManager;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.OperationType;
import com.pnfsoftware.jeb.core.units.code.asm.items.INativeContinuousItem;
import com.pnfsoftware.jeb.core.units.code.asm.items.INativeDataItem;
import com.pnfsoftware.jeb.core.units.code.asm.type.INativeType;
import com.pnfsoftware.jeb.core.units.code.asm.type.IPrimitiveType;
import com.pnfsoftware.jeb.core.units.code.asm.type.ITypeManager;
import com.pnfsoftware.jeb.core.units.code.asm.type.TypeUtil;
import com.pnfsoftware.jeb.util.base.Assert;
import com.pnfsoftware.jeb.util.base.Couple;
import com.pnfsoftware.jeb.util.logging.StructuredLogger;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

public class apm {
   private static final StructuredLogger nf = aeg.q(apm.class);
   IERoutineContext q;
   CFG RF;
   ITypeManager xK;
   IWildcardTypeManager Dw;
   IEStackManager Uv;
   IMethodStackMemoryModel oW;
   apj gO;

   public apm(IERoutineContext var1) {
      this.q = var1;
      this.RF = var1.getCfg();
      this.Dw = var1.getWildcardTypeManager();
      this.xK = this.Dw.getNativeTypeManager();
      this.Uv = var1.getStackManager();
      this.oW = var1.getRoutine().getData().getStackframeModel();
   }

   public apj q(IEVar var1) {
      if (this.gO != null) {
         throw new IllegalStateException();
      } else {
         this.gO = new apj(this.q);
         this.q(var1, true);
         return this.gO;
      }
   }

   public int RF(IEVar var1) {
      if (this.gO == null) {
         throw new IllegalStateException();
      } else {
         return this.q(var1, false);
      }
   }

   private int q(IEVar var1, boolean var2) {
      AtomicInteger var3 = new AtomicInteger(0);

      for (BasicBlock var5 : this.RF) {
         for (IEStatement var7 : var5) {
            var7.visitDepthPost(new apn(this, var7, var1, var2, var3));
         }
      }

      for (BasicBlock var10 : this.RF) {
         for (IEStatement var12 : var10) {
            var12.visitDepthPre(new apo(this, var1, var2, var3));
         }
      }

      if (var2) {
         if (aeh.q) {
            Object[] var10000 = new Object[]{this.gO.Dw()};
         }

         List var9 = this.gO.xK();
         if (!var9.isEmpty()) {
            this.RF.invalidateDataFlowAnalysis();
         }
      } else if (var3.get() > 0) {
         this.RF.invalidateDataFlowAnalysis();
      }

      return var3.get();
   }

   private IEGeneric q(IEGeneric var1, IEGeneric var2, IEVar var3, boolean var4, Boolean var5) {
      ano var6 = new ano(var1, var3);
      if (var6.q()) {
         int var7 = var2 instanceof IEMem ? var2.getBitsize() : 0;
         if (var4) {
            this.gO.q(var6.oW(), var7, var5);
         } else {
            IEGeneric var8 = this.q(var6, var7);
            if (var8 != null) {
               boolean var9 = var2.replaceSubExpression(var1, var8);
               Assert.a(var9);
               return var8;
            }
         }
      }

      return null;
   }

   private IEGeneric q(ano var1, int var2) {
      long var5 = var1.oW();
      INativeContinuousItem var7 = this.oW.getItemOver(var5);
      long var3;
      if (var7 == null) {
         var3 = var5;
         var5 = 0L;
      } else {
         var3 = var7.getMemoryAddress();
         var5 -= var3;
      }

      IEVar var8 = this.q.getStackReference(var3);
      if (var8 == null) {
         IWildcardType var9 = null;
         if (var7 != null) {
            INativeType var10 = ((INativeDataItem)var7).getType();
            if (var7.isAutoGenerated() && TypeUtil.getNonAlias(var10) instanceof IPrimitiveType) {
               var9 = this.Dw.createPointer(var10.getSize() * 8);
            } else {
               var9 = this.Dw.create(this.xK.createReference(var10));
               this.q.acquireNativeItem(var9);
            }
         }

         var8 = this.q.createStackReference(var3, var9);
      }

      var1.q(var8, var5);
      return var1.q(this.q);
   }

   public int q() {
      AtomicInteger var1 = new AtomicInteger(0);

      for (BasicBlock var3 : this.RF) {
         for (IEStatement var5 : var3) {
            var5.visitDepthPost(new app(this, var1));
         }
      }

      if (var1.get() > 0) {
         this.RF.invalidateDataFlowAnalysis();
      }

      return var1.get();
   }

   private static Couple q(IEGeneric var0) {
      if (RF(var0)) {
         return new Couple(var0.asVar(), 0L);
      } else {
         if (var0.isOperation(OperationType.ADD)) {
            IEGeneric var1 = var0.asOperation().getOperand1();
            IEGeneric var2 = var0.asOperation().getOperand2();
            if (RF(var1) && var2.isImm()) {
               return new Couple(var1.asVar(), var2.asImm().getValueAsLong());
            }
         }

         return null;
      }
   }

   private static boolean RF(IEGeneric var0) {
      return var0.isVar() && var0.asVar().isStackReference();
   }
}
