package com.pnfsoftware.jebglobal;

import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEPrototypeHandler;
import com.pnfsoftware.jeb.util.base.Assert;
import com.pnfsoftware.jeb.util.logging.StructuredLogger;

public class awu extends avx {
   private static final StructuredLogger JY = aeg.q(awu.class);

   public awu() {
      super(avy.io);
   }

   @Override
   protected boolean Dw() {
      if (this.gP.getPrototype() != null && !this.gP.isAutoGeneratedPrototype()) {
         Object[] var10000 = new Object[0];
         IEPrototypeHandler var3 = this.Uv.getPrototypeHandler(this.nf);
         var3.applyKnownPrototype(false);
         aps var4 = new aps(this.nf);
         var4.xK();
      } else {
         Assert.a(this.nf.getPrototype() != null, "Routine should have at least a wildcard prototype at this stage");
         IEPrototypeHandler var1 = this.Uv.getPrototypeHandler(this.nf);
         boolean var2 = var1.refinePrototype();
         JY.iH("Wildcard prototype (refined: %b): %s", var2, this.nf.getPrototype());
      }

      return true;
   }
}
