package com.pnfsoftware.jebglobal;

import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEPrototypeHandler;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEStackManager;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEStatement;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IWildcardTypeManager;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.opt.OptimizerMode;
import com.pnfsoftware.jeb.core.units.code.asm.type.IPrototypeItem;
import com.pnfsoftware.jeb.util.logging.StructuredLogger;

public class awy extends avx {
   private static final StructuredLogger JY = aeg.q(awy.class);

   public awy() {
      super(avy.PV);
   }

   @Override
   protected boolean Dw() {
      this.q(JY);
      aps var1 = new aps(this.nf);
      aoe var2 = new aoe(this.nf);
      if (!var2.process(true, true, true)) {
         JY.error("The CFG could not be normalized!");
      } else {
         Object[] var10000 = new Object[0];
         JY.iH("NOTE: ECalls are no longer breaking!");
      }

      this.q(OptimizerMode.UNFRIENDLY, JY, "Final optimizations on the normalized CFG");
      IWildcardTypeManager var3 = this.nf.getWildcardTypeManager();
      IEStackManager var4 = this.nf.getStackManager();

      for (IEStatement var6 : this.nf.getCfg().instructions()) {
         var6.visitDepthPost(new awz(this, var4, var3));
      }

      Object[] var15 = new Object[0];
      int var8 = var1.RF();
      var15 = new Object[]{var8};
      var1.q();
      var1.xK();
      var1.Dw();

      for (IEStatement var7 : this.nf.getCfg().instructions()) {
         var7.visitDepthPost(new axa(this, var3));
      }

      for (IEStatement var13 : this.nf.getCfg().instructions()) {
         var13.visitDepthPost(new axb(this));
      }

      this.nf.invalidateDataFlowAnalysis();
      var15 = new Object[0];
      var8 = new anv(this.nf).xK();
      var15 = new Object[]{var8};
      if (this.gP.getPrototype() == null || this.gP.isAutoGeneratedPrototype()) {
         IEPrototypeHandler var12 = this.Uv.getPrototypeHandler(this.nf);
         var12.refinePrototype();
         var15 = new Object[]{var8, this.nf.getPrototype()};
         IPrototypeItem var14 = this.nf.getPrototype().resolve();
         this.gP.setPrototype(var14);
         var15 = new Object[]{this.gP.getPrototype()};
      }

      var15 = new Object[]{this.gP.getPrototype()};
      var15 = new Object[0];
      this.nf.invalidateDataFlowAnalysis();
      return true;
   }
}
