package com.pnfsoftware.jebglobal;

import com.pnfsoftware.jeb.core.units.IUnitLock;
import com.pnfsoftware.jeb.core.units.PassthroughUnitLock;
import com.pnfsoftware.jeb.core.units.code.asm.items.INativeItem;
import com.pnfsoftware.jeb.core.units.code.asm.items.INativeItemListener;
import com.pnfsoftware.jeb.core.units.code.asm.items.NativeItemEvent;
import com.pnfsoftware.jeb.core.units.code.asm.items.NativeItemEventSubType;
import com.pnfsoftware.jeb.core.units.code.asm.items.NativeItemEventType;
import com.pnfsoftware.jeb.util.concurrent.ACLock;
import com.pnfsoftware.jeb.util.logging.GlobalLog;
import com.pnfsoftware.jeb.util.logging.ILogger;
import com.pnfsoftware.jeb.util.serialization.annotations.Ser;
import com.pnfsoftware.jeb.util.serialization.annotations.SerId;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;

@Ser
public abstract class axj implements INativeItem, INativeItemListener {
   private static final ILogger q = GlobalLog.getLogger(axj.class);
   private static final String RF = "AutoGenerated";
   public static final int oW = 1;
   public static final int gO = 2;
   public static final int nf = 3;
   @SerId(1)
   private long xK = 0L;
   @SerId(2)
   private int Dw = -1;
   @SerId(3)
   private volatile int Uv;
   @SerId(4)
   protected String gP;
   @SerId(5)
   protected String za;
   @SerId(6)
   protected Map lm;
   @SerId(7)
   private boolean zz;
   @SerId(8)
   private volatile List JY;
   @SerId(9)
   private volatile boolean HF;
   @SerId(10)
   private volatile int LK;
   @SerId(11)
   private IUnitLock io;

   public axj(int var1, String var2) {
      this.Uv = var1 | 256 | 1;
      this.gP = var2;
   }

   public final void q(IUnitLock var1) {
      this.Me();
      if (var1 == null) {
         throw new NullPointerException("The lock cannot be null");
      } else if (this.io != null) {
         throw new IllegalStateException("Once set, the lock cannot be reset");
      } else {
         this.io = var1;
      }
   }

   public final IUnitLock za() {
      return (IUnitLock)(this.io != null ? this.io : PassthroughUnitLock.getInstance());
   }

   public final void q(long var1) {
      this.Me();
      this.xK = var1;
   }

   @Override
   public final long getItemId() {
      return this.xK;
   }

   public final void Dw(int var1) {
      this.Me();
      this.Dw = var1;
   }

   @Override
   public final int getIndex() {
      return this.Dw;
   }

   @Override
   public final String getAddress() {
      return this.getAddress(true);
   }

   @Override
   public String getAddress(boolean var1) {
      return null;
   }

   @Override
   public final String getSignature() {
      return this.getSignature(true);
   }

   @Override
   public String getSignature(boolean var1) {
      return this.getName(var1);
   }

   @Override
   public final String getSignature(boolean var1, boolean var2) {
      return this.getSignature(var1);
   }

   @Override
   public String getName(boolean var1) {
      if (!var1) {
         return this.gP;
      } else {
         return this.za != null ? this.za : this.gP;
      }
   }

   @Override
   public final String getName() {
      return this.getName(true);
   }

   @Override
   public void setName(String var1) {
      this.Me();

      try (ACLock var2 = this.za().a()) {
         if (var1 != null && var1.length() != 0) {
            if (this.gP != null && this.gP.equals(var1)) {
               return;
            }

            if (this.za != null && this.za.equals(var1)) {
               return;
            }
         } else {
            if (this.za == null) {
               return;
            }

            var1 = null;
         }

         String var3 = this.za;
         this.za = var1;
         this.q(new NativeItemEvent(NativeItemEventType.UPDATED, this, NativeItemEventSubType.RENAMED, var3));
      }
   }

   @Override
   public final boolean isRenamed() {
      return this.za != null && !this.za.equals(this.gP);
   }

   @Override
   public final boolean isInternal() {
      return (this.Uv & -2147483648) != 0;
   }

   @Override
   public final boolean isArtificial() {
      return (this.Uv & 1073741824) != 0;
   }

   public final boolean lm() {
      return (this.Uv & 268435456) != 0;
   }

   @Override
   public final int getGenericFlags() {
      return this.Uv;
   }

   @Override
   public boolean hasFlag(int var1) {
      return (this.Uv & var1) != 0;
   }

   @Override
   public final void setFlags(int var1) {
      this.q(var1, true);
   }

   public final void q(int var1, boolean var2) {
      this.Me();
      if (var1 != this.Uv) {
         try (ACLock var3 = this.za().a()) {
            this.Uv = var1;
            this.Dw(var2);
         }
      }
   }

   @Override
   public final void addFlags(int var1) {
      this.RF(var1, true);
   }

   public final void RF(int var1, boolean var2) {
      this.Me();

      try (ACLock var3 = this.za().a()) {
         int var4 = this.Uv | var1;
         if (var4 == this.Uv) {
            return;
         }

         this.Uv = var4;
         this.Dw(var2);
      }
   }

   @Override
   public final void removeFlags(int var1) {
      this.xK(var1, true);
   }

   public final void xK(int var1, boolean var2) {
      this.Me();

      try (ACLock var3 = this.za().a()) {
         int var4 = this.Uv & ~var1;
         if (var4 == this.Uv) {
            return;
         }

         this.Uv = var4;
         this.Dw(var2);
      }
   }

   public void Uv(int var1) {
      this.LK = var1;
   }

   public int zz() {
      return this.LK;
   }

   public boolean JY() {
      return (this.LK & 1) == 0;
   }

   public boolean HF() {
      return (this.LK & 2) == 0;
   }

   public boolean LK() {
      return (this.LK & 3) == 0;
   }

   @Override
   public synchronized boolean setAttribute(String var1, Object var2) {
      if (var2 == null) {
         return this.removeAttribute(var1);
      } else {
         this.Me();
         if (var1 == null) {
            throw new IllegalArgumentException("An attribute must have a non-null name");
         } else {
            try (ACLock var3 = this.za().a()) {
               if (this.lm == null) {
                  this.lm = new ConcurrentHashMap();
               }

               Object var4 = this.lm.put(var1, var2);
               if (var2 != var4) {
                  this.q(new NativeItemEvent(NativeItemEventType.UPDATED, this, NativeItemEventSubType.ATTRIBUTE_SET, var1));
               }
            }

            return true;
         }
      }
   }

   @Override
   public synchronized boolean removeAttribute(String var1) {
      this.Me();
      if (this.lm == null) {
         return false;
      } else {
         boolean var4;
         try (ACLock var2 = this.za().a()) {
            boolean var3 = this.lm.remove(var1) != null;
            if (var3) {
               this.q(new NativeItemEvent(NativeItemEventType.UPDATED, this, NativeItemEventSubType.ATTRIBUTE_REMOVED, var1));
            }

            var4 = var3;
         }

         return var4;
      }
   }

   @Override
   public synchronized boolean hasAttribute(String var1) {
      return this.lm == null ? false : this.lm.containsKey(var1);
   }

   @Override
   public boolean hasTrueAttribute(String var1) {
      if (this.lm == null) {
         return false;
      } else {
         Object var2 = this.lm.get(var1);
         return var2 instanceof Boolean ? (Boolean)var2 : false;
      }
   }

   @Override
   public synchronized Object getAttribute(String var1, Class var2) {
      if (this.lm == null) {
         return null;
      } else {
         Object var3 = this.lm.get(var1);
         return var2.isInstance(var3) ? var3 : null;
      }
   }

   @Override
   public synchronized Map getAttributes() {
      return this.lm == null ? Collections.emptyMap() : Collections.unmodifiableMap(this.lm);
   }

   @Override
   public void setAutoGenerated(boolean var1) {
      this.setAttribute("AutoGenerated", var1);
   }

   @Override
   public boolean isAutoGenerated() {
      Boolean var1 = (Boolean)this.getAttribute("AutoGenerated", Boolean.class);
      return var1 == null ? false : var1;
   }

   @Override
   public void onNativeItemEvent(NativeItemEvent var1) {
      this.q(var1);
   }

   protected void io() {
      this.HF = false;
   }

   protected void qa() {
      this.HF = true;
   }

   public boolean xK(boolean var1) {
      if (this.HF == var1) {
         return var1;
      } else {
         boolean var3;
         try (ACLock var2 = this.za().a()) {
            this.HF = var1;
            var3 = !var1;
         }

         return var3;
      }
   }

   public boolean Hk() {
      return this.HF;
   }

   protected void Me() {
      if (this.isDisposed()) {
         throw new IllegalStateException("Item is disposed");
      }
   }

   public final void PV() {
      this.dispose(true);
   }

   @Override
   public final void dispose(boolean var1) {
      if (!this.zz) {
         if (!this.oQ()) {
            q.error("Cannot dispose item: %s", this.toString());
         } else {
            try (ACLock var2 = this.za().a()) {
               this.RF();
               this.zz = true;
               this.c_();
               if (var1) {
                  this.q(new NativeItemEvent(NativeItemEventType.DISPOSED, this));
               }
            }
         }
      }
   }

   protected boolean oQ() {
      return true;
   }

   protected void RF() {
      this.za().verifyLocked();
   }

   protected void c_() {
      this.za().verifyLocked();
   }

   @Override
   public boolean isDisposed() {
      return this.zz;
   }

   @Override
   public void addListener(INativeItemListener var1) {
      if (var1 != null) {
         if (this.JY == null) {
            synchronized (this) {
               if (this.JY == null) {
                  this.JY = new CopyOnWriteArrayList();
               }
            }
         }

         this.JY.add(var1);
      }
   }

   @Override
   public void removeListener(INativeItemListener var1) {
      if (var1 != null) {
         if (this.JY != null) {
            this.JY.remove(var1);
         }
      }
   }

   public List xW() {
      return this.JY == null ? Collections.emptyList() : this.JY;
   }

   public int KT() {
      return this.JY == null ? 0 : this.JY.size();
   }

   public void q(NativeItemEvent var1) {
      if (!this.HF) {
         if (this.JY != null) {
            for (INativeItemListener var3 : this.JY) {
               if (var3 != var1.getItem()) {
                  var3.onNativeItemEvent(var1);
               }
            }
         }
      }
   }

   public final void q(NativeItemEventType var1) {
      this.q(new NativeItemEvent(var1, this));
   }

   protected final void Dw(boolean var1) {
      if (var1) {
         this.q(new NativeItemEvent(NativeItemEventType.UPDATED, this));
      }
   }

   protected final void Gf() {
      this.Dw(true);
   }

   protected final void Uv(boolean var1) {
      if (var1) {
         this.q(new NativeItemEvent(NativeItemEventType.MODIFIED, this));
      }
   }

   protected final void Ef() {
      this.Uv(true);
   }

   @Override
   public abstract String toString();
}
