package com.pnfsoftware.jebglobal;

import com.pnfsoftware.jeb.client.S;
import com.pnfsoftware.jeb.core.AbstractEnginesPlugin;
import com.pnfsoftware.jeb.core.IEnginesContext;
import com.pnfsoftware.jeb.core.IPluginInformation;
import com.pnfsoftware.jeb.core.PluginInformation;
import com.pnfsoftware.jeb.core.Version;
import com.pnfsoftware.jeb.core.properties.IPropertyDefinitionManager;
import com.pnfsoftware.jeb.core.units.INativeCodeUnit;
import com.pnfsoftware.jeb.core.units.IUnitProcessor;
import com.pnfsoftware.jeb.core.units.code.AddressableInstruction;
import com.pnfsoftware.jeb.core.units.code.NativeCommentManager;
import com.pnfsoftware.jeb.core.units.code.asm.items.INativeMethodItem;
import com.pnfsoftware.jeb.core.units.codeobject.CodeObjectUnitUtil;
import com.pnfsoftware.jeb.core.units.codeobject.IELFUnit;
import com.pnfsoftware.jeb.core.units.codeobject.ISymbolInformation;
import com.pnfsoftware.jeb.core.units.codeobject.ProcessorType;
import com.pnfsoftware.jeb.core.units.impl.MetaComment;
import com.pnfsoftware.jeb.util.encoding.Conversion;
import com.pnfsoftware.jeb.util.events.IEventListener;
import com.pnfsoftware.jeb.util.format.Formatter;
import com.pnfsoftware.jeb.util.format.Strings;
import com.pnfsoftware.jeb.util.logging.GlobalLog;
import com.pnfsoftware.jeb.util.logging.ILogger;
import java.io.InputStream;
import java.util.List;
import java.util.Map;

public class bei extends AbstractEnginesPlugin {
   private static final ILogger oW = GlobalLog.getLogger(bei.class);
   static boolean q = true;
   static boolean RF = true;
   static boolean xK = true;
   public static final String[] Dw = new String[]{
      "_kDartVmSnapshotData", "_kDartVmSnapshotInstructions", "_kDartIsolateSnapshotData", "_kDartIsolateSnapshotInstructions"
   };
   public static final String Uv = "dart_aot_snapshots";
   private IEnginesContext gO;
   private IEventListener nf;

   @Override
   public IPluginInformation getPluginInformation() {
      return new PluginInformation(
         S.L("Dart AOT snapshots annotator"),
         S.L("Annotate AOT snapshots generated by Dart 2.10 and above (= Flutter 1.22 and above). Provide method names and pool strings."),
         "PNF Software",
         Version.create(1, 0, 0)
      );
   }

   @Override
   public void load(IEnginesContext var1) {
      this.gO = var1;
      this.nf = new bej(this);
      var1.addListener(this.nf);
   }

   @Override
   public void dispose() {
      if (this.nf != null) {
         this.gO.removeListener(this.nf);
         this.nf = null;
      }
   }

   @Override
   public void execute(IEnginesContext var1, Map var2) {
      oW.debug(S.L("This plugin is auto-executed on any newly created ELF unit."));
   }

   private bek q(IELFUnit var1) {
      if (!var1.isProcessed()) {
         return null;
      } else {
         bek var2 = (bek)var1.getData("dart_aot_snapshots");
         if (var2 != null) {
            return var2;
         } else {
            int[] var3 = new int[Dw.length];
            int var4 = 0;

            for (String var8 : Dw) {
               ISymbolInformation var9 = CodeObjectUnitUtil.findSymbolByName(var1, var8);
               if (var9 == null) {
                  break;
               }

               var3[var4] = (int)var9.getSymbolRelativeAddress();
               var4++;
            }

            if (var4 != Dw.length) {
               return null;
            } else {
               int var17 = var3[0];
               int var18 = var3[1];
               int var19 = var3[2];
               int var20 = var3[3];

               try {
                  label80: {
                     Object var11;
                     try (InputStream var10 = var1.getInput().getStream()) {
                        byte[] var21 = com.pnfsoftware.jeb.util.io.IO.readInputStream(var10);
                        if (bek.q(var21, var17) && bek.q(var21, var19)) {
                           var2 = new bek(var21, var17, var18, var19, var20);
                           break label80;
                        }

                        var11 = null;
                     }

                     return (bek)var11;
                  }
               } catch (Exception var15) {
                  oW.catchingSilent(var15);
                  return null;
               }

               var1.setData("dart_aot_snapshots", var2, false);
               return var2;
            }
         }
      }
   }

   private boolean q(IELFUnit var1, bek var2) {
      if (!var1.isProcessed()) {
         return false;
      } else if (Boolean.TRUE.equals(var1.getData("dart_aot_info_generated"))) {
         return true;
      } else {
         var1.setData("dart_aot_info_generated", Boolean.TRUE, true);
         IUnitProcessor var3 = var1.getUnitProcessor();
         IPropertyDefinitionManager var4 = var1.getPropertyDefinitionManager();
         bel var5 = new bel(var2, "dart_aot_snapshots", var3, var1, var4);
         var5.process();
         var1.addChild(var5);
         return true;
      }
   }

   private boolean q(bek var1, INativeCodeUnit var2, boolean var3) {
      if (!var2.isProcessed()) {
         return false;
      } else if (!var3 && !var2.isAnalysisCompleted()) {
         return false;
      } else if (Boolean.TRUE.equals(var2.getData("dart_aot_annotations_applied"))) {
         return true;
      } else {
         var2.setData("dart_aot_annotations_applied", Boolean.TRUE, true);
         long var4 = var2.getVirtualImageBase();
         NativeCommentManager var6 = var2.getCommentManager();
         ProcessorType var7 = var2.getProcessor().getType();

         label108:
         for (ber var9 : var1.xK()) {
            if (var9 instanceof beo var10) {
               for (bep var12 : var10.Dw) {
                  if (var12.Dw != null) {
                     long var13 = var4 + var12.Dw;
                     INativeMethodItem var15 = var2.getRoutine(var13);
                     if (var15 != null) {
                        if (RF && var15.getName().startsWith("sub_")) {
                           String var16 = var10.q + "__" + var12.q;
                           var15.setName(var16);
                        }

                        if (xK && var7 == ProcessorType.X86_64) {
                           for (AddressableInstruction var17 : var15.getData().getCFG().addressableInstructions()) {
                              String var18;
                              try {
                                 var18 = var17.getInstruction().toString();
                              } catch (Exception var24) {
                                 continue label108;
                              }

                              Integer var19 = null;
                              if (var7 == ProcessorType.X86_64) {
                                 int var20 = var18.indexOf("[r15+");
                                 if (var20 >= 0) {
                                    int var21 = var18.indexOf("]", var20);
                                    String var22 = var18.substring(var20 + 5, var21);
                                    int var23 = Conversion.stringToInt(var22, -1);
                                    if (var23 >= 0) {
                                       var19 = var23 / 8;
                                    }
                                 }
                              } else if (var7 == ProcessorType.X86 || var7 == ProcessorType.ARM || var7 == ProcessorType.ARM64) {
                                 continue label108;
                              }

                              if (var19 != null) {
                                 String var26 = this.q(var1, var19);
                                 if (var26 != null) {
                                    String var27 = Strings.ff(S.L("Pooled string: `%s`"), Formatter.escapeString(var26));
                                    var6.addMetaComment(var6.memoryToAddress(var17.getOffset()), new MetaComment(var27), false);
                                 }
                              }
                           }
                        }
                     }
                  }
               }
            }
         }

         return true;
      }
   }

   private String q(bek var1, int var2) {
      List var3 = var1.RF();
      if (var2 >= 0 && var2 < var3.size()) {
         Object var4 = var3.get(var2);
         if (var4 instanceof bet) {
            return var4.toString();
         }
      }

      return null;
   }
}
