package com.pnfsoftware.jebglobal;

public class cmn {
   private static final clg[] Ef = cmf.Dw;
   private static final clg[] cC = cmf.Dw;
   private static final clg[] sH = cmf.JY;
   private static final clg[] CE = cmf.JY;
   private static final clw wF = new cly(clz.xK, clz.q);
   private static final clw[] If = new clw[]{clz.nf, wF};
   static final cmf[] q = new cmf[]{
      new cmf("LWX", Ef, If),
      cmf.q,
      cmf.q,
      cmf.q,
      new cmf("LHX", Ef, If),
      cmf.q,
      new cmf("LBUX", Ef, If),
      cmf.q,
      new cmf("LDX", sH, If),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q
   };
   public static final cmf RF = new cmf("BPOSGE32", cmp.q, cmb.PV, Ef, clx.RF);
   public static final cmf xK = new cmf("BPOSGE32C", cmp.q, cmb.PV, Ef, clx.RF);
   public static final cmf Dw = new cmf("BPOSGE64", cmp.q, cmb.PV, sH, clx.RF);
   private static final clw[] Dz = new clw[]{clz.xK, clz.q};
   public static final cmf Uv = new cmf("INSV", Ef, Dz);
   public static final cmf oW = new cmf("DINSV", Ef, Dz);
   private static final clw[] mI = new clw[]{clz.nf, clz.q};
   public static final cmf[] gO = new cmf[]{
      new cmf("ADDU.QB", Ef, clz.Me),
      new cmf("SUBU.QB", Ef, clz.Me),
      cmf.q,
      cmf.q,
      new cmf("ADDU_S.QB", Ef, clz.Me),
      new cmf("SUBU_S.QB", Ef, clz.Me),
      new cmf("MULEU_S.PH.QBL", Ef, clz.Me),
      new cmf("MULEU_S.PH.QBR", Ef, clz.Me),
      new cmf("ADDU.PH", cC, clz.Me),
      new cmf("SUBU.PH", cC, clz.Me),
      new cmf("ADDQ.PH", Ef, clz.Me),
      new cmf("SUBQ.PH", Ef, clz.Me),
      new cmf("ADDU_S.PH", cC, clz.Me),
      new cmf("SUBU_S.PH", cC, clz.Me),
      new cmf("ADDQ_S.PH", Ef, clz.Me),
      new cmf("SUBQ_S.PH", Ef, clz.Me),
      new cmf("ADDSC", Ef, clz.Me),
      new cmf("ADDWC", Ef, clz.Me),
      new cmf("MODSUB", Ef, clz.Me),
      cmf.q,
      new cmf("RADDU.W.QB", Ef, mI),
      cmf.q,
      new cmf("ADDQ_S.W", Ef, clz.Me),
      new cmf("SUBQ_S.W", Ef, clz.Me),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      new cmf("MULEQ_S.W.PHL", Ef, clz.Me),
      new cmf("MULEQ_S.W.PHR", Ef, clz.Me),
      new cmf("MULQ_S.PH", cC, clz.Me),
      new cmf("MULQ_RS.PH", Ef, clz.Me)
   };
   private static clw[] jq = new clw[]{clz.xK, clz.q, clx.qa};
   public static final cmf[] nf = new cmf[]{
      new cmf("CMPU.EQ.QB", Ef, clz.qa),
      new cmf("CMPU.LT.QB", Ef, clz.qa),
      new cmf("CMPU.LE.QB", Ef, clz.qa),
      new cmf("PICK.QB", Ef, clz.Me),
      new cmf("CMPGU.EQ.QB", Ef, clz.Me),
      new cmf("CMPGU.LT.QB", Ef, clz.Me),
      new cmf("CMPGU.LE.QB", Ef, clz.Me),
      cmf.q,
      new cmf("CMP.EQ.PH", Ef, clz.qa),
      new cmf("CMP.LT.PH", Ef, clz.qa),
      new cmf("CMP.LE.PH", Ef, clz.qa),
      new cmf("PICK.PH", Ef, clz.Me),
      new cmf("PRECRQ.QB.PH", Ef, clz.Me),
      new cmf("PRECR.QB.PH", cC, clz.Me),
      new cmf("PACKRL.PH", Ef, clz.Me),
      new cmf("PRECRQU_S.QB.PH", Ef, clz.Me),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      new cmf("PRECRQ.PH.W", Ef, clz.Me),
      new cmf("PRECRQ_RS.PH.W", Ef, clz.Me),
      cmf.q,
      cmf.q,
      new cmf("CMPGDU.EQ.QB", cC, clz.Me),
      new cmf("CMPGDU.LT.QB", cC, clz.Me),
      new cmf("CMPGDU.LE.QB", cC, clz.Me),
      cmf.q,
      cmf.q,
      cmf.q,
      new cmf("PRECR_SRA.PH.W", cC, jq),
      new cmf("PRECR_SRA_R.PH.W", cC, jq)
   };
   private static final clw[] ui = new clw[]{clz.nf, clz.xK};
   private static final clw[] TX = new clw[]{clz.nf, clx.cC};
   private static final clw[] Rr = new clw[]{clz.nf, clx.sH};
   public static final cmf[] gP = new cmf[]{
      cmf.q,
      new cmf("ABSQ_S.QB", cC, ui),
      new cmf("REPL.QB", Ef, Rr),
      new cmf("REPLV.QB", Ef, ui),
      new cmf("PRECEQU.PH.QBL", Ef, ui),
      new cmf("PRECEQU.PH.QBR", Ef, ui),
      new cmf("PRECEQU.PH.QBLA", Ef, ui),
      new cmf("PRECEQU.PH.QBRA", Ef, ui),
      cmf.q,
      new cmf("ABSQ_S.PH", Ef, ui),
      new cmf("REPL.PH", Ef, TX),
      new cmf("REPLV.PH", Ef, ui),
      new cmf("PRECEQ.W.PHL", Ef, ui),
      new cmf("PRECEQ.W.PHR", Ef, ui),
      cmf.q,
      cmf.q,
      cmf.q,
      new cmf("ABSQ_S.W", Ef, ui),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      new cmf("BITREV", Ef, ui),
      new cmf("PRECEU.PH.QBL", Ef, ui),
      new cmf("PRECEU.PH.QBR", Ef, ui),
      new cmf("PRECEU.PH.QBLA", Ef, ui),
      new cmf("PRECEU.PH.QBRA", Ef, ui)
   };
   private static final clw[] EB = new clw[]{clz.nf, clz.xK, clx.wF};
   private static final clw[] Xo = new clw[]{clz.nf, clz.xK, clx.CE};
   private static final clw[] Bu = new clw[]{clz.nf, clz.xK, clx.If};
   private static final clw[] IN = new clw[]{clz.nf, clz.xK, clz.q};
   public static final cmf[] za = new cmf[]{
      new cmf("SHLL.QB", Ef, Xo),
      new cmf("SHRL.QB", Ef, Xo),
      new cmf("SHLLV.QB", Ef, IN),
      new cmf("SHRLV.QB", Ef, IN),
      new cmf("SHRA.QB", cC, Xo),
      new cmf("SHRA_R.QB", cC, Xo),
      new cmf("SHRAV.QB", cC, IN),
      new cmf("SHRAV_R.QB", cC, IN),
      new cmf("SHLL.PH", Ef, EB),
      new cmf("SHRA.PH", Ef, EB),
      new cmf("SHLLV.PH", Ef, IN),
      new cmf("SHRAV.PH", Ef, IN),
      new cmf("SHLL_S.PH", Ef, EB),
      new cmf("SHRA_R.PH", Ef, EB),
      new cmf("SHLLV_S.PH", Ef, IN),
      new cmf("SHRAV_R.PH", Ef, IN),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      new cmf("SHLL_S.W", Ef, Bu),
      new cmf("SHRA_R.W", Ef, Bu),
      new cmf("SHLLV_S.W", Ef, IN),
      new cmf("SHRAV_R.W", Ef, IN),
      cmf.q,
      new cmf("SHRL.PH", cC, EB),
      cmf.q,
      new cmf("SHRLV.PH", cC, IN),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q
   };
   public static final cmf[] lm = new cmf[]{
      new cmf("ADDUH.QB", cC, clz.Me),
      new cmf("SUBUH.QB", cC, clz.Me),
      new cmf("ADDUH_R.QB", cC, clz.Me),
      new cmf("SUBUH_R.QB", cC, clz.Me),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      new cmf("ADDQH.PH", cC, clz.Me),
      new cmf("SUBQH.PH", cC, clz.Me),
      new cmf("ADDQH_R.PH", cC, clz.Me),
      new cmf("SUBQH_R.PH", cC, clz.Me),
      new cmf("MUL.PH", cC, clz.Me),
      cmf.q,
      new cmf("MUL_S.PH", cC, clz.Me),
      cmf.q,
      new cmf("ADDQH.W", cC, clz.Me),
      new cmf("SUBQH.W", cC, clz.Me),
      new cmf("ADDQH_R.W", cC, clz.Me),
      new cmf("SUBQH_R.W", cC, clz.Me),
      cmf.q,
      cmf.q,
      new cmf("MULQ_S.W", cC, clz.Me),
      new cmf("MULQ_RS.W", cC, clz.Me),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q
   };
   private static final clw[] rL = new clw[]{clz.JY, clz.q, clz.xK};
   public static final cmf[] zz = new cmf[]{
      new cmf("DPA.W.PH", cC, rL),
      new cmf("DPS.W.PH", cC, rL),
      new cmf("MULSA.W.PH", cC, rL),
      new cmf("DPAU.H.QBL", Ef, rL),
      new cmf("DPAQ_S.W.PH", Ef, rL),
      new cmf("DPSQ_S.W.PH", Ef, rL),
      new cmf("MULSAQ_S.W.PH", Ef, rL),
      new cmf("DPAU.H.QBR", Ef, rL),
      new cmf("DPAX.W.PH", cC, rL),
      new cmf("DPSX.W.PH", cC, rL),
      cmf.q,
      new cmf("DPSU.H.QBL", Ef, rL),
      new cmf("DPAQ_SA.L.W", Ef, rL),
      new cmf("DPSQ_SA.L.W", Ef, rL),
      cmf.q,
      new cmf("DPSU.H.QBR", Ef, rL),
      new cmf("MAQ_SA.W.PHL", Ef, rL),
      cmf.q,
      new cmf("MAQ_SA.W.PHR", Ef, rL),
      cmf.q,
      new cmf("MAQ_S.W.PHL", Ef, rL),
      cmf.q,
      new cmf("MAQ_S.W.PHR", Ef, rL),
      cmf.q,
      new cmf("DPAQX_S.W.PH", cC, rL),
      new cmf("DPSQX_S.W.PH", cC, rL),
      new cmf("DPAQX_SA.W.PH", cC, rL),
      new cmf("DPSQX_SA.W.PH", cC, rL),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q
   };
   public static final cmf[] JY = new cmf[]{
      new cmf("APPEND", cC, jq),
      new cmf("PREPEND", cC, jq),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      new cmf("BALIGN", cC, clz.xK, clz.q, clx.Dz),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q
   };
   private static final clw[] eJ = new clw[]{clz.xK, clz.JY, clx.If};
   private static final clw[] YN = new clw[]{clz.xK, clz.JY, clz.q};
   private static final clw[] Rv = new clw[]{clz.q, clz.JY};
   private static final clw[] zx = new clw[]{clz.nf, clx.Rr};
   private static final clw[] ZT = new clw[]{clz.q, clx.TX};
   public static final cmf[] HF = new cmf[]{
      new cmf("EXTR.W", Ef, eJ),
      new cmf("EXTRV.W", Ef, YN),
      new cmf("EXTP", Ef, eJ),
      new cmf("EXTPV", Ef, YN),
      new cmf("EXTR_R.W", Ef, eJ),
      new cmf("EXTRV_R.W", Ef, YN),
      new cmf("EXTR_RS.W", Ef, eJ),
      new cmf("EXTRV_RS.W", Ef, YN),
      cmf.q,
      cmf.q,
      new cmf("EXTPDP", Ef, eJ),
      new cmf("EXTPDPV", Ef, YN),
      cmf.q,
      cmf.q,
      new cmf("EXTR_S.H", Ef, eJ),
      new cmf("EXTRV_S.H", Ef, YN),
      cmf.q,
      cmf.q,
      new cmf("RDDSP", Ef, zx),
      new cmf("WRDSP", Ef, ZT),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      new cmf("SHILO", Ef, clz.JY, clx.jq),
      new cmf("SHILOV", Ef, clz.JY, clz.q),
      cmf.q,
      cmf.q,
      cmf.q,
      new cmf("MTHLIP", Ef, Rv)
   };
   static final cmf[] LK = new cmf[]{
      new cmf("MFHI", cmf.oW, clz.nf, clz.zz),
      new cmf("MTHI", cmf.oW, clz.q, clz.JY),
      new cmf("MFLO", cmf.oW, clz.nf, clz.zz),
      new cmf("MTLO", cmf.oW, clz.q, clz.JY)
   };
   static final cmf[] io = new cmf[]{
      new cmf("MADD", cmf.oW, rL), new cmf("MADDU", cmf.oW, rL), cmf.q, cmf.q, new cmf("MSUB", cmf.oW, rL), new cmf("MSUBU", cmf.oW, rL), cmf.q, cmf.q
   };
   static final cmf[] qa = new cmf[]{new cmf("MULT", cmf.oW, rL), new cmf("MULTU", cmf.oW, rL), cmf.q, cmf.q, cmf.q, cmf.q, cmf.q, cmf.q};
   public static final cmf[] Hk = new cmf[]{
      new cmf("ADDU.OB", sH, clz.Me),
      new cmf("SUBU.OB", sH, clz.Me),
      cmf.q,
      cmf.q,
      new cmf("ADDU_S.OB", sH, clz.Me),
      new cmf("SUBU_S.OB", sH, clz.Me),
      new cmf("MULEU_S.QH.OBL", sH, clz.Me),
      new cmf("MULEU_S.QH.OBR", sH, clz.Me),
      new cmf("ADDU.QH", CE, clz.Me),
      new cmf("SUBU.QH", CE, clz.Me),
      new cmf("ADDQ.QH", sH, clz.Me),
      new cmf("SUBQ.QH", sH, clz.Me),
      new cmf("ADDU_S.QH", CE, clz.Me),
      new cmf("SUBU_S.QH", CE, clz.Me),
      new cmf("ADDQ_S.QH", sH, clz.Me),
      new cmf("SUBQ_S.QH", sH, clz.Me),
      cmf.q,
      cmf.q,
      new cmf("ADDQ.PW", sH, clz.Me),
      new cmf("SUBQ.PW", sH, clz.Me),
      new cmf("RADDU.L.OB", sH, mI),
      cmf.q,
      new cmf("ADDQ_S.PW", sH, clz.Me),
      new cmf("SUBQ_S.PW", sH, clz.Me),
      new cmf("ADDUH.OB", CE, clz.Me),
      new cmf("SUBUH.OB", CE, clz.Me),
      new cmf("ADDUH_R.OB", CE, clz.Me),
      new cmf("SUBUH_R.OB", CE, clz.Me),
      new cmf("MULEQ_S.PW.QHL", sH, clz.Me),
      new cmf("MULEQ_S.PW.QHR", sH, clz.Me),
      cmf.q,
      new cmf("MULQ_RS.QH", sH, clz.Me)
   };
   public static final cmf[] Me = new cmf[]{
      new cmf("CMPU.EQ.OB", sH, clz.qa),
      new cmf("CMPU.LT.OB", sH, clz.qa),
      new cmf("CMPU.LE.OB", sH, clz.qa),
      new cmf("PICK.OB", sH, clz.Me),
      new cmf("CMPGU.EQ.OB", sH, clz.Me),
      new cmf("CMPGU.LT.OB", sH, clz.Me),
      new cmf("CMPGU.LE.OB", sH, clz.Me),
      cmf.q,
      new cmf("CMP.EQ.QH", sH, clz.qa),
      new cmf("CMP.LT.QH", sH, clz.qa),
      new cmf("CMP.LE.QH", sH, clz.qa),
      new cmf("PICK.QH", sH, clz.Me),
      new cmf("PRECRQ.OB.QH", sH, clz.Me),
      new cmf("PRECR.OB.QH", CE, clz.Me),
      new cmf("PACKRL.PW", sH, clz.Me),
      new cmf("PRECRQU_S.OB.QH", sH, clz.Me),
      new cmf("CMP.EQ.PW", sH, clz.qa),
      new cmf("CMP.LT.PW", sH, clz.qa),
      new cmf("CMP.LE.PW", sH, clz.qa),
      new cmf("PICK.PW", sH, clz.Me),
      new cmf("PRECRQ.QH.PW", sH, clz.Me),
      new cmf("PRECRQ_RS.QH.PW", sH, clz.Me),
      cmf.q,
      cmf.q,
      new cmf("CMPGDU.EQ.OB", CE, clz.Me),
      new cmf("CMPGDU.LT.OB", CE, clz.Me),
      new cmf("CMPGDU.LE.OB", CE, clz.Me),
      cmf.q,
      new cmf("PRECRQ.PW.L", sH, clz.Me),
      cmf.q,
      new cmf("PRECR_SRA.QH.PW", CE, jq),
      new cmf("PRECR_SRA_R.QH.PW", CE, jq)
   };
   public static final cmf[] PV = new cmf[]{
      cmf.q,
      new cmf("ABSQ_S.OB", CE, ui),
      new cmf("REPL.OB", sH, Rr),
      new cmf("REPLV.OB", sH, ui),
      new cmf("PRECEQU.QH.OBL", sH, ui),
      new cmf("PRECEQU.QH.OBR", sH, ui),
      new cmf("PRECEQU.QH.OBLA", sH, ui),
      new cmf("PRECEQU.QH.OBRA", sH, ui),
      cmf.q,
      new cmf("ABSQ_S.QH", sH, ui),
      new cmf("REPL.QH", sH, TX),
      new cmf("REPLV.QH", sH, ui),
      new cmf("PRECEQ.PW.QHL", sH, ui),
      new cmf("PRECEQ.PW.QHR", sH, ui),
      new cmf("PRECEQ.PW.QHLA", sH, ui),
      new cmf("PRECEQ.PW.QHRA", sH, ui),
      cmf.q,
      new cmf("ABSQ_S.PW", sH, ui),
      new cmf("REPL.PW", sH, TX),
      new cmf("REPLV.PW", sH, ui),
      new cmf("PRECEQ.L.PWL", sH, ui),
      new cmf("PRECEQ.L.PWR", sH, ui),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      new cmf("PRECEU.QH.OBL", sH, ui),
      new cmf("PRECEU.QH.OBR", sH, ui),
      new cmf("PRECEU.QH.OBLA", sH, ui),
      new cmf("PRECEU.QH.OBRA", sH, ui)
   };
   public static final cmf[] oQ = new cmf[]{
      new cmf("SHLL.OB", sH, Xo),
      new cmf("SHRL.OB", sH, Xo),
      new cmf("SHLLV.OB", sH, IN),
      new cmf("SHRLV.OB", sH, IN),
      new cmf("SHRA.OB", CE, Xo),
      new cmf("SHRA_R.OB", CE, Xo),
      new cmf("SHRAV.OB", CE, IN),
      new cmf("SHRAV_R.OB", CE, IN),
      new cmf("SHLL.QH", sH, EB),
      new cmf("SHRA.QH", sH, EB),
      new cmf("SHLLV.QH", sH, IN),
      new cmf("SHRAV.QH", sH, IN),
      new cmf("SHLL_S.QH", sH, EB),
      new cmf("SHRA_R.QH", sH, EB),
      new cmf("SHLLV_S.QH", sH, IN),
      new cmf("SHRAV_R.QH", sH, IN),
      new cmf("SHLL.PW", sH, Bu),
      new cmf("SHRA.PW", sH, Bu),
      new cmf("SHLLV.PW", sH, IN),
      new cmf("SHRAV.PW", sH, IN),
      new cmf("SHLL_S.PW", sH, Bu),
      new cmf("SHRA_R.PW", sH, Bu),
      new cmf("SHLLV_S.PW", sH, IN),
      new cmf("SHRAV_R.PW", sH, IN),
      cmf.q,
      new cmf("SHRL.QH", CE, EB),
      cmf.q,
      new cmf("SHRLV.QH", CE, IN),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q
   };
   public static final cmf[] xW = new cmf[]{
      new cmf("DPA.W.QH", CE, rL),
      new cmf("DPS.W.QH", CE, rL),
      cmf.q,
      new cmf("DPAU.H.OBL", sH, rL),
      new cmf("DPAQ_S.W.QH", sH, rL),
      new cmf("DPSQ_S.W.QH", sH, rL),
      new cmf("MULSAQ_S.W.QH", sH, rL),
      new cmf("DPAU.H.OBR", sH, rL),
      new cmf("DPAX.W.QH", CE, rL),
      new cmf("DPSX.W.QH", CE, rL),
      cmf.q,
      new cmf("DPSU.H.OBL", sH, rL),
      new cmf("DPAQ_SA.L.PW", sH, rL),
      new cmf("DPSQ_SA.L.PW", sH, rL),
      new cmf("MULSAQ_S.L.PW", sH, rL),
      new cmf("DPSU.H.OBR", sH, rL),
      new cmf("MAQ_SA.W.QHLL", sH, rL),
      new cmf("MAQ_SA.W.QHLR", sH, rL),
      new cmf("MAQ_SA.W.QHRL", sH, rL),
      new cmf("MAQ_SA.W.QHRR", sH, rL),
      new cmf("MAQ_S.W.QHLL", sH, rL),
      new cmf("MAQ_S.W.QHLR", sH, rL),
      new cmf("MAQ_S.W.QHRL", sH, rL),
      new cmf("MAQ_S.W.QHRR", sH, rL),
      cmf.q,
      new cmf("DMADD", sH, rL),
      cmf.q,
      new cmf("DMSUB", sH, rL),
      new cmf("MAQ_S.L.PWL", sH, rL),
      new cmf("DMADDU", sH, rL),
      new cmf("MAQ_S.L.PWR", sH, rL),
      new cmf("DMSUBU", sH, rL)
   };
   public static final cmf[] KT = new cmf[]{
      new cmf("DAPPEND", cC, jq),
      new cmf("PREPENDW", cC, jq),
      cmf.q,
      new cmf("PREPENDD", cC, jq),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      new cmf("DBALIGN", cC, clz.xK, clz.q, clx.mI),
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q,
      cmf.q
   };
   public static final cmf[] Gf = new cmf[]{
      new cmf("DEXTR.W", sH, eJ),
      new cmf("DEXTRV.W", sH, YN),
      new cmf("DEXTP", sH, eJ),
      new cmf("DEXTPV", sH, YN),
      new cmf("DEXTR_R.W", sH, eJ),
      new cmf("DEXTRV_R.W", sH, YN),
      new cmf("DEXTR_RS.W", sH, eJ),
      new cmf("DEXTRV_RS.W", sH, YN),
      cmf.q,
      cmf.q,
      new cmf("DEXTPDP", sH, eJ),
      new cmf("DEXTPDPV", sH, YN),
      cmf.q,
      cmf.q,
      new cmf("DEXTR_S.H", sH, eJ),
      new cmf("DEXTRV_S.H", sH, YN),
      new cmf("DEXTR.L", sH, eJ),
      new cmf("DEXTRV.L", sH, YN),
      cmf.q,
      cmf.q,
      new cmf("DEXTR_R.L", sH, eJ),
      new cmf("DEXTRV_R.L", sH, YN),
      new cmf("DEXTR_RS.L", sH, eJ),
      new cmf("DEXTRV_RS.L", sH, YN),
      cmf.q,
      cmf.q,
      new cmf("DSHILO", sH, clz.JY, clx.ui),
      new cmf("DSHILOV", sH, clz.JY, clz.q),
      cmf.q,
      cmf.q,
      cmf.q,
      new cmf("DMTHLIP", sH, Rv)
   };
}
