package com.pnfsoftware.jebglobal;

import com.pnfsoftware.jeb.core.units.INativeCodeUnit;
import com.pnfsoftware.jeb.core.units.UnitUtil;
import com.pnfsoftware.jeb.core.units.code.android.DexUtil;
import com.pnfsoftware.jeb.core.units.code.android.IApkUnit;
import com.pnfsoftware.jeb.core.units.code.android.IDexUnit;
import com.pnfsoftware.jeb.core.units.code.android.dex.IDexMethod;
import com.pnfsoftware.jeb.core.units.code.android.dex.IDexType;
import com.pnfsoftware.jeb.core.units.codeobject.IELFUnit;
import com.pnfsoftware.jeb.util.format.Strings;
import com.pnfsoftware.jeb.util.logging.GlobalLog;
import com.pnfsoftware.jeb.util.logging.ILogger;
import java.util.concurrent.atomic.AtomicInteger;

public class N {
   private static final ILogger q = GlobalLog.getLogger(N.class);
   private AtomicInteger RF = new AtomicInteger();
   private INativeCodeUnit xK;
   private IELFUnit Dw;
   private IApkUnit Uv;

   public N(INativeCodeUnit var1) {
      if (var1 == null) {
         throw new IllegalArgumentException();
      } else {
         this.xK = var1;
      }
   }

   public boolean q() {
      if (this.RF.getAndIncrement() != 0) {
         throw new IllegalStateException();
      } else if (this.xK.getTypeLibraryService() == null || this.xK.getTypeLibraryService().findTypeBySignature("JNIEnv", null) == null) {
         return false;
      } else if (!(this.xK.getCodeObjectContainer() instanceof IELFUnit)) {
         return false;
      } else {
         this.Dw = (IELFUnit)this.xK.getCodeObjectContainer();
         this.Uv = (IApkUnit)UnitUtil.findAncestor(this.Dw, IApkUnit.class, false);
         return this.Uv != null && this.Uv.getDex() != null && this.Uv.getDex().isProcessed();
      }
   }

   public int RF() {
      if (this.RF.getAndIncrement() != 1) {
         throw new IllegalStateException();
      } else {
         int var1 = 0;
         IDexUnit var2 = this.Uv.getDex();

         for (IDexMethod var4 : var2.getMethods()) {
            if (var4.isInternal() && var4.getData().isNative()) {
               String[] var5 = DexUtil.generateDefaultJniNames(var4.getSignature(false));
               if (var5 != null && var5.length == 2) {
                  axp var6 = ((abg)this.xK).RF(var5[0]);
                  if (var6 == null) {
                     var6 = ((abg)this.xK).RF(var5[1]);
                  }

                  if (var6 != null && (var6.getPrototype() == null || var6.isAutoGeneratedPrototype())) {
                     Object[] var10000 = new Object[]{var6.getSignature()};
                     StringBuilder var7 = new StringBuilder();
                     int var8 = 0;
                     String var9 = var4.getReturnType().getSignature(false);
                     var9 = this.q(var9);
                     var7.append(var9);
                     var7.append(" ");
                     var7.append(var4.getName(false));
                     var7.append("(JNIEnv* env");
                     var8++;
                     if (!var4.getData().isStatic()) {
                        var7.append(", jobject obj");
                        var8++;
                     }

                     for (IDexType var11 : var4.getParameterTypes()) {
                        var9 = var11.getSignature(false);
                        var9 = this.q(var9);
                        Strings.ff(var7, ", %s param%d", var9, var8);
                        var8++;
                     }

                     var7.append(")");
                     String var16 = var7.toString();
                     if (this.xK.setRoutineSignature(var6, var16, true)) {
                        var1++;
                     }
                  }
               }
            }
         }

         return var1;
      }
   }

   private String q(String var1) {
      switch (var1) {
         case "Ljava/lang/String;":
            return "jstring";
         case "Ljava/lang/Class;":
            return "jclass";
         case "Z":
            return "jboolean";
         case "B":
            return "jbyte";
         case "C":
            return "jchar";
         case "S":
            return "jshort";
         case "I":
            return "jint";
         case "J":
            return "jlong";
         case "F":
            return "jfloat";
         case "D":
            return "jdouble";
         case "V":
            return "void";
         case "[Z":
            return "jbooleanArray";
         case "[B":
            return "jbyteArray";
         case "[C":
            return "jcharArray";
         case "[S":
            return "jshortArray";
         case "[I":
            return "jintArray";
         case "[J":
            return "jlongArray";
         case "[F":
            return "jfloatArray";
         case "[D":
            return "jdoubleArray";
         default:
            return var1.startsWith("[") ? "jarray" : "jobject";
      }
   }
}
