package com.pnfsoftware.jeb.corei.parsers.apk;

public enum zp {
   pC("android.permission.ACCESS_CACHE_FILESYSTEM"),
   A("android.permission.ACCESS_CHECKIN_PROPERTIES"),
   kS("android.permission.ACCESS_COARSE_LOCATION", yt.A, KD.wS),
   wS("android.permission.ACCESS_DRM_CERTIFICATES"),
   UT("android.permission.ACCESS_FINE_LOCATION", yt.A, KD.wS),
   E("android.permission.ACCESS_FM_RADIO"),
   sY("android.permission.ACCESS_LOCATION_EXTRA_COMMANDS", yt.pC),
   ys("android.permission.ACCESS_MOCK_LOCATION"),
   ld("android.permission.ACCESS_MTP"),
   gp("android.permission.ACCESS_NETWORK_CONDITIONS"),
   oT("android.permission.ACCESS_NETWORK_STATE", yt.pC),
   fI("android.permission.ACCESS_NOTIFICATIONS"),
   WR("android.permission.ACCESS_NOTIFICATION_POLICY", yt.pC),
   NS("android.permission.ACCESS_SURFACE_FLINGER"),
   vP("android.permission.ACCESS_WIFI_STATE", yt.pC),
   xC("android.permission.ACCOUNT_MANAGER"),
   ED("com.android.voicemail.permission.ADD_VOICEMAIL", yt.A, KD.E),
   Sc("android.permission.ALLOCATE_AGGRESSIVE"),
   ah("android.permission.ALLOW_ANY_CODEC_FOR_PLAYBACK"),
   eP("android.permission.ANSWER_PHONE_CALLS"),
   UO("android.permission.BACKUP"),
   Ab("android.permission.BATTERY_STATS"),
   rl("android.permission.BIND_ACCESSIBILITY_SERVICE"),
   z("android.permission.BIND_APPWIDGET"),
   Ek("android.permission.BIND_AUTOFILL_SERVICE"),
   hK("android.permission.BIND_CARRIER_MESSAGING_SERVICE"),
   Er("android.permission.BIND_CARRIER_SERVICES"),
   FE("android.permission.BIND_CHOOSER_TARGET_SERVICE"),
   Aj("android.permission.BIND_CONDITION_PROVIDER_SERVICE"),
   EX("android.permission.BIND_CONNECTION_SERVICE"),
   LM("android.permission.BIND_DEVICE_ADMIN"),
   mv("android.permission.BIND_DIRECTORY_SEARCH"),
   sO("android.permission.BIND_DREAM_SERVICE"),
   os("android.permission.BIND_IMS_SERVICE"),
   Cu("android.permission.BIND_INCALL_SERVICE"),
   hZ("android.permission.BIND_INPUT_METHOD"),
   UW("android.permission.BIND_KEYGUARD_APPWIDGET"),
   PR("android.permission.BIND_MIDI_DEVICE_SERVICE"),
   cX("android.permission.BIND_NETWORK_RECOMMENDATION_SERVICE"),
   DQ("android.permission.BIND_NFC_SERVICE"),
   ZN("android.permission.BIND_NOTIFICATION_ASSISTANT_SERVICE"),
   OB("android.permission.BIND_NOTIFICATION_LISTENER_SERVICE"),
   pF("android.permission.BIND_PRINT_RECOMMENDATION_SERVICE"),
   Bc("android.permission.BIND_PRINT_SERVICE"),
   OI("android.permission.BIND_QUICK_SETTINGS_TILE"),
   Bf("android.permission.BIND_REMOTEVIEWS"),
   Pe("android.permission.BIND_RESOLVER_RANKER_SERVICE"),
   ck("android.permission.BIND_RUNTIME_PERMISSION_PRESENTER_SERVICE"),
   RW("android.permission.BIND_SCREENING_SERVICE"),
   e("android.permission.BIND_TELECOM_CONNECTION_SERVICE"),
   xM("android.permission.BIND_TEXT_SERVICE"),
   kU("android.permission.BIND_TRUST_AGENT"),
   Kq("android.permission.BIND_TV_INPUT"),
   go("android.permission.BIND_TV_REMOTE_SERVICE"),
   JF("android.permission.BIND_VISUAL_VOICEMAIL_SERVICE"),
   Nq("android.permission.BIND_VOICE_INTERACTION"),
   pg("android.permission.BIND_VPN_SERVICE"),
   gj("android.permission.BIND_VR_LISTENER_SERVICE"),
   ZD("android.permission.BIND_WALLPAPER"),
   DL("android.permission.BLUETOOTH", yt.pC),
   UH("android.permission.BLUETOOTH_ADMIN", yt.pC),
   VD("android.permission.BLUETOOTH_PRIVILEGED"),
   Xs("android.permission.BODY_SENSORS", yt.A, KD.sY),
   KV("android.permission.BRICK"),
   FK("android.permission.BROADCAST_NETWORK_PRIVILEGED"),
   Bi("android.permission.BROADCAST_PACKAGE_REMOVED"),
   wQ("android.permission.BROADCAST_SMS"),
   PZ("android.permission.BROADCAST_STICKY", yt.pC),
   Ip("android.permission.BROADCAST_WAP_PUSH"),
   Fm("android.permission.CALL_PHONE", yt.A, KD.E),
   FM("android.permission.CALL_PRIVILEGED"),
   Wn("android.permission.CAMERA", yt.A, KD.A),
   gy("android.permission.CAMERA_DISABLE_TRANSMIT_LED"),
   pt("android.permission.CAPTURE_AUDIO_HOTWORD"),
   uE("android.permission.CAPTURE_AUDIO_OUTPUT"),
   Um("android.permission.CAPTURE_SECURE_VIDEO_OUTPUT"),
   Ta("android.permission.CAPTURE_TV_INPUT"),
   So("android.permission.CAPTURE_VIDEO_OUTPUT"),
   tH("android.permission.CHANGE_COMPONENT_ENABLED_STATE"),
   Gm("android.permission.CHANGE_CONFIGURATION"),
   Br("android.permission.CHANGE_DEVICE_IDLE_TEMP_WHITELIST"),
   IE("android.permission.CHANGE_NETWORK_STATE", yt.pC),
   AU("android.permission.CHANGE_WIFI_MULTICAST_STATE", yt.pC),
   jS("android.permission.CHANGE_WIFI_STATE", yt.pC),
   KK("android.permission.CLEAR_APP_CACHE"),
   oB("android.permission.CLEAR_APP_USER_DATA"),
   Rq("android.permission.CONNECTIVITY_INTERNAL"),
   LL("android.permission.CONNECTIVITY_USE_RESTRICTED_NETWORKS"),
   rC("android.permission.CONTROL_INCALL_EXPERIENCE"),
   be("android.permission.CONTROL_LOCATION_UPDATES"),
   Xh("android.permission.CONTROL_VPN"),
   sz("android.permission.CRYPT_KEEPER"),
   QQ("android.permission.DELETE_CACHE_FILES"),
   eE("android.permission.DELETE_PACKAGES"),
   dM("android.permission.DEVICE_POWER"),
   EM("android.permission.DIAGNOSTIC"),
   fD("android.permission.DISABLE_KEYGUARD", yt.pC),
   ii("android.permission.DISPATCH_PROVISIONING_MESSAGE"),
   Gu("android.permission.DUMP"),
   hw("android.permission.EXPAND_STATUS_BAR", yt.pC),
   qG("android.permission.FACTORY_TEST"),
   yi("android.permission.FORCE_BACK"),
   zK("android.permission.FORCE_STOP_PACKAGES"),
   LA("android.permission.GET_ACCOUNTS", yt.A, KD.kS),
   ve("android.permission.GET_ACCOUNTS_PRIVILEGED"),
   yv("android.permission.GET_APP_OPS_STATS"),
   MZ("android.permission.GET_PACKAGE_SIZE", yt.pC),
   fH("android.permission.GET_PROCESS_STATE_AND_OOM_SCORE"),
   ET("android.permission.GET_TASKS"),
   kk("android.permission.GET_TOP_ACTIVITY_INFO"),
   Rh("android.permission.GLOBAL_SEARCH"),
   vv("android.permission.GRANT_RUNTIME_PERMISSIONS"),
   fn("android.permission.HARDWARE_TEST"),
   AS("android.permission.HDMI_CEC"),
   wF("android.permission.INJECT_EVENTS"),
   hF("android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS"),
   FA("android.permission.INSTALL_LOCATION_PROVIDER"),
   IK("android.permission.INSTALL_PACKAGES"),
   DM("com.android.launcher.permission.INSTALL_SHORTCUT", yt.pC),
   IQ("android.permission.INSTANT_APP_FOREGROUND_SERVICE"),
   zR("android.permission.INTENT_FILTER_VERIFICATION_AGENT"),
   Ft("android.permission.INTERACT_ACROSS_USERS"),
   kt("android.permission.INTERACT_ACROSS_USERS_FULL"),
   Yw("android.permission.INTERNAL_SYSTEM_WINDOW"),
   uD("android.permission.INTERNET", yt.pC),
   ZY("android.permission.INVOKE_CARRIER_SETUP"),
   mK("android.permission.KILL_BACKGROUND_PROCESSES", yt.pC),
   pW("android.permission.KILL_UID"),
   Gg("android.permission.LOCAL_MAC_ADDRESS"),
   kQ("android.permission.LOCATION_HARDWARE"),
   te("android.permission.LOOP_RADIO"),
   B("android.permission.MANAGE_ACTIVITY_STACKS"),
   RR("android.permission.MANAGE_APP_OPS_RESTRICTIONS"),
   CK("android.permission.MANAGE_APP_TOKENS"),
   Eq("android.permission.MANAGE_AUTO_FILL"),
   y("android.permission.MANAGE_CARRIER_OEM_UNLOCK_STATE"),
   JP("android.permission.MANAGE_CA_CERTIFICATES"),
   jY("android.permission.MANAGE_DEVICE_ADMINS"),
   ee("android.permission.MANAGE_DOCUMENTS"),
   ho("android.permission.MANAGE_OWN_CALLS"),
   VE("android.permission.MANAGE_USB"),
   lt("android.permission.MANAGE_USERS"),
   uw("android.permission.MANAGE_USER_OEM_UNLOCK_STATE"),
   QP("android.permission.MASTER_CLEAR"),
   hM("android.permission.MEDIA_CONTENT_CONTROL"),
   MJ("android.permission.MODIFY_APPWIDGET_BIND_PERMISSIONS"),
   OA("android.permission.MODIFY_AUDIO_ROUTING"),
   kT("android.permission.MODIFY_AUDIO_SETTINGS", yt.pC),
   x("android.permission.MODIFY_CELL_BROADCASTS"),
   un("android.permission.MODIFY_DAY_NIGHT_MODE"),
   JV("android.permission.MODIFY_NETWORK_ACCOUNTING"),
   Iq("android.permission.MODIFY_PARENTAL_CONTROLS"),
   mV("android.permission.MODIFY_PHONE_STATE"),
   Gh("android.permission.MOUNT_FORMAT_FILESYSTEMS"),
   HG("android.permission.MOUNT_UNMOUNT_FILESYSTEMS"),
   yC("android.permission.MOVE_PACKAGE"),
   uu("android.permission.NFC", yt.pC),
   Tq("android.permission.NOTIFICATION_DURING_SETUP"),
   HO("android.permission.NOTIFY_TV_INPUTS"),
   Is("android.permission.OVERRIDE_WIFI_CONFIG"),
   BP("android.permission.PACKAGE_USAGE_STATS"),
   Wm("android.permission.PACKAGE_VERIFICATION_AGENT"),
   TP("android.permission.PEERS_MAC_ADDRESS"),
   gd("android.permission.PERFORM_CDMA_PROVISIONING"),
   eI("android.permission.PERFORM_SIM_ACTIVATION"),
   lZ("android.permission.PERSISTENT_ACTIVITY"),
   AQ("android.permission.PROCESS_OUTGOING_CALLS", yt.A, KD.E),
   BX("android.permission.PROVIDE_RESOLVER_RANKER_SERVICE"),
   xg("android.permission.PROVIDE_TRUST_AGENT"),
   NN("android.permission.READ_CALENDAR", yt.A, KD.pC),
   np("android.permission.READ_CALL_LOG", yt.A, KD.E),
   ik("android.permission.READ_CONTACTS", yt.A, KD.kS),
   aK("android.permission.READ_DREAM_STATE"),
   gR("android.permission.READ_EXTERNAL_STORAGE", yt.A, KD.ld),
   Ig("android.permission.READ_FRAME_BUFFER"),
   TV("android.permission.READ_INPUT_STATE"),
   pY("android.permission.READ_INSTALL_SESSIONS"),
   l("android.permission.READ_LOGS"),
   Tr("android.permission.READ_NETWORK_USAGE_HISTORY"),
   Op("android.permission.READ_OEM_UNLOCK_STATE"),
   yB("android.permission.READ_PHONE_NUMBERS"),
   Mi("android.permission.READ_PHONE_STATE", yt.A, KD.E),
   TD("android.permission.READ_PRIVILEGED_PHONE_STATE"),
   mz("android.permission.READ_SEARCH_INDEXABLES"),
   UJ("android.permission.READ_SMS", yt.A, KD.ys),
   KW("android.permission.READ_SYNC_SETTINGS", yt.pC),
   NB("android.permission.READ_SYNC_STATS"),
   ND("com.android.voicemail.permission.READ_VOICEMAIL"),
   WX("android.permission.READ_WIFI_CREDENTIAL"),
   Ck("android.permission.REAL_GET_TASKS"),
   vU("android.permission.REBOOT"),
   KM("android.permission.RECEIVE_BOOT_COMPLETED", yt.pC),
   rI("android.permission.RECEIVE_DATA_ACTIVITY_CHANGE"),
   iX("android.permission.RECEIVE_EMERGENCY_BROADCAST"),
   XZ("android.permission.RECEIVE_MMS", yt.A, KD.ys),
   jj("android.permission.RECEIVE_SMS", yt.A, KD.ys),
   jH("android.permission.RECEIVE_WAP_PUSH", yt.A, KD.ys),
   uJ("android.permission.RECEIVE_WIFI_CREDENTIAL_CHANGE"),
   Fx("android.permission.RECORD_AUDIO", yt.A, KD.UT),
   hB("android.permission.RECOVERY"),
   gW("android.permission.REGISTER_CALL_PROVIDER"),
   pP("android.permission.REGISTER_CONNECTION_MANAGER"),
   sd("android.permission.REGISTER_SIM_SUBSCRIPTION"),
   OD("android.permission.REMOVE_DRM_CERTIFICATES"),
   hq("android.permission.REORDER_TASKS", yt.pC),
   sR("android.permission.REQUEST_COMPANION_RUN_IN_BACKGROUND"),
   ib("android.permission.REQUEST_COMPANION_USE_DATA_IN_BACKGROUND"),
   zJ("android.permission.REQUEST_DELETE_PACKAGES"),
   aU("android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS", yt.pC),
   dC("android.permission.REQUEST_INSTALL_PACKAGES", yt.pC),
   fN("android.permission.RESTART_PACKAGES"),
   dW("android.permission.RESTRICTED_VR_ACCESS"),
   dE("android.permission.RETRIEVE_WINDOW_CONTENT"),
   xy("android.permission.REVOKE_RUNTIME_PERMISSIONS"),
   tR("android.permission.SCORE_NETWORKS"),
   lO("android.permission.SEND_EMBMS_INTENTS"),
   ll("android.permission.SEND_RESPOND_VIA_MESSAGE"),
   KC("android.permission.SEND_SMS", yt.A, KD.ys),
   cH("android.permission.SEND_SMS_NO_CONFIRMATION"),
   bm("android.permission.SERIAL_PORT"),
   hE("android.permission.SET_ACTIVITY_WATCHER"),
   vr("com.android.alarm.permission.SET_ALARM", yt.pC),
   LV("android.permission.SET_ALWAYS_FINISH"),
   Yi("android.permission.SET_ANIMATION_SCALE"),
   dF("android.permission.SET_DEBUG_APP"),
   Jq("android.permission.SET_MEDIA_KEY_LISTENER"),
   Fz("android.permission.SET_ORIENTATION"),
   mr("android.permission.SET_POINTER_SPEED"),
   ct("android.permission.SET_PREFERRED_APPLICATIONS"),
   wj("android.permission.SET_PROCESS_LIMIT"),
   kB("android.permission.SET_SCREEN_COMPATIBILITY"),
   rB("android.permission.SET_TIME"),
   zL("android.permission.SET_TIME_ZONE", yt.pC),
   oc("android.permission.SET_VOLUME_KEY_LONG_PRESS_LISTENER"),
   mE("android.permission.SET_WALLPAPER", yt.pC),
   GM("android.permission.SET_WALLPAPER_COMPONENT"),
   TS("android.permission.SET_WALLPAPER_HINTS", yt.pC),
   LQ("android.permission.SHUTDOWN"),
   dv("android.permission.SIGNAL_PERSISTENT_PROCESSES"),
   of("android.permission.STATUS_BAR"),
   iG("android.permission.STOP_APP_SWITCHES"),
   Pr("android.permission.SUBSTITUTE_NOTIFICATION_APP_NAME"),
   ti("android.permission.SYSTEM_ALERT_WINDOW"),
   nd("android.permission.TETHER_PRIVILEGED"),
   RS("android.permission.TRANSMIT_IR", yt.pC),
   Nw("android.permission.TV_INPUT_HARDWARE"),
   Tl("android.permission.TV_VIRTUAL_REMOTE_CONTROLLER"),
   Jl("com.android.launcher.permission.UNINSTALL_SHORTCUT", yt.pC),
   gS("android.permission.UPDATE_APP_OPS_STATS"),
   aX("android.permission.UPDATE_DEVICE_STATS"),
   Jy("android.permission.UPDATE_LOCK"),
   mx("android.permission.USER_ACTIVITY"),
   Vw("android.permission.USE_FINGERPRINT", yt.pC),
   bK("android.permission.USE_SIP", yt.A, KD.E),
   VT("android.permission.VIBRATE", yt.pC),
   Gn("android.permission.WAKE_LOCK", yt.pC),
   Do("android.permission.WRITE_APN_SETTINGS"),
   QA("android.permission.WRITE_CALENDAR", yt.A, KD.pC),
   HZ("android.permission.WRITE_CALL_LOG", yt.A, KD.E),
   wa("android.permission.WRITE_CONTACTS", yt.A, KD.kS),
   Tb("android.permission.WRITE_DREAM_STATE"),
   Uf("android.permission.WRITE_EXTERNAL_STORAGE", yt.A, KD.ld),
   sZ("android.permission.WRITE_GSERVICES"),
   dH("android.permission.WRITE_MEDIA_STORAGE"),
   yS("android.permission.WRITE_SECURE_SETTINGS"),
   UB("android.permission.WRITE_SETTINGS"),
   cq("android.permission.WRITE_SYNC_SETTINGS", yt.pC),
   Ol("com.android.voicemail.permission.WRITE_VOICEMAIL");

   private final String nx;
   private final yt NG;
   private final KD Sx;

   private zp(String var3) {
      this(var3, null, null);
   }

   private zp(String var3, yt var4) {
      this(var3, var4, null);
   }

   private zp(String var3, yt var4, KD var5) {
      if (var4 != yt.A && var5 != null) {
         throw new RuntimeException("Only dangerous permissions have a permission group! " + var3);
      } else if (var4 == yt.A && var5 == null) {
         throw new RuntimeException("A dangerous permission must have a permission group! " + var3);
      } else {
         this.nx = var3;
         this.NG = var4;
         this.Sx = var5;
      }
   }

   public String pC() {
      return this.nx;
   }

   public yt A() {
      return this.NG;
   }

   public KD kS() {
      return this.Sx;
   }
}
