package com.pnfsoftware.jebglobal;

import com.pnfsoftware.jeb.core.units.code.asm.analyzer.IMethodStackMemoryModel;
import com.pnfsoftware.jeb.core.units.code.asm.cfg.BasicBlock;
import com.pnfsoftware.jeb.core.units.code.asm.cfg.CFG;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.IERoutineContext;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEGeneric;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEMem;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEStackManager;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEStatement;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEVar;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IWildcardType;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IWildcardTypeManager;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.OperationType;
import com.pnfsoftware.jeb.core.units.code.asm.items.INativeContinuousItem;
import com.pnfsoftware.jeb.core.units.code.asm.items.INativeDataItem;
import com.pnfsoftware.jeb.core.units.code.asm.type.INativeType;
import com.pnfsoftware.jeb.core.units.code.asm.type.IPrimitiveType;
import com.pnfsoftware.jeb.core.units.code.asm.type.ITypeManager;
import com.pnfsoftware.jeb.core.units.code.asm.type.TypeUtil;
import com.pnfsoftware.jeb.util.base.Assert;
import com.pnfsoftware.jeb.util.base.Couple;
import com.pnfsoftware.jeb.util.logging.StructuredLogger;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

public class anc {
   private static final StructuredLogger ys = aco.pC(anc.class);
   IERoutineContext pC;
   CFG A;
   ITypeManager kS;
   IWildcardTypeManager wS;
   IEStackManager UT;
   IMethodStackMemoryModel E;
   amg sY;

   public anc(IERoutineContext var1) {
      this.pC = var1;
      this.A = var1.getCfg();
      this.wS = var1.getWildcardTypeManager();
      this.kS = this.wS.getNativeTypeManager();
      this.UT = var1.getStackManager();
      this.E = var1.getRoutine().getData().getStackframeModel();
   }

   public amg pC(IEVar var1) {
      if (this.sY != null) {
         throw new IllegalStateException();
      } else {
         this.sY = new amg(this.pC);
         this.pC(var1, true);
         return this.sY;
      }
   }

   public int A(IEVar var1) {
      if (this.sY == null) {
         throw new IllegalStateException();
      } else {
         return this.pC(var1, false);
      }
   }

   private int pC(IEVar var1, boolean var2) {
      AtomicInteger var3 = new AtomicInteger(0);

      for (BasicBlock var5 : this.A) {
         for (IEStatement var7 : var5) {
            var7.visitDepthPost(new and(this, var7, var1, var2, var3));
         }
      }

      for (BasicBlock var10 : this.A) {
         for (IEStatement var12 : var10) {
            var12.visitDepthPre(new ane(this, var1, var2, var3));
         }
      }

      if (var2) {
         if (acp.pC) {
            Object[] var10000 = new Object[]{this.sY.kS()};
         }

         List var9 = this.sY.A();
         if (!var9.isEmpty()) {
            this.A.invalidateDataFlowAnalysis();
         }
      } else if (var3.get() > 0) {
         this.A.invalidateDataFlowAnalysis();
      }

      return var3.get();
   }

   private IEGeneric pC(IEGeneric var1, IEGeneric var2, IEVar var3, boolean var4, Boolean var5) {
      alj var6 = new alj(var1, var3);
      if (var6.pC()) {
         int var7 = var2 instanceof IEMem ? var2.getBitsize() : 0;
         if (var4) {
            this.sY.pC(var6.E(), var7, var5);
         } else {
            IEGeneric var8 = this.pC(var6, var7);
            if (var8 != null) {
               boolean var9 = var2.replaceSubExpression(var1, var8);
               Assert.a(var9);
               return var8;
            }
         }
      }

      return null;
   }

   private IEGeneric pC(alj var1, int var2) {
      long var5 = var1.E();
      INativeContinuousItem var7 = this.E.getItemOver(var5);
      long var3;
      if (var7 == null) {
         var3 = var5;
         var5 = 0L;
      } else {
         var3 = var7.getMemoryAddress();
         var5 -= var3;
      }

      IEVar var8 = this.pC.getStackReference(var3);
      if (var8 == null) {
         IWildcardType var9 = null;
         if (var7 != null) {
            INativeType var10 = ((INativeDataItem)var7).getType();
            if (var7.isAutoGenerated() && TypeUtil.getNonAlias(var10) instanceof IPrimitiveType) {
               var9 = this.wS.createPointer(var10.getSize() * 8);
            } else {
               var9 = this.wS.create(this.kS.createReference(var10));
               this.pC.acquireNativeItem(var9);
            }
         }

         var8 = this.pC.createStackReference(var3, var9);
      }

      var1.pC(var8, var5);
      return var1.pC(this.pC);
   }

   public int pC() {
      AtomicInteger var1 = new AtomicInteger(0);

      for (BasicBlock var3 : this.A) {
         for (IEStatement var5 : var3) {
            var5.visitDepthPost(new anf(this, var1));
         }
      }

      if (var1.get() > 0) {
         this.A.invalidateDataFlowAnalysis();
      }

      return var1.get();
   }

   private static Couple pC(IEGeneric var0) {
      if (A(var0)) {
         return new Couple(var0.asVar(), 0L);
      } else {
         if (var0.isOperation(OperationType.ADD)) {
            IEGeneric var1 = var0.asOperation().getOperand1();
            IEGeneric var2 = var0.asOperation().getOperand2();
            if (A(var1) && var2.isImm()) {
               return new Couple(var1.asVar(), var2.asImm().getValueAsLong());
            }
         }

         return null;
      }
   }

   private static boolean A(IEGeneric var0) {
      return var0.isVar() && var0.asVar().isStackReference();
   }
}
