package com.pnfsoftware.jebglobal;

import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEPrototypeHandler;
import com.pnfsoftware.jeb.util.base.Assert;
import com.pnfsoftware.jeb.util.logging.StructuredLogger;

public class aua extends atf {
   private static final StructuredLogger WR = aco.pC(aua.class);

   public aua() {
      super(atg.xC);
   }

   @Override
   protected boolean kS() {
      if (this.ld.getPrototype() != null && !this.ld.isAutoGeneratedPrototype()) {
         Object[] var10000 = new Object[0];
         IEPrototypeHandler var3 = this.UT.getPrototypeHandler(this.ys);
         var3.applyKnownPrototype(false);
         ani var4 = new ani(this.ys);
         var4.kS();
      } else {
         Assert.a(this.ys.getPrototype() != null, "Routine should have at least a wildcard prototype at this stage");
         IEPrototypeHandler var1 = this.UT.getPrototypeHandler(this.ys);
         boolean var2 = var1.refinePrototype();
         WR.iH("Wildcard prototype (refined: %b): %s", var2, this.ys.getPrototype());
      }

      return true;
   }
}
