package com.pnfsoftware.jebglobal;

import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEPrototypeHandler;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEStackManager;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IEStatement;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ir.IWildcardTypeManager;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.opt.OptimizerMode;
import com.pnfsoftware.jeb.core.units.code.asm.type.IPrototypeItem;
import com.pnfsoftware.jeb.util.logging.StructuredLogger;

public class aue extends atf {
   private static final StructuredLogger WR = aco.pC(aue.class);

   public aue() {
      super(atg.eP);
   }

   @Override
   protected boolean kS() {
      this.pC(WR);
      alx var1 = new alx(this.ys);
      if (!var1.process(true, true, true)) {
         WR.error("The CFG could not be normalized!");
      } else {
         Object[] var10000 = new Object[0];
         WR.iH("NOTE: ECalls are no longer breaking!");
      }

      this.pC(OptimizerMode.UNFRIENDLY, WR, "Final optimizations on the normalized CFG");
      IWildcardTypeManager var2 = this.ys.getWildcardTypeManager();
      IEStackManager var3 = this.ys.getStackManager();

      for (IEStatement var5 : this.ys.getCfg().instructions()) {
         var5.visitDepthPost(new auf(this, var3, var2));
      }

      ani var9 = new ani(this.ys);
      Object[] var16 = new Object[0];
      int var10 = var9.A();
      var16 = new Object[]{var10};
      var9.pC();
      var9.kS();
      var9.wS();

      for (IEStatement var7 : this.ys.getCfg().instructions()) {
         var7.visitDepthPost(new aug(this, var2));
      }

      for (IEStatement var14 : this.ys.getCfg().instructions()) {
         var14.visitDepthPost(new auh(this));
      }

      this.ys.invalidateDataFlowAnalysis();
      var16 = new Object[0];
      var10 = new alq(this.ys).pC();
      var16 = new Object[]{var10};
      if (this.ld.getPrototype() == null || this.ld.isAutoGeneratedPrototype()) {
         IEPrototypeHandler var13 = this.UT.getPrototypeHandler(this.ys);
         var13.refinePrototype();
         boolean var15 = true;
         if (var15) {
            var16 = new Object[]{var10, this.ys.getPrototype()};
            IPrototypeItem var8 = this.ys.getPrototype().resolve();
            this.ld.setPrototype(var8);
            var16 = new Object[]{this.ld.getPrototype()};
         }
      }

      var16 = new Object[]{this.ld.getPrototype()};
      var16 = new Object[0];
      this.ys.invalidateDataFlowAnalysis();
      return true;
   }
}
