package com.pnfsoftware.jebglobal;

import com.pnfsoftware.jeb.util.base.Assert;
import com.pnfsoftware.jeb.util.format.Formatter;
import com.pnfsoftware.jeb.util.format.Strings;
import com.pnfsoftware.jeb.util.io.ByteArray;
import com.pnfsoftware.jeb.util.logging.GlobalLog;
import com.pnfsoftware.jeb.util.logging.ILogger;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;

public class bar implements bbb {
   private static final ILogger kS = GlobalLog.getLogger();
   public bbd pC;
   public bbd A;
   private List wS;
   private transient boolean UT;
   private Map E = new HashMap();
   private static final Map sY = new HashMap();

   public static boolean pC(byte[] var0, int var1) {
      ByteArray var2 = new ByteArray(var0, var1);
      if (var2.available() < 52) {
         return false;
      } else {
         int var3 = var2.i32();
         if (var3 != -589498891) {
            return false;
         } else {
            long var4 = var2.i64();
            if (var4 > 0L && var4 <= 2147483647L) {
               long var6 = var2.i64();
               String var8 = Strings.decodeASCII(var2.get(32)).toLowerCase();
               bar.Av var9 = (bar.Av)sY.get(var8);
               return var9 == null ? false : var6 == var9.pC();
            } else {
               return false;
            }
         }
      }
   }

   public bar(byte[] var1, int var2, int var3, int var4, int var5) throws IOException {
      this.pC(var1, var2, var3, var4, var5);
   }

   private String A(byte[] var1, int var2) {
      ByteArray var3 = new ByteArray(var1, var2);
      Assert.a(var3.available() >= 52);
      int var4 = var3.i32();
      Assert.a(var4 == -589498891);
      long var5 = var3.i64();
      Assert.a(var5 <= 2147483647L);
      long var7 = var3.i64();
      String var9 = Strings.decodeASCII(var3.get(32)).toLowerCase();
      bar.Av var10 = (bar.Av)sY.get(var9);
      if (var10 == null) {
         throw new RuntimeException("Dart snapshot hash is unknown: snapshot_hash=" + var9);
      } else if (var7 != var10.pC()) {
         throw new RuntimeException("Not an AOT snapshot: snapshot_kind=" + var7);
      } else {
         return var10.pC;
      }
   }

   private void pC(byte[] var1, int var2, int var3, int var4, int var5) {
      String var6 = this.A(var1, var2);
      String var7 = this.A(var1, var4);
      if (var6 != null && var6.equals(var7)) {
         kS.debug("Preparing to parse dart snapshot generated by dart version %s", var6);
         if (var6.startsWith("2.10.")) {
            bbh var8 = new bbh(var1, var2, var1, var3, null);
            this.pC = var8;
            this.A = new bbh(var1, var4, var1, var5, var8);
         } else if (var6.startsWith("2.12.")) {
            bbl var9 = new bbl(var1, var2, var1, var3, null);
            this.pC = var9;
            this.A = new bbl(var1, var4, var1, var5, var9);
         } else if (var6.startsWith("2.13.")) {
            bbp var10 = new bbp(var1, var2, var1, var3, null);
            this.pC = var10;
            this.A = new bbp(var1, var4, var1, var5, var10);
         } else if (var6.startsWith("2.14.")) {
            bbt var11 = new bbt(var1, var2, var1, var3, null);
            this.pC = var11;
            this.A = new bbt(var1, var4, var1, var5, var11);
         } else if (var6.startsWith("2.15.")) {
            bbx var12 = new bbx(var1, var2, var1, var3, null);
            this.pC = var12;
            this.A = new bbx(var1, var4, var1, var5, var12);
         } else if (var6.startsWith("2.16.")) {
            bcb var13 = new bcb(var1, var2, var1, var3, null);
            this.pC = var13;
            this.A = new bcb(var1, var4, var1, var5, var13);
         } else if (var6.startsWith("2.17.")) {
            bcf var14 = new bcf(var1, var2, var1, var3, null);
            this.pC = var14;
            this.A = new bcf(var1, var4, var1, var5, var14);
         } else if (var6.startsWith("2.18.")) {
            bcj var15 = new bcj(var1, var2, var1, var3, null);
            this.pC = var15;
            this.A = new bcj(var1, var4, var1, var5, var15);
         } else if (var6.startsWith("2.19.")) {
            bcn var16 = new bcn(var1, var2, var1, var3, null);
            this.pC = var16;
            this.A = new bcn(var1, var4, var1, var5, var16);
         } else if (var6.startsWith("3.0.")) {
            bcr var17 = new bcr(var1, var2, var1, var3, null);
            this.pC = var17;
            this.A = new bcr(var1, var4, var1, var5, var17);
         } else if (var6.startsWith("3.1.")) {
            bcv var18 = new bcv(var1, var2, var1, var3, null);
            this.pC = var18;
            this.A = new bcv(var1, var4, var1, var5, var18);
         } else if (var6.startsWith("3.2.")) {
            bcz var19 = new bcz(var1, var2, var1, var3, null);
            this.pC = var19;
            this.A = new bcz(var1, var4, var1, var5, var19);
         } else if (var6.startsWith("3.3.")) {
            bdd var20 = new bdd(var1, var2, var1, var3, null);
            this.pC = var20;
            this.A = new bdd(var1, var4, var1, var5, var20);
         } else if (var6.startsWith("3.4.")) {
            bdh var21 = new bdh(var1, var2, var1, var3, null);
            this.pC = var21;
            this.A = new bdh(var1, var4, var1, var5, var21);
         } else if (var6.startsWith("3.5.")) {
            bdl var22 = new bdl(var1, var2, var1, var3, null);
            this.pC = var22;
            this.A = new bdl(var1, var4, var1, var5, var22);
         } else if (var6.startsWith("3.6.")) {
            bdp var23 = new bdp(var1, var2, var1, var3, null);
            this.pC = var23;
            this.A = new bdp(var1, var4, var1, var5, var23);
         } else if (var6.startsWith("3.7.")) {
            bdt var24 = new bdt(var1, var2, var1, var3, null);
            this.pC = var24;
            this.A = new bdt(var1, var4, var1, var5, var24);
         } else {
            if (!var6.startsWith("3.8.")) {
               throw new RuntimeException("Dart AOT snapshot is unsupported: compiled with dart " + var6);
            }

            bdx var25 = new bdx(var1, var2, var1, var3, null);
            this.pC = var25;
            this.A = new bdx(var1, var4, var1, var5, var25);
         }

         this.pC.A = var6;
         this.A.A = var7;
         this.UT();
      } else {
         throw new RuntimeException(
            Strings.ff("The VM and isolate snapshots appear to have been generated by two different versions of Dart (%s, %s)", var6, var7)
         );
      }
   }

   public List pC() {
      return Collections.unmodifiableList(this.A.LM);
   }

   private List wS() {
      ArrayList var1 = new ArrayList();
      int var2 = 0;

      for (bbc var4 : this.pC()) {
         if (var4.pC().equals("kObjectPoolCid") && var4.A("data")) {
            if (var2 > 0) {
               throw new RuntimeException("Multiple pools, not handled");
            }

            var1.add(null);

            for (Object var7 : (List)var4.pC("data", List.class)) {
               Map var8 = (Map)var7;
               Object var9 = var8.get("rawObj");
               if (var9 instanceof Long) {
                  bay var10 = (bay)this.E.get(((Long)var9).intValue());
                  var1.add(var10);
               } else {
                  var9 = var8.get("rawValue");
                  if (var9 instanceof Long) {
                     var1.add(var9);
                  } else {
                     var1.add(null);
                  }
               }
            }

            var2++;
         }
      }

      return var1;
   }

   public List A() {
      if (this.wS == null) {
         synchronized (this) {
            if (this.wS == null) {
               this.wS = this.wS();
            }
         }
      }

      return Collections.unmodifiableList(this.wS);
   }

   @Override
   public Object pC(bbc var1, String var2, Class var3) {
      if (!var1.A(var2)) {
         return null;
      } else {
         int var4 = ((Long)var1.pC(var2, Long.class)).intValue();
         return this.E.get(var4);
      }
   }

   @Override
   public void pC(bbc var1, String var2, Class var3, Collection var4) {
      bbc var5 = var1.wS(var2);
      if (var5 != null) {
         for (Object var9 : (Object[])var5.kS("data")) {
            int var10 = ((Number)var9).intValue();
            Object var11 = this.E.get(var10);
            var4.add(var11);
         }
      }
   }

   private void UT() {
      if (!this.UT) {
         synchronized (this) {
            if (!this.UT) {
               int var2 = 0;

               for (bbc var4 : this.A.LM) {
                  String var5 = var4.pC();
                  if (var5 == null) {
                     throw new RuntimeException();
                  }

                  if (var5.equals("kTypeCid")) {
                     this.E.put(var2, new bba(var4));
                  } else if (var5.equals("kClassCid")) {
                     this.E.put(var2, new bav(var4));
                  } else if (var5.equals("kFunctionCid")) {
                     this.E.put(var2, new baw(var4));
                  } else if (var5.equals("kLibraryCid")) {
                     this.E.put(var2, new bax(var4));
                  } else if (var5.endsWith("StringCid")) {
                     this.E.put(var2, new baz(var4));
                  }

                  var2++;
               }

               for (bay var9 : this.E.values()) {
                  var9.pC(this);
               }

               this.UT = true;
            }
         }
      }
   }

   public Collection kS() {
      return Collections.unmodifiableCollection(this.E.values());
   }

   @Override
   public String toString() {
      return this.pC(true, true, true, true);
   }

   public String pC(boolean var1, boolean var2, boolean var3, boolean var4) {
      StringBuilder var5 = new StringBuilder();
      if (var1) {
         Strings.ff(var5, "SNAPSHOTS:\n");
         Strings.ff(var5, "=> VM: %s\n", this.pC.UO());
         Strings.ff(var5, "=> ISOLATE: %s\n", this.A.UO());
         Strings.ff(var5, "\n");
      }

      if (var2) {
         Strings.ff(var5, "ALL REFERENCES:\n");
         int var6 = 0;

         for (bbc var8 : this.pC()) {
            Strings.ff(var5, "%d -> %s\n", var6, var8);
            var6++;
         }

         Strings.ff(var5, "\n");
      }

      if (var3) {
         Strings.ff(var5, "POOL: (displaying strings only)\n");
         int var10 = 0;

         for (Object var16 : this.A()) {
            Strings.ff(var5, "%d: ", var10);
            if (var16 instanceof bay) {
               if (var16 instanceof baz) {
                  Strings.ff(var5, "\"%s\"", Formatter.escapeString(((baz)var16).pC));
               } else {
                  Strings.ff(var5, "?");
               }
            } else if (var16 instanceof Long) {
               Strings.ff(var5, "%d", (Long)var16);
            } else {
               Strings.ff(var5, "?");
            }

            var5.append('\n');
            var10++;
         }

         Strings.ff(var5, "\n");
      }

      if (var4) {
         Strings.ff(var5, "CLASSES, METHODS: (addresses displayed are relative virtual offsets)\n");
         HashSet var14 = new HashSet();
         int var11 = 0;

         for (bay var9 : this.E.values()) {
            if (var9 instanceof bav) {
               var14.addAll(((bav)var9).wS);
               Strings.ff(var5, "Class %d: %s\n", var11, var9);
               var11++;
            }
         }

         Strings.ff(var5, "\n");
         Strings.ff(var5, "OTHER METHODS: (addresses displayed are relative virtual offsets)\n");

         for (bay var20 : this.E.values()) {
            if (var20 instanceof baw && !var14.contains(var20)) {
               Strings.ff(var5, "  %s\n", var20);
            }
         }

         Strings.ff(var5, "\n");
      }

      if (var4) {
         Strings.ff(var5, "LIBRARIES:\n");
         int var12 = 0;

         for (bay var19 : this.E.values()) {
            if (var19 instanceof bax) {
               Strings.ff(var5, "Library #%d: %s\n", var12, var19);
               var12++;
            }
         }

         Strings.ff(var5, "\n");
      }

      return var5.toString();
   }

   static {
      sY.put("47fb0d1441c967a6cafe72dd7edf7a84", new bar.Av("3.9.0-216.0.dev"));
      sY.put("eb54a7c7f754416b5a9b414ab315a319", new bar.Av("3.9.0-212.0.dev"));
      sY.put("b707ef5ee5a4b323f7d764841454c442", new bar.Av("3.9.0-205.0.dev"));
      sY.put("478acceee22b35bdc3f900f25fbf034e", new bar.Av("3.9.0-202.0.dev"));
      sY.put("42f987b8c14084aea0ee61f362c10682", new bar.Av("3.9.0-194.0.dev"));
      sY.put("2c60b7ea5b8f6754e89f8df42e41462c", new bar.Av("3.9.0-172.0.dev"));
      sY.put("d202022dc13ed9847fe68f8e068e7e1c", new bar.Av("3.9.0-171.0.dev"));
      sY.put("fa4a47b2163898936cdd848f7d329e57", new bar.Av("3.9.0-153.0.dev"));
      sY.put("464d3e01f36dbabba946d8a43d40a3ec", new bar.Av("3.9.0-145.0.dev"));
      sY.put("38198bbcda4f59ec5af394a2e78a6e72", new bar.Av("3.9.0-121.0.dev"));
      sY.put("b3e43f5515d5dccf94e318501ab449d2", new bar.Av("3.9.0-100.2.beta"));
      sY.put("14dc06d8088afb62faafb0a28ea73488", new bar.Av("3.9.0-99.0.dev"));
      sY.put("04a1afa9a1e526c177c7db610c7cb5c1", new bar.Av("3.9.0-98.0.dev"));
      sY.put("ced5f0b7bb4678480552685e5fee1e22", new bar.Av("3.9.0-82.0.dev"));
      sY.put("56c5c1751292b210b9f9c6406683f23c", new bar.Av("3.9.0-73.0.dev"));
      sY.put("dd006301e7c9ce689d2dad4daac649ca", new bar.Av("3.9.0-57.0.dev"));
      sY.put("71aaf97a30d32adebfec83faf9159f31", new bar.Av("3.9.0-48.0.dev"));
      sY.put("242e22fb708e69e463f66d6d9a72478b", new bar.Av("3.9.0-46.0.dev"));
      sY.put("682cf5f7bee8be2e7b172adb9f8c7ef7", new bar.Av("3.9.0-43.0.dev"));
      sY.put("830f4f59e7969c70b595182826435c19", new bar.Av("3.9.0-26.0.dev"));
      sY.put("23d3f13db16f63a2bdfdd5a7b1a0cf4a", new bar.Av("3.9.0-21.0.dev"));
      sY.put("ff5598b8d9a6167e7184aec3f8183d7c", new bar.Av("3.8.0-258.0.dev"));
      sY.put("c82409e14a8789fb9e45c981631ef21e", new bar.Av("3.8.0-246.0.dev"));
      sY.put("19f7051f265f72e40e23596b85a2d5c5", new bar.Av("3.8.0-213.0.dev"));
      sY.put("ce093465f445124f66e64a7da552c5d4", new bar.Av("3.8.0-205.0.dev"));
      sY.put("6f441b68139013de31bc0b585133e1b1", new bar.Av("3.8.0-204.0.dev"));
      sY.put("dcb9e9a35a7b784f00293872604ff9b2", new bar.Av("3.8.0-183.0.dev"));
      sY.put("3a2ef32389087437ce26ed8546143b8b", new bar.Av("3.8.0-182.0.dev"));
      sY.put("3489d40ff2aa26cca4dc64b56756c1cd", new bar.Av("3.8.0-155.0.dev"));
      sY.put("e030f84c5f6fd7de1526d840c6f7c9b9", new bar.Av("3.8.0-152.0.dev"));
      sY.put("0674df23a202fd2480cc1735feb772d3", new bar.Av("3.8.0-117.0.dev"));
      sY.put("40b6311b11bd1ddc15557a67196dbbde", new bar.Av("3.8.0-94.0.dev"));
      sY.put("459a2e81dd8c7ca89b94ebd999fa06de", new bar.Av("3.8.0-92.0.dev"));
      sY.put("daa49b53912c9b703c87a94c48352c6c", new bar.Av("3.8.0-86.0.dev"));
      sY.put("ce2796968ab5325d09258a1bdb7c12bf", new bar.Av("3.8.0-84.0.dev"));
      sY.put("7e8e21996fdb20b1e7adf7e9bfd4c30c", new bar.Av("3.8.0-71.0.dev"));
      sY.put("0a841ba78a1c491593464ebbc79a6bbb", new bar.Av("3.8.0-70.1.beta"));
      sY.put("29dc7c7e993e4cc1714bf21dad221dfa", new bar.Av("3.8.0-69.0.dev"));
      sY.put("6156466bd53f61a5cd21a10410b6a205", new bar.Av("3.8.0-41.0.dev"));
      sY.put("fc5746fec3b6a311531a329619293370", new bar.Av("3.8.0-33.0.dev"));
      sY.put("d91c0e6f35f0eb2e44124e8f42aa44a7", new bar.Av("3.7.3"));
      sY.put("55ce55057361645828ccf8ca83b14e8f", new bar.Av("3.7.0-272.0.dev"));
      sY.put("d8a3cf0d095957b3391ebb5bae489749", new bar.Av("3.7.0-267.0.dev"));
      sY.put("d7bad166cd49a5e93ff8bd1ad111074e", new bar.Av("3.7.0-249.0.dev"));
      sY.put("1792be370d00fa4e8bbc092c8cf121e5", new bar.Av("3.7.0-239.0.dev"));
      sY.put("7b0bba5d2d938a3b2d630860d1d96ac9", new bar.Av("3.7.0-228.0.dev"));
      sY.put("01c2ce8f3c1e9d31f4f209b5467c8ac6", new bar.Av("3.7.0-227.0.dev"));
      sY.put("7dc6dbaf0161c6e0611e808e9993791d", new bar.Av("3.7.0-226.0.dev"));
      sY.put("97f52ee782b130538ba1dca8de3ad8b2", new bar.Av("3.7.0-209.1.beta"));
      sY.put("ddcbb32cd5a0c7787989073aed79bbb1", new bar.Av("3.7.0-206.0.dev"));
      sY.put("8457b536e47de5bb18ea9bdf5c353f62", new bar.Av("3.7.0-183.0.dev"));
      sY.put("b2d5fa73b70d59497889f5ac48d5d7f8", new bar.Av("3.7.0-152.0.dev"));
      sY.put("57986b030ce602573c00668c26f6be00", new bar.Av("3.7.0-137.0.dev"));
      sY.put("b288a09543426b0f799fd1ceb945c946", new bar.Av("3.7.0-84.0.dev"));
      sY.put("728b7ba9de4c5dd8e9ebe17bc5afc593", new bar.Av("3.7.0-75.0.dev"));
      sY.put("646d063e28a1dc68fe4c6efcceea0176", new bar.Av("3.7.0-53.0.dev"));
      sY.put("e17c6be098a254e3f16b8cfe543e3134", new bar.Av("3.7.0-32.0.dev"));
      sY.put("f956f595844a2f845a55707faaaa51e4", new bar.Av("3.6.2"));
      sY.put("e04affe75599aecbb5a905de8811490e", new bar.Av("3.6.0-313.0.dev"));
      sY.put("4bbc4c3bf1002ed9fedf884c2fed2d6d", new bar.Av("3.6.0-309.0.dev"));
      sY.put("c7f0154018e3898ca35da30075d05665", new bar.Av("3.6.0-280.0.dev"));
      sY.put("ab7a7c160e18910372c7254c95c39e75", new bar.Av("3.6.0-279.0.dev"));
      sY.put("4766942b46268a0b16fa13cb2d7a924f", new bar.Av("3.6.0-270.0.dev"));
      sY.put("85820842589d8be45067fdee3ea68c43", new bar.Av("3.6.0-265.0.dev"));
      sY.put("da72b7ef499f51724e085c8d9e5e07c9", new bar.Av("3.6.0-247.0.dev"));
      sY.put("6d8a66705452c2ea4f68889d98e2de45", new bar.Av("3.6.0-240.0.dev"));
      sY.put("436e6aba3d24b32f27f635a00f815dbc", new bar.Av("3.6.0-229.0.dev"));
      sY.put("8d97f46f9e092e886d13bfafe3fc7004", new bar.Av("3.6.0-216.1.beta"));
      sY.put("95d4183c65d34f183c54829a3fbc7a53", new bar.Av("3.6.0-197.0.dev"));
      sY.put("ecb002b9601f714c9bc4a3ff4d57931e", new bar.Av("3.6.0-190.0.dev"));
      sY.put("2e486b19113050440fd17f370605ba91", new bar.Av("3.6.0-187.0.dev"));
      sY.put("de2a01120b6ec4f4ae0f91e84e815605", new bar.Av("3.6.0-182.0.dev"));
      sY.put("46ac6a0cc03d1ccd7069d76f9244e509", new bar.Av("3.6.0-158.0.dev"));
      sY.put("6234228703466fb244a5f8c7a64a9293", new bar.Av("3.6.0-156.0.dev"));
      sY.put("13fc296ae53a2c88d454ab149588c7bb", new bar.Av("3.6.0-149.3.beta"));
      sY.put("f5e98da4c90896c13ff2a06ef854d6a7", new bar.Av("3.6.0-145.0.dev"));
      sY.put("e778b1230a9836052e2161a8a766cccc", new bar.Av("3.6.0-95.0.dev"));
      sY.put("4d4a4fa154123267f680910cee18ff9e", new bar.Av("3.6.0-48.0.dev"));
      sY.put("1c85b31010eecbdce4b6f54634609e60", new bar.Av("3.6.0-26.0.dev"));
      sY.put("83445cfa9bd799eea551951aeed46e1e", new bar.Av("3.6.0-20.0.dev"));
      sY.put("8e5eed65cd308f8b0028e3ae1a789ad0", new bar.Av("3.6.0-16.0.dev"));
      sY.put("b2878aa668979b06ad4bf19bf0310992", new bar.Av("3.6.0-5.0.dev"));
      sY.put("80a49c7111088100a233b2ae788e1f48", new bar.Av("3.5.4"));
      sY.put("9546c86d97808b1997871b2cc2c29f8c", new bar.Av("3.5.0-310.0.dev"));
      sY.put("8c5c2a4e47513d7e931dea670496287f", new bar.Av("3.5.0-305.0.dev"));
      sY.put("dcff67ebd4d9e1b2be8e1043a87ecab4", new bar.Av("3.5.0-295.0.dev"));
      sY.put("804cbc034bbc1be3b1027629d0dff9a5", new bar.Av("3.5.0-285.0.dev"));
      sY.put("b21e1bbef7e64ee4825c5cf94f48b68d", new bar.Av("3.5.0-284.0.dev"));
      sY.put("c3b9920be707872f1a43e0d5c8048a00", new bar.Av("3.5.0-275.0.dev"));
      sY.put("213bc7714bba6014c1c2c56f11184444", new bar.Av("3.5.0-274.0.dev"));
      sY.put("af79a056a192b5b68ef306bf5f7d5f75", new bar.Av("3.5.0-267.0.dev"));
      sY.put("7b83d7b664c4609565b45bae67f1a4ec", new bar.Av("3.5.0-256.0.dev"));
      sY.put("bda25f73781326cc7b02b5bbde2bf10e", new bar.Av("3.5.0-255.0.dev"));
      sY.put("853774151675607809640123f1ab2cab", new bar.Av("3.5.0-245.0.dev"));
      sY.put("896c732206e0ae517cb905eef8077879", new bar.Av("3.5.0-230.0.dev"));
      sY.put("461f89bdee5cebee37d7dea04386b396", new bar.Av("3.5.0-223.0.dev"));
      sY.put("3a896f79c125bb36936cb345507a8e10", new bar.Av("3.5.0-211.0.dev"));
      sY.put("ee17e0dcd4903f37202fce913d63a7b8", new bar.Av("3.5.0-202.0.dev"));
      sY.put("24b37cafceb2be9b58e1783e0f76a288", new bar.Av("3.5.0-187.0.dev"));
      sY.put("779ad8354993312805ece8d8080e54bb", new bar.Av("3.5.0-163.0.dev"));
      sY.put("13658978ca5d6f412243947b1f1df681", new bar.Av("3.5.0-156.0.dev"));
      sY.put("383ba7dedf5bd7fd59a55b55e7b49fea", new bar.Av("3.5.0-143.0.dev"));
      sY.put("ec82e1b6972b7232c6d31be01e2bf5d7", new bar.Av("3.5.0-139.0.dev"));
      sY.put("af5c5420d455eb61b9a2acd4b4b9bfa8", new bar.Av("3.5.0-126.0.dev"));
      sY.put("83193544e71dde4331afebac0574e802", new bar.Av("3.5.0-120.0.dev"));
      sY.put("8787c610dd232d2d3efae139c322b964", new bar.Av("3.5.0-116.0.dev"));
      sY.put("5eab285d7b905901e3ec12f6fe2f76ae", new bar.Av("3.5.0-100.0.dev"));
      sY.put("629462ab6243b1f80e66ea18f2b3366b", new bar.Av("3.5.0-99.0.dev"));
      sY.put("a55d3493eae99fbf3a9f686078d22742", new bar.Av("3.5.0-94.0.dev"));
      sY.put("f91b8b03bf7f30a5e983fd19b23d978d", new bar.Av("3.5.0-78.0.dev"));
      sY.put("e626b3c974f4afdd82d77a14c5e59173", new bar.Av("3.5.0-75.0.dev"));
      sY.put("7cbcabe9a51b7c3590dbf60384efe207", new bar.Av("3.5.0-71.0.dev"));
      sY.put("886c5f5c2ac8e9582b057e1cb010919e", new bar.Av("3.5.0-67.0.dev"));
      sY.put("02c97e55f250b055ab8b4794883debbc", new bar.Av("3.5.0-62.0.dev"));
      sY.put("6bcd85a0d017aff208dd91e2f845a4e8", new bar.Av("3.5.0-56.0.dev"));
      sY.put("5dac24564ec916c7f995b6b3ca7f0760", new bar.Av("3.5.0-55.0.dev"));
      sY.put("bf274ed1fe184ad94ac5643eacb6b9a9", new bar.Av("3.5.0-46.0.dev"));
      sY.put("e61bb4839b7fdba80c82601436582250", new bar.Av("3.5.0-40.0.dev"));
      sY.put("c4b5b8698609f82513cdf460f301146b", new bar.Av("3.5.0-36.0.dev"));
      sY.put("e248a2ed2bedcd70930458d9445069d2", new bar.Av("3.5.0-30.0.dev"));
      sY.put("87c12de830692088c666957109282085", new bar.Av("3.5.0-27.0.dev"));
      sY.put("54738f65622228875f40f3ac2d692234", new bar.Av("3.5.0-24.0.dev"));
      sY.put("d20a1be77c3d3c41b2a5accaee1ce549", new bar.Av("3.5.0-12.0.dev"));
      sY.put("352323c9cf844162824069c5282534ea", new bar.Av("3.4.0-275.0.dev"));
      sY.put("01cf09cd8abb4b94c81ca5285c69348c", new bar.Av("3.4.0-269.0.dev"));
      sY.put("d3c9dfea6ebee65290957e53c30c3814", new bar.Av("3.4.0-267.0.dev"));
      sY.put("4bcd699098f10839d9ac1fb6ca4737f4", new bar.Av("3.4.0-261.0.dev"));
      sY.put("0d66c0c7db9f612bac8e3425ec210d68", new bar.Av("3.4.0-259.0.dev"));
      sY.put("8125a3fab82b349f654d178fefb6f35b", new bar.Av("3.4.0-253.0.dev"));
      sY.put("35e9c5561ce7f275142c220e87b4693f", new bar.Av("3.4.0-244.0.dev"));
      sY.put("2644ae150769b4712787b49a23662d3e", new bar.Av("3.4.0-238.0.dev"));
      sY.put("672bfc278eb12f4e361a9910fa833335", new bar.Av("3.4.0-227.0.dev"));
      sY.put("2bf8c2eecdfe884f00444893c46f03b3", new bar.Av("3.4.0-221.0.dev"));
      sY.put("c5ba66a12cb58a0c24bf7b0b0571435d", new bar.Av("3.4.0-220.0.dev"));
      sY.put("2762e088f9adf71d7503b9436a77f2b0", new bar.Av("3.4.0-212.0.dev"));
      sY.put("75f170bc3de3cc2026e3e159bef60351", new bar.Av("3.4.0-190.2.beta"));
      sY.put("4009e1faf92f3f9665b05cf69a8a0497", new bar.Av("3.4.0-187.0.dev"));
      sY.put("ca8484c827fa7b09afa4bcf68252a6db", new bar.Av("3.4.0-170.0.dev"));
      sY.put("1aa2b2c09bb4ab61cd2c915ec6dc67d0", new bar.Av("3.4.0-163.0.dev"));
      sY.put("3751e4c3d71f812ab89c97ae13164cff", new bar.Av("3.4.0-158.0.dev"));
      sY.put("7261d1fb2f12b9474e743195731a2ddd", new bar.Av("3.4.0-151.0.dev"));
      sY.put("48ced695e4f1140c273568b7ad0a9571", new bar.Av("3.4.0-150.0.dev"));
      sY.put("566025f93b2ddf0f95636bd793112d1b", new bar.Av("3.4.0-147.0.dev"));
      sY.put("5a34833d5d06b37cb5b67de85ef1c0d5", new bar.Av("3.4.0-143.0.dev"));
      sY.put("e7bf9323d8e35b0500be63f3d066108e", new bar.Av("3.4.0-140.0.dev"));
      sY.put("5a19d7935c0f042835e6b6dc17e1273a", new bar.Av("3.4.0-138.0.dev"));
      sY.put("77a863962bddcef0b87847788e7d49cf", new bar.Av("3.4.0-126.0.dev"));
      sY.put("de526b6b436ed4145f228d96208f3c94", new bar.Av("3.4.0-116.0.dev"));
      sY.put("1be522d4e0e29df82235ca9468606967", new bar.Av("3.4.0-88.0.dev"));
      sY.put("926871c14a032337c574a976284ba2f7", new bar.Av("3.4.0-79.0.dev"));
      sY.put("f3c673251d10c02de8189f7d0d59c966", new bar.Av("3.4.0-68.0.dev"));
      sY.put("8edd3ef438b308109a630d532643576c", new bar.Av("3.4.0-40.0.dev"));
      sY.put("04ed6cdedc6323a791cb22208b08a26a", new bar.Av("3.4.0-35.0.dev"));
      sY.put("268da5932189d2c31c7b21cb84edb7d0", new bar.Av("3.4.0-23.0.dev"));
      sY.put("2ca222b7bcc78be288cdecea52ccac58", new bar.Av("3.4.0-14.0.dev"));
      sY.put("908833b43c5d880d80e0e3291271040d", new bar.Av("3.4.0-9.0.dev"));
      sY.put("2fbca81aa1c7c6f0f5181417a7970d07", new bar.Av("3.4.0-8.0.dev"));
      sY.put("ee1eb666c76a5cb7746faf39d0b97547", new bar.Av("3.3.4"));
      sY.put("ab223aefce9b48e2e6b9a42e650a9511", new bar.Av("3.3.0-254.0.dev"));
      sY.put("89143e92a845ecb311b6a3be575f1db3", new bar.Av("3.3.0-235.0.dev"));
      sY.put("6f75c22f2d951400e14c4e7214b7fe29", new bar.Av("3.3.0-229.0.dev"));
      sY.put("f758924bdfe26a8bca6c96fa1335bf8e", new bar.Av("3.3.0-227.0.dev"));
      sY.put("a741ba601bd66e2a38a5e8f9da437cd3", new bar.Av("3.3.0-222.0.dev"));
      sY.put("667cacb26758610b2e90a87131fec7b6", new bar.Av("3.3.0-219.0.dev"));
      sY.put("8ab7bbb3e0e4f04fdd89b75f480d5b90", new bar.Av("3.3.0-210.0.dev"));
      sY.put("d2cceaeff6bbfbcb2ab534df3ee0ee28", new bar.Av("3.3.0-203.0.dev"));
      sY.put("5b5c9635430dc0c7802ec9c087410a74", new bar.Av("3.3.0-194.0.dev"));
      sY.put("2ae2d640dd26f0ae4b0a72f1db32e57e", new bar.Av("3.3.0-192.0.dev"));
      sY.put("8b43434a6666a4f8eb2de8ecf8be4f82", new bar.Av("3.3.0-174.3.beta"));
      sY.put("f5fae572a9aec9b15e0689760c2e0257", new bar.Av("3.3.0-173.0.dev"));
      sY.put("a95e6d60c53f582199216a1d71d1a8a9", new bar.Av("3.3.0-158.0.dev"));
      sY.put("ea3ccc6100cf8f85f9845ba1a2f30560", new bar.Av("3.3.0-155.0.dev"));
      sY.put("d1211c1eccc2df5e00fca94d034b7000", new bar.Av("3.3.0-147.0.dev"));
      sY.put("f59b72fc848b72ecce215681b11781ea", new bar.Av("3.3.0-139.0.dev"));
      sY.put("2445dfd4be914b9035e6646f36970b3c", new bar.Av("3.3.0-96.0.dev"));
      sY.put("0e3774486f8df5dda79de43efdb24304", new bar.Av("3.3.0-93.0.dev"));
      sY.put("d5ece25ca220c9785a8a4a425614e4e3", new bar.Av("3.3.0-82.0.dev"));
      sY.put("5327ec96a3590929b195b5ba30aa44be", new bar.Av("3.3.0-68.0.dev"));
      sY.put("ee291cf977d119f7df551e6c4ef6a9a5", new bar.Av("3.3.0-56.0.dev"));
      sY.put("1b9fcf55d37212d9bddba48b52cb2092", new bar.Av("3.3.0-45.0.dev"));
      sY.put("18790505885deb38cd79e6a774f0d823", new bar.Av("3.3.0-39.0.dev"));
      sY.put("7f24823277b19cf64ddc66f77e48bf62", new bar.Av("3.3.0-38.0.dev"));
      sY.put("737f28d52aa13c554466074e9cdf9f8c", new bar.Av("3.3.0-32.0.dev"));
      sY.put("86cc3f9bbe196ef41d5f45c8bcf903e1", new bar.Av("3.3.0-7.0.dev"));
      sY.put("f71c76320d35b65f1164dbaa6d95fe09", new bar.Av("3.2.6"));
      sY.put("8b22861357fbc2c8c3a3cd02500428f0", new bar.Av("3.2.0-233.0.dev"));
      sY.put("f105cf3d66970fb41bf76f12d9b38f6d", new bar.Av("3.2.0-211.0.dev"));
      sY.put("e9f3bd5bc1e079d2b4150608e6884e9a", new bar.Av("3.2.0-198.0.dev"));
      sY.put("1752eb1da612fa2eeb0fef5d2d749080", new bar.Av("3.2.0-177.0.dev"));
      sY.put("2112888298f0705e7f9919bdcf9e2d0a", new bar.Av("3.2.0-162.0.dev"));
      sY.put("8b4ce61baff624ad78be1b732fe65e44", new bar.Av("3.2.0-137.0.dev"));
      sY.put("7fa63726c5356ef2c53682747aa6a1d2", new bar.Av("3.2.0-135.0.dev"));
      sY.put("fd89ca26d38c62af5c097a16d3418736", new bar.Av("3.2.0-134.1.beta"));
      sY.put("0849d72f5307325354e1b76ca47373b4", new bar.Av("3.2.0-132.0.dev"));
      sY.put("5a9b8af18beb469ff41df5434819fa49", new bar.Av("3.2.0-125.0.dev"));
      sY.put("f41091401bebc0628fe1c0ddfa26c15c", new bar.Av("3.2.0-115.0.dev"));
      sY.put("6ee88ef0dd2fd6c7cc6b4a1c6eced27d", new bar.Av("3.2.0-112.0.dev"));
      sY.put("f1d2c6a6d43861e11ab94500308292b5", new bar.Av("3.2.0-109.0.dev"));
      sY.put("be3fb6fb0da8832e9052b5fd62bd540d", new bar.Av("3.2.0-106.0.dev"));
      sY.put("e0728df46714c7e6388959a51c947267", new bar.Av("3.2.0-99.0.dev"));
      sY.put("06c374b59512891d782ea229a17d3094", new bar.Av("3.2.0-97.0.dev"));
      sY.put("ac87a1b703d05ef84d2acaf1f4b50fa2", new bar.Av("3.2.0-96.0.dev"));
      sY.put("c65d4d6b3b40f50954384bb18bfec6e4", new bar.Av("3.2.0-83.0.dev"));
      sY.put("e5f8531e52dba3367c58e1a15124ab1a", new bar.Av("3.2.0-73.0.dev"));
      sY.put("70c3ff6562de82b9494cf4f3e23753e3", new bar.Av("3.2.0-72.0.dev"));
      sY.put("de0a0ee314b6a2f272ce9645db07ed09", new bar.Av("3.2.0-69.0.dev"));
      sY.put("6ec0dd3d3de44d4167b6292d30f9c7fe", new bar.Av("3.2.0-59.0.dev"));
      sY.put("243e2d92fc5cd62a2a60ad3c0dd42bbd", new bar.Av("3.2.0-54.0.dev"));
      sY.put("da9403626542e0723c344892fc0c1243", new bar.Av("3.2.0-48.0.dev"));
      sY.put("9f955a9e302162b540d107bf71dbdaa0", new bar.Av("3.2.0-47.0.dev"));
      sY.put("b63f41229f2d3db31322b62c3d39978a", new bar.Av("3.2.0-46.0.dev"));
      sY.put("8cdc6329004b22ad97760d4e2f412ce5", new bar.Av("3.2.0-38.0.dev"));
      sY.put("7e673cbf6ad7f6a9c8addedcfa5824b2", new bar.Av("3.2.0-11.0.dev"));
      sY.put("d930de8088ce430e9e78326e432e010c", new bar.Av("3.2.0-10.0.dev"));
      sY.put("a3598ed12db2eed7d13870f07e271775", new bar.Av("3.2.0-5.0.dev"));
      sY.put("7dbbeeb8ef7b91338640dca3927636de", new bar.Av("3.1.5"));
      sY.put("9ade36860067c51f2b0598593d429b8e", new bar.Av("3.1.0-332.0.dev"));
      sY.put("05d23217a7bf3698293c1bf51332b0a7", new bar.Av("3.1.0-327.0.dev"));
      sY.put("c948f83ef92dc69ff3e9cb5028cf4410", new bar.Av("3.1.0-324.0.dev"));
      sY.put("6558e62d6f510fc6c318d7062ee43fe1", new bar.Av("3.1.0-310.0.dev"));
      sY.put("b08de15bbc986bb295230e471e4cef08", new bar.Av("3.1.0-306.0.dev"));
      sY.put("a7933f5ff57baf03f723244da410c1b1", new bar.Av("3.1.0-301.0.dev"));
      sY.put("e1073298951e84a689fc27eea50dd8af", new bar.Av("3.1.0-298.0.dev"));
      sY.put("72bb5ba275d2d677e0775c43327b56a9", new bar.Av("3.1.0-297.0.dev"));
      sY.put("f827a05c038789c6d652d2150bb6a49f", new bar.Av("3.1.0-296.0.dev"));
      sY.put("467a2be87649a35b54e1428ab5d18576", new bar.Av("3.1.0-286.0.dev"));
      sY.put("889a0d4fd204aa76018b24938eb8824f", new bar.Av("3.1.0-282.0.dev"));
      sY.put("93b98ca3bf8dcfc7ba1303e636b9cc1b", new bar.Av("3.1.0-281.0.dev"));
      sY.put("8b18cbd27a36ad2438a710924c54ff9a", new bar.Av("3.1.0-269.0.dev"));
      sY.put("038ba20554a8639e370a9e50c9cac2cc", new bar.Av("3.1.0-268.0.dev"));
      sY.put("faff2e27d302b0fa99739a26c411c5ce", new bar.Av("3.1.0-265.0.dev"));
      sY.put("a16916b18bcb44282b1b583a6132358e", new bar.Av("3.1.0-261.0.dev"));
      sY.put("f3394984bd17835a5bfd5c675886e729", new bar.Av("3.1.0-257.0.dev"));
      sY.put("360439feb1f456b06b7ab07fcf031d87", new bar.Av("3.1.0-254.0.dev"));
      sY.put("2a8975979c1ec4ec916cebf23780b8d3", new bar.Av("3.1.0-253.0.dev"));
      sY.put("29b1d5bc38d086d32fcdb2b74c04de79", new bar.Av("3.1.0-246.0.dev"));
      sY.put("3cacf69897ae34a58f352ce54c2c62fb", new bar.Av("3.1.0-242.0.dev"));
      sY.put("252f5e3b2b8ba5659df32c32364fed27", new bar.Av("3.1.0-238.0.dev"));
      sY.put("e5b7565d11b1e167c0aef4e97f451a74", new bar.Av("3.1.0-237.0.dev"));
      sY.put("1d63f1bea249ec61eb280c2af0d11ef3", new bar.Av("3.1.0-234.0.dev"));
      sY.put("de19b7dfc926ad13cc9f10c3d28d41fa", new bar.Av("3.1.0-233.0.dev"));
      sY.put("5726e894a82607ac307e242b31abb633", new bar.Av("3.1.0-217.0.dev"));
      sY.put("982d2a1ba1b6b419c5222a3f8822a11d", new bar.Av("3.1.0-213.0.dev"));
      sY.put("469dcf6e521204a433d5af5fc68cb203", new bar.Av("3.1.0-204.0.dev"));
      sY.put("22cd768a4ad55cb6c43338bba5097584", new bar.Av("3.1.0-202.0.dev"));
      sY.put("56daabd262d37386f397e7b3b657b5e2", new bar.Av("3.1.0-200.0.dev"));
      sY.put("e1feead10f9ee2aab63f75f8990956e0", new bar.Av("3.1.0-199.0.dev"));
      sY.put("d02e95b8e501904132e563b16dc63b36", new bar.Av("3.1.0-191.0.dev"));
      sY.put("99cbb264ba0f24848061ecab4f6a83bb", new bar.Av("3.1.0-190.0.dev"));
      sY.put("d0acff364c5b952c8b90ea5daf5982f6", new bar.Av("3.1.0-188.0.dev"));
      sY.put("c2376a74629a6ebf28ff9a96e719ab50", new bar.Av("3.1.0-177.0.dev"));
      sY.put("23dddce2979f9ac8cc8fd8bc4f079df2", new bar.Av("3.1.0-174.0.dev"));
      sY.put("1178f23ec64b85090afedfb7ec4a9528", new bar.Av("3.1.0-173.0.dev"));
      sY.put("16ad76edd19b537bf6ea64fdd31977a7", new bar.Av("3.1.0-165.0.dev"));
      sY.put("43c981b90102474051837c8350d833b1", new bar.Av("3.1.0-160.0.dev"));
      sY.put("0396dc9d69c0cb5542d21df83138ab5f", new bar.Av("3.1.0-158.0.dev"));
      sY.put("713f3425728f1eb0f5b30fb83df30f4c", new bar.Av("3.1.0-156.0.dev"));
      sY.put("e3d9121a97c23a700b98d2f531a6dcdf", new bar.Av("3.1.0-155.0.dev"));
      sY.put("b470ba60896a7cf869dfd4b849bd7e8e", new bar.Av("3.1.0-153.0.dev"));
      sY.put("5c9f2f55d6a6288d3a7234bc7e188040", new bar.Av("3.1.0-152.0.dev"));
      sY.put("fcbdbf35c75e921d5a243ecfcad4246c", new bar.Av("3.1.0-151.0.dev"));
      sY.put("143a4aa23aae41259f4e7db8d70cb2d3", new bar.Av("3.1.0-149.0.dev"));
      sY.put("0c912ff36d53872fdcc044cd4114eb07", new bar.Av("3.1.0-144.0.dev"));
      sY.put("4da9e9e52fffb32a714b4e26c21f94d6", new bar.Av("3.1.0-136.0.dev"));
      sY.put("6a2c3df45c78d2a2ccbebc81018cd712", new bar.Av("3.1.0-121.0.dev"));
      sY.put("a22e815a7fc036c6b6c7a3cdcd856be6", new bar.Av("3.1.0-119.0.dev"));
      sY.put("57997b9cca87c9318118ef12331487a5", new bar.Av("3.1.0-118.0.dev"));
      sY.put("dce4311b9177a23e01e51ee8f9faddd9", new bar.Av("3.1.0-113.0.dev"));
      sY.put("a615c7a95b7a28e46f036e85f80bdd90", new bar.Av("3.1.0-107.0.dev"));
      sY.put("a56e252a6b89106e7925e569e309b027", new bar.Av("3.1.0-100.0.dev"));
      sY.put("64008c48efc9ea7b04eac05b114b49f3", new bar.Av("3.1.0-97.0.dev"));
      sY.put("36b0375d284ee2af0d0fffc6e6e48fde", new bar.Av("3.1.0-82.0.dev"));
      sY.put("6103d48c2bc202dd982fed93681cabe1", new bar.Av("3.1.0-57.0.dev"));
      sY.put("a10337a88d797e50a074855826cd53a3", new bar.Av("3.1.0-56.0.dev"));
      sY.put("37ee30e3059b13032cefd2a609f8687e", new bar.Av("3.1.0-48.0.dev"));
      sY.put("2db328d6b244ec595526ee930da67b3a", new bar.Av("3.1.0-42.0.dev"));
      sY.put("e3f163802cf27223ccefc5ea026f39aa", new bar.Av("3.1.0-33.0.dev"));
      sY.put("9bf6b9b2ed9258269d59e7f4c86eb026", new bar.Av("3.1.0-30.0.dev"));
      sY.put("84cd66b27376c9faa034efbb5562c57d", new bar.Av("3.1.0-29.0.dev"));
      sY.put("4759be15164611b88032db1cbcbeb149", new bar.Av("3.1.0-26.0.dev"));
      sY.put("72a5104206462cd53b0b8ce6c5394aa0", new bar.Av("3.1.0-25.0.dev"));
      sY.put("f4a73622102454b5177a57910592c6bd", new bar.Av("3.1.0-22.0.dev"));
      sY.put("60ce22f39d1d1e0e8cb88957156406a8", new bar.Av("3.1.0-20.0.dev"));
      sY.put("83c4b1e567456ba7bb4ae1190f225816", new bar.Av("3.1.0-17.0.dev"));
      sY.put("87188d6251c1e03a6c3153ecada53bed", new bar.Av("3.1.0-14.0.dev"));
      sY.put("90b56a561f70cd55e972cb49b79b3d8b", new bar.Av("3.0.7"));
      sY.put("aa64af18e7d086041ac127cc4bc50c5e", new bar.Av("3.0.2"));
      sY.put("06a4ea808ed6a5e8d4b8465a9cc1ff1f", new bar.Av("3.0.0-437.0.dev"));
      sY.put("8427108995905a2af016394f692bd87c", new bar.Av("3.0.0-431.0.dev"));
      sY.put("879645861290ad216e759c3c4d3238c2", new bar.Av("3.0.0-428.0.dev"));
      sY.put("ecbbe72342ecc8c447a24203135623cf", new bar.Av("3.0.0-401.0.dev"));
      sY.put("ac05a4f49be5dfb07a782b4acc0e9afb", new bar.Av("3.0.0-383.0.dev"));
      sY.put("3325531811addb5c1f3dd79f7ed86348", new bar.Av("3.0.0-382.0.dev"));
      sY.put("6f4ecc6fa79ad344fef6c732a8daae81", new bar.Av("3.0.0-380.0.dev"));
      sY.put("e3f4c62035071618c39acd0bfb75d0aa", new bar.Av("3.0.0-379.0.dev"));
      sY.put("454d36e44160804e92dfad59430b178f", new bar.Av("3.0.0-375.0.dev"));
      sY.put("b163880b06ece941b127c8bf18c43af3", new bar.Av("3.0.0-367.0.dev"));
      sY.put("d85184d61167a3fa7caa07cd5f8886ab", new bar.Av("3.0.0-356.0.dev"));
      sY.put("787fb68c551df0a9bd4f35c04d91262e", new bar.Av("3.0.0-330.0.dev"));
      sY.put("8877f6396ad2f7c3aebbae259fc350fe", new bar.Av("3.0.0-327.0.dev"));
      sY.put("ba57392bc990ee00df686d820018e3e2", new bar.Av("3.0.0-313.0.dev"));
      sY.put("2c0ea1088906981af262a50f6ba13903", new bar.Av("3.0.0-310.0.dev"));
      sY.put("618084be871d017013dc342a8ecadba6", new bar.Av("3.0.0-304.0.dev"));
      sY.put("c900affb12eda5b14a7bddf6dacd06a5", new bar.Av("3.0.0-300.0.dev"));
      sY.put("ba0e8f6c952f10a60cb073b538120389", new bar.Av("3.0.0-277.0.dev"));
      sY.put("777089ed3e77485280adcb0d1e5fd9b5", new bar.Av("3.0.0-269.0.dev"));
      sY.put("3fc438132facc8c7f8cdfaad20103acb", new bar.Av("3.0.0-262.0.dev"));
      sY.put("b50e084b9947908091f2472d113900f4", new bar.Av("3.0.0-234.0.dev"));
      sY.put("9c305e27a08d97476668f0a4eb76700f", new bar.Av("3.0.0-223.0.dev"));
      sY.put("8860f13fdeacf945548b94e3293739dc", new bar.Av("3.0.0-218.1.beta"));
      sY.put("090cb34cd7e8e36471452b8c010165e3", new bar.Av("3.0.0-216.0.dev"));
      sY.put("4471ba2df6d5d47b284f0640c0234c86", new bar.Av("3.0.0-212.0.dev"));
      sY.put("93f797199bad0861f46f8b746fb08a44", new bar.Av("3.0.0-199.0.dev"));
      sY.put("cb3e2edd817e5bedfa9e461a04c3ec66", new bar.Av("3.0.0-197.0.dev"));
      sY.put("a0b6da6c67f2ff6a64a3fcbac878d85d", new bar.Av("3.0.0-187.0.dev"));
      sY.put("86171cf612f408a9bf26a1fca5999a6b", new bar.Av("3.0.0-182.0.dev"));
      sY.put("71879bfe1a218257b74f94def731a844", new bar.Av("3.0.0-179.0.dev"));
      sY.put("40c4b9667d4708d66ddff8664cf4728d", new bar.Av("3.0.0-176.0.dev"));
      sY.put("5c170446166cfcca20c4fb4546762561", new bar.Av("3.0.0-173.0.dev"));
      sY.put("88a781dd978193750589ee3715cd1465", new bar.Av("3.0.0-169.0.dev"));
      sY.put("a8346a2193887e730dd1ad617cff1afe", new bar.Av("3.0.0-165.0.dev"));
      sY.put("93f6e4286172274dc17807c501f4dd30", new bar.Av("3.0.0-160.0.dev"));
      sY.put("e265361846c3dd63c9cabf6424a97956", new bar.Av("3.0.0-156.0.dev"));
      sY.put("5c4dbf0a2bbb83f028242a35d3ee7546", new bar.Av("3.0.0-153.0.dev"));
      sY.put("c02f9749d1208af196cba84789700880", new bar.Av("3.0.0-147.0.dev"));
      sY.put("8829551405de87e61c68cbed4c876e8a", new bar.Av("3.0.0-146.0.dev"));
      sY.put("c05dc47480b68330c00395ee7fcd8563", new bar.Av("3.0.0-143.0.dev"));
      sY.put("26b3ab85e7570b8c3cefb25c85cc902e", new bar.Av("3.0.0-140.0.dev"));
      sY.put("5e70cf2088e2639d7d829d297b18de5a", new bar.Av("3.0.0-137.0.dev"));
      sY.put("157fc97a6c4ce480a7be1f37dc5354e2", new bar.Av("3.0.0-134.0.dev"));
      sY.put("7cd30f40bcf357f899a70623df400f18", new bar.Av("3.0.0-133.0.dev"));
      sY.put("d8d74f290570f004eb87b5773449686d", new bar.Av("3.0.0-127.0.dev"));
      sY.put("b1f1a9682699e7342f6315648b5cd860", new bar.Av("3.0.0-126.0.dev"));
      sY.put("04ae76c83b2c33676dbcec41f8e83348", new bar.Av("3.0.0-110.0.dev"));
      sY.put("38844748def0cad2322c73f2f2ec99a1", new bar.Av("3.0.0-104.0.dev"));
      sY.put("58956dd889168cc5618e6216f8b2f716", new bar.Av("3.0.0-103.0.dev"));
      sY.put("3b5e08980e8a48b7dd3b94149b460d01", new bar.Av("3.0.0-88.0.dev"));
      sY.put("fb30dc4e3f35e93a007c9d8c3e85d46f", new bar.Av("3.0.0-71.0.dev"));
      sY.put("b57ceab1f6c7f52bb789ad1e4d1c90eb", new bar.Av("3.0.0-55.0.dev"));
      sY.put("1702379a6a39bbcb6933b1617c284a95", new bar.Av("3.0.0-51.0.dev"));
      sY.put("3d06f339dad9dc70160c3db28a073273", new bar.Av("3.0.0-46.0.dev"));
      sY.put("ecf884918f5332cb80c7ecb8f87a7b95", new bar.Av("3.0.0-38.0.dev"));
      sY.put("fdd941b9db180b21d19857b54203a470", new bar.Av("3.0.0-33.0.dev"));
      sY.put("94d2d8ede43d6f93c228dfe0fe4f6984", new bar.Av("3.0.0-32.0.dev"));
      sY.put("dead1ce7b4c5e8957476a0c18ddbf978", new bar.Av("3.0.0-30.0.dev"));
      sY.put("1fb6fa87e7fec4ea7e1d6d0caf08f33d", new bar.Av("3.0.0-29.0.dev"));
      sY.put("8bca09eb489b71e15bd79ae273d70a48", new bar.Av("3.0.0-23.0.dev"));
      sY.put("c4781d920d6f2d466dde7b9ca5ca533f", new bar.Av("3.0.0-21.0.dev"));
      sY.put("44dcaaae0f65f2cf255e83320b86efbd", new bar.Av("3.0.0-8.0.dev"));
      sY.put("b12cf414e5a6be140cc851d187ad9808", new bar.Av("3.0.0-7.0.dev"));
      sY.put("f1e3a3f8b94f2c3034d1f0216d34fb8a", new bar.Av("3.0.0-6.0.dev"));
      sY.put("7ee7f1c32c03f0a8c9218f843376a1b5", new bar.Av("3.0.0-3.0.dev"));
      sY.put("adb4292f3ec25074ca70abcd2d5c7251", new bar.Av("2.19.6"));
      sY.put("501ef5cbd64ca70b6b42672346af6a8a", new bar.Av("2.19.0"));
      sY.put("51286ce35d33f17c5bfb57929a3ee687", new bar.Av("2.19.0-467.0.dev"));
      sY.put("914fdb1d690558ec7fed1af1071c4fd2", new bar.Av("2.19.0-465.0.dev"));
      sY.put("1ae4f4d164497295e39f5920617b40c9", new bar.Av("2.19.0-453.0.dev"));
      sY.put("d8312ed9233a02af462259a97e95a53e", new bar.Av("2.19.0-452.0.dev"));
      sY.put("c7dc2f8f88f49836586d90b0dbf9d45d", new bar.Av("2.19.0-449.0.dev"));
      sY.put("5ae615b86a62229b8122947901071f74", new bar.Av("2.19.0-443.0.dev"));
      sY.put("41a080f6b032799a5e3139a1a18e447a", new bar.Av("2.19.0-441.0.dev"));
      sY.put("78752706bfd4e92d430b1fbced275495", new bar.Av("2.19.0-436.0.dev"));
      sY.put("648931f1cf135c77792cb316683ff3fc", new bar.Av("2.19.0-435.0.dev"));
      sY.put("c0e636f39f6785b1b38bc11a3f2cad51", new bar.Av("2.19.0-420.0.dev"));
      sY.put("973313a03741df1d48723a17c289a5bc", new bar.Av("2.19.0-415.0.dev"));
      sY.put("68abfc0610d227ee65d46a3f0ddaab9a", new bar.Av("2.19.0-409.0.dev"));
      sY.put("9dab377f12f32c18cb6b23d64522cfd4", new bar.Av("2.19.0-406.0.dev"));
      sY.put("9e9b919bbff57a7b9788db16348925db", new bar.Av("2.19.0-405.0.dev"));
      sY.put("0be8d4d2cd82c75fc445c705a7c3fce3", new bar.Av("2.19.0-403.0.dev"));
      sY.put("f583065121f28f1f7bd955f392ee3f9c", new bar.Av("2.19.0-392.0.dev"));
      sY.put("e820ac4f4472cf861d70c581073bdcfe", new bar.Av("2.19.0-390.0.dev"));
      sY.put("1bd8ca171064c8b8d387e47f96375a6f", new bar.Av("2.19.0-376.0.dev"));
      sY.put("7438d9b3e96ea8f3cdf380dbe1d2eb8b", new bar.Av("2.19.0-371.0.dev"));
      sY.put("03494fc482d00594a93b4f70ef2acd23", new bar.Av("2.19.0-370.0.dev"));
      sY.put("d6c6990be660d26562b5926d10acf1e8", new bar.Av("2.19.0-359.0.dev"));
      sY.put("b5bd16df9fa9ac104924b85288ac924f", new bar.Av("2.19.0-358.0.dev"));
      sY.put("d5c8f2625a7c2668da0b4dc88895beb3", new bar.Av("2.19.0-350.0.dev"));
      sY.put("36031a7cdbf217e2996fdd281b9f3872", new bar.Av("2.19.0-348.0.dev"));
      sY.put("799f89d4ab6290da9c9bbfab9602012f", new bar.Av("2.19.0-334.0.dev"));
      sY.put("51c9b05217864039a6f16d3e5c9af994", new bar.Av("2.19.0-325.0.dev"));
      sY.put("df4c5f031b897e5fb160dd071d2c0da4", new bar.Av("2.19.0-319.0.dev"));
      sY.put("e1171c8dcfd7e9feb93a0b8e74b1f997", new bar.Av("2.19.0-315.0.dev"));
      sY.put("c52d8c2c8e317ae7934d8eae886d8270", new bar.Av("2.19.0-310.0.dev"));
      sY.put("cb08e820e30582cd1ca2343ef8aa3fbf", new bar.Av("2.19.0-286.0.dev"));
      sY.put("76d4b846230cf20a52c4206cba8c1838", new bar.Av("2.19.0-284.0.dev"));
      sY.put("2e71e2e0efa1b3246444a3f98f1d93b3", new bar.Av("2.19.0-281.0.dev"));
      sY.put("63cf007746640bd2d81bd937f4d76df0", new bar.Av("2.19.0-275.0.dev"));
      sY.put("c14a1b2bbb3272625c13673e929ff8e3", new bar.Av("2.19.0-272.0.dev"));
      sY.put("b13e00f0c18ac6d8b2bc7778b2581d2d", new bar.Av("2.19.0-269.0.dev"));
      sY.put("b6a1c0b8562a7680adedfbb8fcc5a065", new bar.Av("2.19.0-256.0.dev"));
      sY.put("8474b4c91552994203c79e6396f77417", new bar.Av("2.19.0-253.0.dev"));
      sY.put("d3b0195b76ef1f52649c8687ac628236", new bar.Av("2.19.0-249.0.dev"));
      sY.put("259e2d3b3cd7a1d86fa8d1823de0dc91", new bar.Av("2.19.0-248.0.dev"));
      sY.put("f450a6a068272430e8a5db9ecd13053a", new bar.Av("2.19.0-243.0.dev"));
      sY.put("38e04e1402652dc940dd18f3ee4e634f", new bar.Av("2.19.0-233.0.dev"));
      sY.put("40ed82673f0baaba84dbcb9bc4a4d7e0", new bar.Av("2.19.0-223.0.dev"));
      sY.put("b33e71dbd811687eb012fe1f12e5fbb4", new bar.Av("2.19.0-219.0.dev"));
      sY.put("7641800eb30f4f05be5632dcf522170a", new bar.Av("2.19.0-211.0.dev"));
      sY.put("e59f75a761ed45ec5ef49f39d5e0e1ee", new bar.Av("2.19.0-210.0.dev"));
      sY.put("def3c91d6f2789c9d71ed1ca55b0f5b0", new bar.Av("2.19.0-200.0.dev"));
      sY.put("43f9456201bf5def02816f702237c544", new bar.Av("2.19.0-192.0.dev"));
      sY.put("6d4e3849794145d550100aaeffb5e295", new bar.Av("2.19.0-191.0.dev"));
      sY.put("0276ad0b12b9de98e5a293004117992f", new bar.Av("2.19.0-186.0.dev"));
      sY.put("0f1919ad477ae4359f9293b77e1e995d", new bar.Av("2.19.0-183.0.dev"));
      sY.put("0b422f9b30dac8149e59e50e981f22f3", new bar.Av("2.19.0-172.0.dev"));
      sY.put("52b1c2ae5c009afbd0370ba7c863b94b", new bar.Av("2.19.0-156.0.dev"));
      sY.put("1044d5d7857485639caee4798a5dcbb7", new bar.Av("2.19.0-153.0.dev"));
      sY.put("f00540d413a3a8d0d706d1f1efcb4200", new bar.Av("2.19.0-144.0.dev"));
      sY.put("67ecb6055e6bc9135b9058e199b2990f", new bar.Av("2.19.0-129.0.dev"));
      sY.put("78120764fd1885fa236e5d9fac23ecce", new bar.Av("2.19.0-126.0.dev"));
      sY.put("de4adf1c2c62238374f4743a575a6a82", new bar.Av("2.19.0-124.0.dev"));
      sY.put("bbbf0aa5dbd0e225ab6cc1d9081a7837", new bar.Av("2.19.0-123.0.dev"));
      sY.put("1b4c710756cc1888aa99acd4801e5bde", new bar.Av("2.19.0-116.0.dev"));
      sY.put("8401db7214b3c4314de60507ac620506", new bar.Av("2.19.0-99.0.dev"));
      sY.put("2872117f1cad30c49cc45915501d4f2b", new bar.Av("2.19.0-90.0.dev"));
      sY.put("ad1cc0568d867ba5db5122d7c55e491d", new bar.Av("2.19.0-79.0.dev"));
      sY.put("8987e12923c0933e1c9bc9d8dba94ed3", new bar.Av("2.19.0-69.0.dev"));
      sY.put("be14182e3038f81e8a560801b3906dd7", new bar.Av("2.19.0-59.0.dev"));
      sY.put("39440884213cc964b8ce22d4d670560b", new bar.Av("2.19.0-51.0.dev"));
      sY.put("50f92de4fe025d6f1c78dd03715c617b", new bar.Av("2.19.0-42.0.dev"));
      sY.put("b31de8076b10d22b6e7e541b98b2aa5b", new bar.Av("2.19.0-40.0.dev"));
      sY.put("900279aa9cd00f01abe6fcffde6118e6", new bar.Av("2.19.0-36.0.dev"));
      sY.put("2ba39ad20fa7cd353a7a47d7297dbc49", new bar.Av("2.19.0-33.0.dev"));
      sY.put("80ae6c169bc07b30ec3fca1be07018d7", new bar.Av("2.19.0-28.0.dev"));
      sY.put("04535a19a6d11b0df503a35bb5c91f5b", new bar.Av("2.19.0-0.0.dev"));
      sY.put("b6d0a1f034d158b0d37b51d559379697", new bar.Av("2.18.7"));
      sY.put("b0e899ec5a90e4661501f0b69e9dd70f", new bar.Av("2.18.5"));
      sY.put("87074c54c8861676f37aa76c4b2b1f01", new bar.Av("2.18.0-284.0.dev"));
      sY.put("07102f97a833cd8e2879e349dc16d271", new bar.Av("2.18.0-258.0.dev"));
      sY.put("2bc796c396a1d0335ea29bf2a77084cc", new bar.Av("2.18.0-251.0.dev"));
      sY.put("cc890f2119b84fa90af9d5cb3bd3b230", new bar.Av("2.18.0-245.0.dev"));
      sY.put("d8c4e23f951f9cf57fe24faf73d541b9", new bar.Av("2.18.0-242.0.dev"));
      sY.put("08c97bb6b092b132f1e7ec94d72e301f", new bar.Av("2.18.0-241.0.dev"));
      sY.put("659afe085946f40cad6c6d7fa0c393c7", new bar.Av("2.18.0-239.0.dev"));
      sY.put("52d7c7ee8b4e52b7d0fae378dbdf5bdd", new bar.Av("2.18.0-233.0.dev"));
      sY.put("f5d9a2cbcabf545f5cb718718ad20673", new bar.Av("2.18.0-224.0.dev"));
      sY.put("aa383f2fd81612902538e1e813a97ae8", new bar.Av("2.18.0-222.0.dev"));
      sY.put("5fe0492196de85dfe636436c22f5913c", new bar.Av("2.18.0-197.0.dev"));
      sY.put("1cd6f11bc2398d18197e1822f4b5437b", new bar.Av("2.18.0-192.0.dev"));
      sY.put("3cdd173d369e1de3bc848cf53710bbd1", new bar.Av("2.18.0-174.0.dev"));
      sY.put("f8adae55bc70865e835f38e1861976d0", new bar.Av("2.18.0-172.0.dev"));
      sY.put("8e50e448b241be23b9e990094f4dca39", new bar.Av("2.18.0-166.0.dev"));
      sY.put("758da859c3ca9361d4610538bb1b5e0f", new bar.Av("2.18.0-164.0.dev"));
      sY.put("eee7f4699c231543c75078cce70d18d3", new bar.Av("2.18.0-161.0.dev"));
      sY.put("cc544affad6008894de16dee12e026f3", new bar.Av("2.18.0-157.0.dev"));
      sY.put("785610aec5d6691872f46f61931d7804", new bar.Av("2.18.0-156.0.dev"));
      sY.put("1b6f018f2ffc422825a69248abc96eb1", new bar.Av("2.18.0-149.0.dev"));
      sY.put("61541f4839e10088d3a85e728fdb30d1", new bar.Av("2.18.0-134.0.dev"));
      sY.put("a39b04ee5ee2a7ec4c57594c36b1c478", new bar.Av("2.18.0-131.0.dev"));
      sY.put("13e6e34171195918fb4bd3de2601f951", new bar.Av("2.18.0-126.0.dev"));
      sY.put("4fa1936d7e2ca0c4a4487df68f46eb6d", new bar.Av("2.18.0-120.0.dev"));
      sY.put("84eb110ac4f6199a76b2f153fc9902e2", new bar.Av("2.18.0-110.0.dev"));
      sY.put("9b6f16ba2e03264205cb0297c176d6f0", new bar.Av("2.18.0-109.0.dev"));
      sY.put("2a035582e425a268dae1be63f3eacfa6", new bar.Av("2.18.0-103.0.dev"));
      sY.put("34399b4e23fa744fb0797fe1b79caa6c", new bar.Av("2.18.0-102.0.dev"));
      sY.put("114ddf9774f8aa460ad75c4066367b20", new bar.Av("2.18.0-92.0.dev"));
      sY.put("1529f382c86afa2f0fc73aeb0b51ee4b", new bar.Av("2.18.0-90.0.dev"));
      sY.put("9cb974d7dfab633a0c6569154b83980c", new bar.Av("2.18.0-85.0.dev"));
      sY.put("005f07a78892d6f90f0be0f29217c42b", new bar.Av("2.18.0-79.0.dev"));
      sY.put("3f29f968406640bcc2b7a836f0e73546", new bar.Av("2.18.0-68.0.dev"));
      sY.put("757060b7bb93e64d2348224fb1e5c043", new bar.Av("2.18.0-66.0.dev"));
      sY.put("cd1251dd552716c402b5070334765f44", new bar.Av("2.18.0-58.0.dev"));
      sY.put("6a9b5a03a7e784a4558b10c769f188d9", new bar.Av("2.18.0-44.1.beta"));
      sY.put("3eeb05ef47ebad895892e7300cee1882", new bar.Av("2.18.0-43.0.dev"));
      sY.put("b7c015a786f960d98f53191bdf3bed10", new bar.Av("2.18.0-42.0.dev"));
      sY.put("87b91e5ee7b08c09bcc8d88843c47bf5", new bar.Av("2.18.0-41.0.dev"));
      sY.put("217c56f8f609d616552a14acfcd9c3a0", new bar.Av("2.18.0-40.0.dev"));
      sY.put("78726ced9c4a3054adc0c053718b340d", new bar.Av("2.18.0-32.0.dev"));
      sY.put("175068b11c22f25ce66ae34ec3f2b4ea", new bar.Av("2.18.0-31.0.dev"));
      sY.put("1441d6b13b8623fa7fbf61433abebd31", new bar.Av("2.17.7"));
      sY.put("f63259f87b68d40d448177621ba45433", new bar.Av("2.17.0-281.0.dev"));
      sY.put("3ae5b21664a9423459f4e8055924e53d", new bar.Av("2.17.0-262.0.dev"));
      sY.put("5030f85049a4a486fcb65008d724f110", new bar.Av("2.17.0-255.0.dev"));
      sY.put("b1f6e1db755c67e2b773ad774636712c", new bar.Av("2.17.0-254.0.dev"));
      sY.put("714f83ad3975e61411992881b02f7084", new bar.Av("2.17.0-243.0.dev"));
      sY.put("e848b6d1f6b80483ade51c9a62ae706b", new bar.Av("2.17.0-239.0.dev"));
      sY.put("052e3dce22dbfb3dfac9ed7e4106727f", new bar.Av("2.17.0-235.0.dev"));
      sY.put("4c223814f8e04fbe6c3e8906623fc850", new bar.Av("2.17.0-232.0.dev"));
      sY.put("11acd8f0dd250b01a0688f11004cf18d", new bar.Av("2.17.0-229.0.dev"));
      sY.put("e8d08d194e14c3e5b788e2ad08e00899", new bar.Av("2.17.0-228.0.dev"));
      sY.put("958d4614bf7e4059992d1b72660b83f0", new bar.Av("2.17.0-227.0.dev"));
      sY.put("1459f2e6d407d105ae57f282d239f368", new bar.Av("2.17.0-222.0.dev"));
      sY.put("9c4330435f95b1efdc4d53b2d18356fa", new bar.Av("2.17.0-213.0.dev"));
      sY.put("5f27893f1d1219edb7c9e28bfa4e00d6", new bar.Av("2.17.0-209.0.dev"));
      sY.put("58047989f90b4c90242e758cf240b4c6", new bar.Av("2.17.0-205.0.dev"));
      sY.put("e82ce038215f416903555950f539d983", new bar.Av("2.17.0-204.0.dev"));
      sY.put("4c07a8158f0a3f0e0bc596c19fec4569", new bar.Av("2.17.0-202.0.dev"));
      sY.put("941bd302ac4630fd2bae122ac52deb11", new bar.Av("2.17.0-200.0.dev"));
      sY.put("a0cb0c928b23bc17a26e062b351dc44d", new bar.Av("2.17.0-190.0.dev"));
      sY.put("863a40e62f8e0cd03265bae8f50a442e", new bar.Av("2.17.0-181.0.dev"));
      sY.put("7ec0bb33cd51743d3b409c4b3b898796", new bar.Av("2.17.0-175.0.dev"));
      sY.put("fefce30e1d7d73fcebd14fbb58d55dc4", new bar.Av("2.17.0-173.0.dev"));
      sY.put("78ab3caa4e3751a8ed5e919a95d4ae41", new bar.Av("2.17.0-170.0.dev"));
      sY.put("c82b9473b092a8f7a2ea05845fe9b70b", new bar.Av("2.17.0-164.0.dev"));
      sY.put("9d3f6599d5e4ff8c0008b422bf0eaafb", new bar.Av("2.17.0-141.0.dev"));
      sY.put("206272d8aa549e5ac099a05af63f0460", new bar.Av("2.17.0-133.0.dev"));
      sY.put("a79d4ee2f38c8be989ba46b2f0a328f7", new bar.Av("2.17.0-124.0.dev"));
      sY.put("a9b04de7ea58b091c6a015a38a7a6a3a", new bar.Av("2.17.0-123.0.dev"));
      sY.put("39200a2e5ebb350f352dbc7f6924ec0c", new bar.Av("2.17.0-122.0.dev"));
      sY.put("028061ca53a52205861e1fb161da7285", new bar.Av("2.17.0-99.0.dev"));
      sY.put("441d1a7183de22cb2a9fd39b197e1052", new bar.Av("2.17.0-97.0.dev"));
      sY.put("5232f1307e93c131db1868386557bffc", new bar.Av("2.17.0-86.0.dev"));
      sY.put("6bcd1979e280eec19628036feefc96c1", new bar.Av("2.17.0-85.0.dev"));
      sY.put("299c695fc3db6b113c80e210bbd25ced", new bar.Av("2.17.0-84.0.dev"));
      sY.put("57259b219659ce063bd959c6fe976ef2", new bar.Av("2.17.0-80.0.dev"));
      sY.put("ded6ef11c73fdc638d6ff6d3ad22a67b", new bar.Av("2.17.0-79.0.dev"));
      sY.put("f24439cf5d766f786c9079a5d8fd200a", new bar.Av("2.17.0-66.0.dev"));
      sY.put("29818ae78cd9983edf2a094820b1adf4", new bar.Av("2.17.0-65.0.dev"));
      sY.put("f242aa1ab9229bf23b53786ac0323373", new bar.Av("2.17.0-63.0.dev"));
      sY.put("f233c451488c009a08f7dc334058e7c0", new bar.Av("2.17.0-53.0.dev"));
      sY.put("21fb4814fcb8a532e2154728fdcec013", new bar.Av("2.17.0-44.0.dev"));
      sY.put("4bec6986001f40be58ddec85dc04065f", new bar.Av("2.17.0-40.0.dev"));
      sY.put("84ba1a56ae1af2d968977e39e6bdf4b9", new bar.Av("2.17.0-34.0.dev"));
      sY.put("d4467bb7dee56ff1cf2274bf49543dc5", new bar.Av("2.17.0-29.0.dev"));
      sY.put("b5f4b7a6fa2eb8a8510977cfe528e4e1", new bar.Av("2.17.0-24.0.dev"));
      sY.put("adf800e7fc7e5cef207374140b30ff46", new bar.Av("2.17.0-5.0.dev"));
      sY.put("d56742caf7b3b3f4bd2df93a9bbb5503", new bar.Av("2.16.2"));
      sY.put("28ed51c39448be00a69c16ba4df2af76", new bar.Av("2.16.0-160.0.dev"));
      sY.put("4d7c798defdcaeb54874018d5cc06dd0", new bar.Av("2.16.0-157.0.dev"));
      sY.put("33642ab6f41c02e4db187b2796222179", new bar.Av("2.16.0-153.0.dev"));
      sY.put("35468ea94c78d94aa76cebd4c3b8995a", new bar.Av("2.16.0-152.0.dev"));
      sY.put("59d751fda6f8b718c5abc52b9bb6b058", new bar.Av("2.16.0-119.0.dev"));
      sY.put("533cdb1ea62a56f19c58ca78615292fe", new bar.Av("2.16.0-118.0.dev"));
      sY.put("79f81bd9ddc8761eff9374ea3ba554a5", new bar.Av("2.16.0-116.0.dev"));
      sY.put("0ed5c2a890ad96d1d5b5b560ef4bb34b", new bar.Av("2.16.0-110.0.dev"));
      sY.put("3318fe66091c0ffbb64faec39976cb7d", new bar.Av("2.16.0-105.0.dev"));
      sY.put("aaf681d10ceabeb69f1c6816bb9c65f3", new bar.Av("2.16.0-71.0.dev"));
      sY.put("bafaf4fde46b108c932edf65f83a9589", new bar.Av("2.16.0-63.0.dev"));
      sY.put("7e7b01f8130f39f50310b5e6a16d509c", new bar.Av("2.16.0-57.0.dev"));
      sY.put("a55b756e4e828731f5dacf60ee936c70", new bar.Av("2.16.0-56.0.dev"));
      sY.put("9c414234e12dc4a92327d707875e5c1c", new bar.Av("2.16.0-45.0.dev"));
      sY.put("6504429a5c5e757e60c4ebcb41059b4c", new bar.Av("2.16.0-27.0.dev"));
      sY.put("5fe25d85ccbd944b2e49f5b1e9010bb1", new bar.Av("2.16.0-26.0.dev"));
      sY.put("ce7bfd712e52879239a5f7a4c7853fd3", new bar.Av("2.16.0-23.0.dev"));
      sY.put("76b479b2b038c71455ad36f929a1262f", new bar.Av("2.16.0-20.0.dev"));
      sY.put("b4ebfd49e2fb4ca9b949e4c4681df05f", new bar.Av("2.16.0-18.0.dev"));
      sY.put("28a816801efac061866380ecde777277", new bar.Av("2.16.0-16.0.dev"));
      sY.put("22e9b03037b8934077ea05af1f18ec79", new bar.Av("2.16.0-3.0.dev"));
      sY.put("0a230f174fe90978646466de92847677", new bar.Av("2.16.0-0.0.dev"));
      sY.put("adf563436d12ba0d50ea5beb7f3be1bb", new bar.Av("2.15.1"));
      sY.put("ddf989407d96de1062aff86df2bcd8a3", new bar.Av("2.15.0-293.0.dev"));
      sY.put("e74e25a29c25d6f59aded7141ebd8cdf", new bar.Av("2.15.0-260.0.dev"));
      sY.put("bf7946b1ca30650fcfa0258c92172380", new bar.Av("2.15.0-250.0.dev"));
      sY.put("8f1ca53dc67970b6e74ab351c182c578", new bar.Av("2.15.0-243.0.dev"));
      sY.put("db730306d17b0e6c8580bef794934f82", new bar.Av("2.15.0-236.0.dev"));
      sY.put("7b7ad6a51e4d4850ff550fe20293cfcf", new bar.Av("2.15.0-234.0.dev"));
      sY.put("d034e16f981b71785d1586c9874095f8", new bar.Av("2.15.0-232.0.dev"));
      sY.put("86c8766082703a45ce4cd619321af90c", new bar.Av("2.15.0-224.0.dev"));
      sY.put("719da11f5896c71458e2258e30c6a5ee", new bar.Av("2.15.0-223.0.dev"));
      sY.put("5e5c48db23167377b7eece597bfc351c", new bar.Av("2.15.0-217.0.dev"));
      sY.put("c1a066134a9adfcef0f84775fd443b43", new bar.Av("2.15.0-214.0.dev"));
      sY.put("4be0b4cd8de253f9f092a038f9743d31", new bar.Av("2.15.0-189.0.dev"));
      sY.put("52b7d1ae0aaaf2eb1bc0e2ba9d958dc7", new bar.Av("2.15.0-185.0.dev"));
      sY.put("24d9d411c2f90c8fbe8907f99e89d4b0", new bar.Av("2.15.0-184.0.dev"));
      sY.put("e4fb8ddac06bb4fc6bfe51c5a4f2c7a2", new bar.Av("2.15.0-159.0.dev"));
      sY.put("495a4912c97ad1f6e7fa0845b225aacc", new bar.Av("2.15.0-158.0.dev"));
      sY.put("854a80d63b40faa3e816eb0025453e3d", new bar.Av("2.15.0-154.0.dev"));
      sY.put("082dc9f10c4e3719990b22c4df2e5574", new bar.Av("2.15.0-142.0.dev"));
      sY.put("f1db3415a45bf430607898342ec95936", new bar.Av("2.15.0-138.0.dev"));
      sY.put("092b8773ca859764d1626544c9e91316", new bar.Av("2.15.0-112.0.dev"));
      sY.put("8afb4bc21dab015026ce8f14e973276a", new bar.Av("2.15.0-105.0.dev"));
      sY.put("4746ccfd9782382562f47693f1c3f637", new bar.Av("2.15.0-100.0.dev"));
      sY.put("b778f48b54482611b0c49023d9f86fe7", new bar.Av("2.15.0-98.0.dev"));
      sY.put("0aef01b2b6ab69cc9a8365405cdff65c", new bar.Av("2.15.0-91.0.dev"));
      sY.put("e075c5163cbb24360761c621264484a8", new bar.Av("2.15.0-90.0.dev"));
      sY.put("cd9196aa895c0b03560bd413048baa7a", new bar.Av("2.15.0-88.0.dev"));
      sY.put("f10776149bf76be288def3c2ca73bdc1", new bar.Av("2.15.0-82.2.beta"));
      sY.put("a2c9eb2504a0f0b18cb890989c285483", new bar.Av("2.15.0-78.0.dev"));
      sY.put("2863fd03ed8cefea523ac7e6419f25b4", new bar.Av("2.15.0-74.0.dev"));
      sY.put("161b5ddf2c36e9cf7d820474e3968351", new bar.Av("2.15.0-72.0.dev"));
      sY.put("8e7455548a00cf1ebf1596dc9fd17170", new bar.Av("2.15.0-69.0.dev"));
      sY.put("c6f170657f1361110e2aed121c627869", new bar.Av("2.15.0-66.0.dev"));
      sY.put("eee905e75c8eec2cc31373589451106b", new bar.Av("2.15.0-65.0.dev"));
      sY.put("530da85962ba17a2bb73f05f42fc6f31", new bar.Av("2.15.0-53.0.dev"));
      sY.put("1d381e617fba775aba4b212149d956de", new bar.Av("2.15.0-52.0.dev"));
      sY.put("f2ed175878eb1ab377414135b301edb8", new bar.Av("2.15.0-51.0.dev"));
      sY.put("a9974cfb2e83999bc5dad2a40e972144", new bar.Av("2.15.0-37.0.dev"));
      sY.put("7ca5a8b672271ab38210659a0111ab43", new bar.Av("2.15.0-36.0.dev"));
      sY.put("6a884b4c15a6e3e2d318ce329af723cb", new bar.Av("2.15.0-34.0.dev"));
      sY.put("2845111295952b75abc6dae3c101021b", new bar.Av("2.15.0-28.0.dev"));
      sY.put("e7958fa493dfbac59da9f59feb405c75", new bar.Av("2.15.0-19.0.dev"));
      sY.put("55d36b37e935bc94b8621c71de2eb009", new bar.Av("2.15.0-18.0.dev"));
      sY.put("203759270f21e74fde0d3e4482b85ec0", new bar.Av("2.15.0-15.0.dev"));
      sY.put("d4f94449414b4c8b6d614cfbb9faa605", new bar.Av("2.15.0-13.0.dev"));
      sY.put("1c1289eb450e1a22430991110b67511a", new bar.Av("2.15.0-10.0.dev"));
      sY.put("6a16168d863eed0affd5e2871bdee229", new bar.Av("2.15.0-9.0.dev"));
      sY.put("d9ef38830fda5fd35fe41a60fd56d0d8", new bar.Av("2.15.0-6.0.dev"));
      sY.put("922d2db3ce18ff8d14859f29288a2813", new bar.Av("2.15.0-1.0.dev"));
      sY.put("9cf77f4405212c45daf608e1cd646852", new bar.Av("2.14.4"));
      sY.put("6aa5a820d7b5eaba74482a0eaf4af3bd", new bar.Av("2.14.0-393.0.dev"));
      sY.put("49202a15b3b732d9309252bd9ae0f991", new bar.Av("2.14.0-391.0.dev"));
      sY.put("89238f1fe8c26cbbba62cdc6e4e09198", new bar.Av("2.14.0-388.0.dev"));
      sY.put("47d2fd85fe2d669fbde6102e01968b36", new bar.Av("2.14.0-385.0.dev"));
      sY.put("273a96cb8030a224844a1367a11ef0c3", new bar.Av("2.14.0-378.0.dev"));
      sY.put("b555f636e5ed67c4cd65ec7250ff2930", new bar.Av("2.14.0-377.1.beta"));
      sY.put("6bd03eebbc5f6c1b1957c6df0151ddc3", new bar.Av("2.14.0-373.0.dev"));
      sY.put("7ed157417bd64fe58dbf26523504cc12", new bar.Av("2.14.0-369.0.dev"));
      sY.put("b37f482b0e877d36533a6c152d5eda39", new bar.Av("2.14.0-366.0.dev"));
      sY.put("2fa905ff9e365caf517680d388e369bf", new bar.Av("2.14.0-360.0.dev"));
      sY.put("0b2f798662571b6bb36dde27a2f473d4", new bar.Av("2.14.0-358.0.dev"));
      sY.put("3c385fd4cbdc1eeeaf7829a5b8397b3a", new bar.Av("2.14.0-355.0.dev"));
      sY.put("1ae3d365df3b79573de35f7679a7e091", new bar.Av("2.14.0-353.0.dev"));
      sY.put("0ace76156789dce96e2a5d89e2895a4b", new bar.Av("2.14.0-351.0.dev"));
      sY.put("3f3cf53d0a6f41b8c4d5d683a9f731d1", new bar.Av("2.14.0-347.0.dev"));
      sY.put("6ec635f906001f785967e6e5877ef120", new bar.Av("2.14.0-345.0.dev"));
      sY.put("13371e4df14660750e3f3eade1c8f7b0", new bar.Av("2.14.0-340.0.dev"));
      sY.put("755fb2aa0f4829927108ee54b9d3327d", new bar.Av("2.14.0-334.0.dev"));
      sY.put("255d4ce5844813c25f12eb62feb79da9", new bar.Av("2.14.0-330.0.dev"));
      sY.put("9649811e0b3643dfbf6c8771a990f719", new bar.Av("2.14.0-325.0.dev"));
      sY.put("b65c72600a32d5f4acd1bcec96c2b8a3", new bar.Av("2.14.0-323.0.dev"));
      sY.put("a8858266062b0d7462435c5117145648", new bar.Av("2.14.0-322.0.dev"));
      sY.put("263ce6bd3860bdcd1daf0037141eacde", new bar.Av("2.14.0-321.0.dev"));
      sY.put("c33298bfdc309c9499a355dd7c509b5d", new bar.Av("2.14.0-319.0.dev"));
      sY.put("161db9edfa7534cd5b422fd109797a2f", new bar.Av("2.14.0-317.0.dev"));
      sY.put("249fb063dd2d06d25c5684c05114eb17", new bar.Av("2.14.0-313.0.dev"));
      sY.put("3339ab66ddaef4a4f473bfc63237f8a9", new bar.Av("2.14.0-312.0.dev"));
      sY.put("f0f078914e571634382e6f4330010572", new bar.Av("2.14.0-309.0.dev"));
      sY.put("7201eb4793a12c595592dc32d98117be", new bar.Av("2.14.0-308.0.dev"));
      sY.put("d6d9391170e9e7040ac5264acccdf0b6", new bar.Av("2.14.0-306.0.dev"));
      sY.put("659a72e41e3276e882709901c27de33d", new bar.Av("2.14.0-304.0.dev"));
      sY.put("fc2351f95b5e1a72b1533cb92ee22916", new bar.Av("2.14.0-296.0.dev"));
      sY.put("3dbc46730a7489f04db5303ab0cff03a", new bar.Av("2.14.0-291.0.dev"));
      sY.put("d0e0034be34a7536da0aadd09c6ffa23", new bar.Av("2.14.0-290.0.dev"));
      sY.put("36048a42701bb71bf50ce1fe739452a2", new bar.Av("2.14.0-288.0.dev"));
      sY.put("33b3b347bf043c6e432fc11cf0cf7254", new bar.Av("2.14.0-287.0.dev"));
      sY.put("bd90a07bdbbe91d30ace188c8962f06c", new bar.Av("2.14.0-272.0.dev"));
      sY.put("7f09796c8f005e483daad7975bb17f7b", new bar.Av("2.14.0-271.0.dev"));
      sY.put("7889e9acadf3de36e5a1cc7d2daf1990", new bar.Av("2.14.0-269.0.dev"));
      sY.put("4668f14d4d56f9022fb1e30d3d14656b", new bar.Av("2.14.0-265.0.dev"));
      sY.put("44a8ee12775e71d1b529ea5680773d71", new bar.Av("2.14.0-263.0.dev"));
      sY.put("179244c371e0a111ba4142c8cdd14de1", new bar.Av("2.14.0-261.0.dev"));
      sY.put("403d8c9e7737331601e5c3c590b19b48", new bar.Av("2.14.0-257.0.dev"));
      sY.put("ca9929faca92c6518c9f4b0dc1f7c24d", new bar.Av("2.14.0-243.0.dev"));
      sY.put("6ae83719a5f8328be9a03eedeaa7da33", new bar.Av("2.14.0-238.0.dev"));
      sY.put("803c618895b1b140abeccbd47a424c2c", new bar.Av("2.14.0-236.0.dev"));
      sY.put("84a80c06c5c3a0ac84f86ee255212405", new bar.Av("2.14.0-232.0.dev"));
      sY.put("cf5d3c3ddfc307458075c8fa928f404b", new bar.Av("2.14.0-231.0.dev"));
      sY.put("57b0d5951a5c89e192dd5fcda932273d", new bar.Av("2.14.0-223.0.dev"));
      sY.put("233989b1ef8938d78fd789f712ab06b9", new bar.Av("2.14.0-222.0.dev"));
      sY.put("4555acb65e85640556396cc36eb812e5", new bar.Av("2.14.0-219.0.dev"));
      sY.put("8ac127db1491e284da870a3486fd7beb", new bar.Av("2.14.0-212.0.dev"));
      sY.put("f454528221a61e66349b5a1469f817f9", new bar.Av("2.14.0-203.0.dev"));
      sY.put("7130d2e3e7718153eb3b9a593e532023", new bar.Av("2.14.0-193.0.dev"));
      sY.put("c8013df373bfd54fe0b6b2e462737a04", new bar.Av("2.14.0-190.0.dev"));
      sY.put("7a5b240780941844bae88eca5dbaa7b8", new bar.Av("2.14.0-189.0.dev"));
      sY.put("e5079cc50fc7bb78128ab4c24d490a97", new bar.Av("2.14.0-186.0.dev"));
      sY.put("5bea50752310ccded34cb4814b5ab006", new bar.Av("2.14.0-181.0.dev"));
      sY.put("e7d4050ec4627ae1c92e0ac8bcc52419", new bar.Av("2.14.0-180.0.dev"));
      sY.put("b39409932dc36c3fca377a621c1cb5a3", new bar.Av("2.14.0-176.0.dev"));
      sY.put("2a5bd2589e5ce11b66bcdf4d01377bab", new bar.Av("2.14.0-175.0.dev"));
      sY.put("9be7e6e9e474a4edd84f5aabbbc90f72", new bar.Av("2.14.0-171.0.dev"));
      sY.put("65817c30a78bb44c3dc3771876b6010a", new bar.Av("2.14.0-152.0.dev"));
      sY.put("fb41b05fc6de686f3a2cb518e3dc7dcf", new bar.Av("2.14.0-150.0.dev"));
      sY.put("090ebbeda95db605c003be863f761ce5", new bar.Av("2.14.0-147.0.dev"));
      sY.put("ae0e1cbea401ebc4a088f94bda7aa3a1", new bar.Av("2.14.0-146.0.dev"));
      sY.put("b94a04a25144701785e6e30df9f2d66d", new bar.Av("2.14.0-137.0.dev"));
      sY.put("3e4db0a4e349cd35af96cb6edeefa092", new bar.Av("2.14.0-134.0.dev"));
      sY.put("79a251c8ff6ecdde5d84c9ca225e92b5", new bar.Av("2.14.0-131.0.dev"));
      sY.put("5ac70af6f5826dff5fc623f59f1f2d97", new bar.Av("2.14.0-125.0.dev"));
      sY.put("db9356a7e37c101edaf19b0a93bebb2b", new bar.Av("2.14.0-123.0.dev"));
      sY.put("03e6d2a403f559edb69f9e16146a50f2", new bar.Av("2.14.0-120.0.dev"));
      sY.put("70c9d29b8a2b6ed500388fe28df883f9", new bar.Av("2.14.0-111.0.dev"));
      sY.put("37469ee1112dcd0eb8a02f0f2f823d85", new bar.Av("2.14.0-110.0.dev"));
      sY.put("25808cf7f705a33a1502a324f37c2de8", new bar.Av("2.14.0-107.0.dev"));
      sY.put("b776210c2cee627ece8252f97d229732", new bar.Av("2.14.0-105.0.dev"));
      sY.put("a83aabe627286f53770f887cb40ed874", new bar.Av("2.14.0-100.0.dev"));
      sY.put("4c3385199fc9c16122077686592092e5", new bar.Av("2.14.0-99.0.dev"));
      sY.put("6015ccc990926c2eb1cecb51b8f009fe", new bar.Av("2.14.0-98.0.dev"));
      sY.put("7c8c926fc907cf615951fa2c2b91f919", new bar.Av("2.14.0-85.0.dev"));
      sY.put("2f836f927b2e9f35bd13c2597208fc6c", new bar.Av("2.14.0-78.0.dev"));
      sY.put("3579193dc7bd3776e81158238742b7d2", new bar.Av("2.14.0-77.0.dev"));
      sY.put("e7ad14f921786dbf76b9add4b0a5c950", new bar.Av("2.14.0-76.0.dev"));
      sY.put("5aa6bc85208470161ad8525c07dc0289", new bar.Av("2.14.0-54.0.dev"));
      sY.put("960c5f6e01bf057848eae4f97e563a36", new bar.Av("2.14.0-51.0.dev"));
      sY.put("8964c48d5ca43d93a2f586e5b30db338", new bar.Av("2.14.0-44.0.dev"));
      sY.put("9459afc3f2c2e4bbbd1df73136a3c88e", new bar.Av("2.14.0-43.0.dev"));
      sY.put("7481ef56316e99af07033165e1ce302d", new bar.Av("2.14.0-35.0.dev"));
      sY.put("d58ee21093763f51825576ad730f6471", new bar.Av("2.14.0-33.0.dev"));
      sY.put("a494c56681844f46ac2752325cb576ef", new bar.Av("2.14.0-31.0.dev"));
      sY.put("c67ea667da5ea6eed7204ebbfd6e5427", new bar.Av("2.14.0-30.0.dev"));
      sY.put("4fe403b9b945d11e4d5bfc6e98ee6308", new bar.Av("2.14.0-29.0.dev"));
      sY.put("51c1a9e67c35c38866ff0443c1d0f71d", new bar.Av("2.14.0-22.0.dev"));
      sY.put("4910ce210fa7693e06ab126a8b10c1ab", new bar.Av("2.14.0-21.0.dev"));
      sY.put("e89bb14ef57e26574631b8178f11ee79", new bar.Av("2.14.0-18.0.dev"));
      sY.put("b781c6c2d0f0630c666c9418611ed340", new bar.Av("2.14.0-16.0.dev"));
      sY.put("e87ae8099ea3973bc16e7b72be0f966f", new bar.Av("2.14.0-14.0.dev"));
      sY.put("6e69b50b437b62fc92f8b01e8e71ed72", new bar.Av("2.14.0-8.0.dev"));
      sY.put("fad45a863bb0a956ae15416330d57400", new bar.Av("2.14.0-4.0.dev"));
      sY.put("f3099d89a5c538cd2a43fc4f0e121a5d", new bar.Av("2.14.0-3.0.dev"));
      sY.put("e4a09dbf2bb120fe4674e0576617a0dc", new bar.Av("2.13.4"));
      sY.put("bb6012f2939af1b6cfbc5107fd3b603e", new bar.Av("2.13.0-236.0.dev"));
      sY.put("8dda214aaa26282768cbfd6be48ceb87", new bar.Av("2.13.0-235.0.dev"));
      sY.put("875d11e327b88692cf49efa763ef8178", new bar.Av("2.13.0-234.0.dev"));
      sY.put("1b2f96037de8dbed07a4547e11a79506", new bar.Av("2.13.0-219.0.dev"));
      sY.put("6bf34475a541a4e51359054833ca6490", new bar.Av("2.13.0-216.0.dev"));
      sY.put("8a317d5ca9432b39e5e73a48fc89f76e", new bar.Av("2.13.0-214.0.dev"));
      sY.put("c1b7477fa678d260501bd01ce4f7725b", new bar.Av("2.13.0-212.0.dev"));
      sY.put("34f6eec64e9371856eaaa278ccf56538", new bar.Av("2.13.0-211.6.beta"));
      sY.put("e980cdaea1ff576f0a5e5cd0a89fc9d4", new bar.Av("2.13.0-203.0.dev"));
      sY.put("7248c213adb6c1ab7dc8eba9e106c3c6", new bar.Av("2.13.0-194.0.dev"));
      sY.put("4340f02f6af32e2a3bd94c8706e0bbce", new bar.Av("2.13.0-193.0.dev"));
      sY.put("ef794c8e08c7097e441486b00dac5a7c", new bar.Av("2.13.0-192.0.dev"));
      sY.put("c3070b7232175617adaed5ca39cc1f2d", new bar.Av("2.13.0-188.0.dev"));
      sY.put("addda38cfef49434f86b9ef6abd6e4ef", new bar.Av("2.13.0-187.0.dev"));
      sY.put("a40c3e3d2d50ed5730898df8a9dd527e", new bar.Av("2.13.0-176.0.dev"));
      sY.put("232db26dbe686de4eb842dcde614674a", new bar.Av("2.13.0-167.0.dev"));
      sY.put("68c1263ec678d199c5c0064c626d9b2f", new bar.Av("2.13.0-164.0.dev"));
      sY.put("c366a01caa59fb5f9d53ee3a54ec1861", new bar.Av("2.13.0-161.0.dev"));
      sY.put("2aab4370fff93025b424e084badf0ee1", new bar.Av("2.13.0-152.0.dev"));
      sY.put("9ed221966de743bf8a06f3de76b03035", new bar.Av("2.13.0-150.0.dev"));
      sY.put("6152ab2003aa01f6dddbf6316e64616f", new bar.Av("2.13.0-148.0.dev"));
      sY.put("bd2090e41120fe0d06323ad9f7aa6c32", new bar.Av("2.13.0-143.0.dev"));
      sY.put("45133aa80b2578e6e9fae50e97d6c3d0", new bar.Av("2.13.0-139.0.dev"));
      sY.put("c9e5331d025d483d0db115bdf8a5bdef", new bar.Av("2.13.0-138.0.dev"));
      sY.put("66536af203f4b902ba4335758fc79b0e", new bar.Av("2.13.0-130.0.dev"));
      sY.put("b65dec6dbaae94639d1d07b2010aafb5", new bar.Av("2.13.0-123.0.dev"));
      sY.put("b6010f11b0e61c3bb83f03d29922d336", new bar.Av("2.13.0-122.0.dev"));
      sY.put("ae2549c9f867074c14b18d0d76dc9530", new bar.Av("2.13.0-121.0.dev"));
      sY.put("2416dbbaa922825aa3e8326e6d790df3", new bar.Av("2.13.0-120.0.dev"));
      sY.put("39a9141bbcc3cae43e6f9f6b7fbaafe3", new bar.Av("2.13.0-117.0.dev"));
      sY.put("cb2c4c93657437ed3524c9e68aa0d7e0", new bar.Av("2.13.0-105.0.dev"));
      sY.put("e041f9c6d235b0ad548cbf6f4b95ef5a", new bar.Av("2.13.0-101.0.dev"));
      sY.put("3c8e1eaa28551a48ae8b4f46f4750e8d", new bar.Av("2.13.0-95.0.dev"));
      sY.put("27b372b43037d0569acf2adf5df87870", new bar.Av("2.13.0-94.0.dev"));
      sY.put("dfe17a0c601c65c0ffce71dd079aff4d", new bar.Av("2.13.0-93.0.dev"));
      sY.put("aac992673ad0e4a5e41716d2a9911c88", new bar.Av("2.13.0-91.0.dev"));
      sY.put("f6a6cef736ffc4c3af80bffd37d6e45b", new bar.Av("2.13.0-87.0.dev"));
      sY.put("f18efa12b5f5843234b44529ab76dad3", new bar.Av("2.13.0-75.0.dev"));
      sY.put("bc1d056183d43af39cc80a544603d0a7", new bar.Av("2.13.0-72.0.dev"));
      sY.put("fe3d63536e7ae14d452e925a8406afeb", new bar.Av("2.13.0-70.0.dev"));
      sY.put("b93e8c85e308ba4f8d218479708c804e", new bar.Av("2.13.0-65.0.dev"));
      sY.put("f4ed6e26c2be5fbbd37b8a30ac840315", new bar.Av("2.13.0-63.0.dev"));
      sY.put("0e0cde5ea00832637e01492cb0aec4c8", new bar.Av("2.13.0-59.0.dev"));
      sY.put("654dd4e8e4b62fbd72031d5c1824c1ea", new bar.Av("2.13.0-58.0.dev"));
      sY.put("b5d9453cf29781f583f621b258fcf346", new bar.Av("2.13.0-51.0.dev"));
      sY.put("ec9b0000e08ddc9032a5aa213e950ef4", new bar.Av("2.13.0-44.0.dev"));
      sY.put("73f2c50cbcf67af7edc804b18df67583", new bar.Av("2.13.0-41.0.dev"));
      sY.put("dcf77928fbdbdde402c2846bff8cfba2", new bar.Av("2.13.0-40.0.dev"));
      sY.put("091d9fefe4da0c3c7e35f215684ef394", new bar.Av("2.13.0-32.0.dev"));
      sY.put("e8b7543ba0865c5bac45bf158bb3d4c1", new bar.Av("2.13.0-30.0.dev"));
      sY.put("89d03b22bf8e837f86da1cf9ccb57bda", new bar.Av("2.13.0-29.0.dev"));
      sY.put("b32babaf05ec04f0a398d30f803dbe97", new bar.Av("2.13.0-28.0.dev"));
      sY.put("d6c8b87d6fdffc8e962dde187c509a44", new bar.Av("2.13.0-26.0.dev"));
      sY.put("fa90d222a37d5852c1685a172a2faa04", new bar.Av("2.13.0-25.0.dev"));
      sY.put("a13d24f49655ab1de7a2da8f822e800d", new bar.Av("2.13.0-22.0.dev"));
      sY.put("ed7af07b9a58b262170caef2f2d0e831", new bar.Av("2.13.0-20.0.dev"));
      sY.put("d35dd7503360ac0571bad443fd335439", new bar.Av("2.13.0-16.0.dev"));
      sY.put("3309d422163e238c4f079ab2eff8468e", new bar.Av("2.13.0-1.0.dev"));
      sY.put("5b97292b25f0a715613b7a28e0734f77", new bar.Av("2.12.4"));
      sY.put("c88b0b66befd6c9996fb3d90043f6b84", new bar.Av("2.12.0-286.0.dev"));
      sY.put("2d1bd9f71cda04ef8a589ca3620cf291", new bar.Av("2.12.0-281.0.dev"));
      sY.put("c4621d00a742561445ec0c5cd0e9f9ba", new bar.Av("2.12.0-279.0.dev"));
      sY.put("dd80a29bf41521d0aedb2622e1b75703", new bar.Av("2.12.0-274.0.dev"));
      sY.put("60ea5d2d944914ee33e16002ea4010b4", new bar.Av("2.12.0-273.0.dev"));
      sY.put("f825989a7b7325a3cb548893706a89cd", new bar.Av("2.12.0-267.0.dev"));
      sY.put("44e70c54ff708592204fd80ba03e1044", new bar.Av("2.12.0-258.0.dev"));
      sY.put("96c234db468600a848728fd8fee577c5", new bar.Av("2.12.0-250.0.dev"));
      sY.put("9ae07a21b00ac5ca7fce4feaa69d457b", new bar.Av("2.12.0-246.0.dev"));
      sY.put("588d197b63d5b4c6e4deeb13c333d5b3", new bar.Av("2.12.0-241.0.dev"));
      sY.put("085052c55bd9b59f60b378c302902992", new bar.Av("2.12.0-240.0.dev"));
      sY.put("71bf58bdfe725ab5d8df46cf4b929e51", new bar.Av("2.12.0-239.0.dev"));
      sY.put("599d2afd7040a7e90a48d0c7185a8e14", new bar.Av("2.12.0-234.0.dev"));
      sY.put("a38382a9ee43aef129837dd8aaf8858c", new bar.Av("2.12.0-232.0.dev"));
      sY.put("1e6b4806049e087434288fb41413f849", new bar.Av("2.12.0-227.0.dev"));
      sY.put("31a2cfdbfd42ff95108f2a9b41f96c2b", new bar.Av("2.12.0-226.0.dev"));
      sY.put("37f5a68f6d9885a875de9587a2fb600c", new bar.Av("2.12.0-225.0.dev"));
      sY.put("786e286ea2c14f7e0d7c8862eec77e0d", new bar.Av("2.12.0-223.0.dev"));
      sY.put("0ff1e59bcef3c58b5eac1a9d56fa8874", new bar.Av("2.12.0-219.0.dev"));
      sY.put("3588ea8d728c4f69465cfe02e3d979d9", new bar.Av("2.12.0-215.0.dev"));
      sY.put("3e85a6c58a1da2bca44473b94f29f6ee", new bar.Av("2.12.0-213.0.dev"));
      sY.put("db61205f8d4d647ec316e02817f6c609", new bar.Av("2.12.0-207.0.dev"));
      sY.put("e23f28e70bb3b5b2694855584584d069", new bar.Av("2.12.0-203.0.dev"));
      sY.put("985d04c89665d4d9bc211fde34445b98", new bar.Av("2.12.0-201.0.dev"));
      sY.put("e0d3f54533a88fa854996c5a4a79cac5", new bar.Av("2.12.0-200.0.dev"));
      sY.put("eb0f61b71eb844e914f1047acb977c17", new bar.Av("2.12.0-199.0.dev"));
      sY.put("40a7b16899a25f3ae398e4d06c159cdc", new bar.Av("2.12.0-196.0.dev"));
      sY.put("aec2861b8a7fb93059cdbfbaf230c8a4", new bar.Av("2.12.0-195.0.dev"));
      sY.put("3e28ce3c17c24422cde684e1e43ddd12", new bar.Av("2.12.0-169.0.dev"));
      sY.put("bedbf9a22819a75380033cee9c87ec01", new bar.Av("2.12.0-167.0.dev"));
      sY.put("80a2d8161a5da6c78bdbe7f82a561c63", new bar.Av("2.12.0-166.0.dev"));
      sY.put("a1d1c095c3982d651b5bcf560a132d3a", new bar.Av("2.12.0-164.0.dev"));
      sY.put("b8310b5af05851e8befda1c87ac6a5d5", new bar.Av("2.12.0-161.0.dev"));
      sY.put("4dfe562eaa01fb4eeda4520951a4edfc", new bar.Av("2.12.0-158.0.dev"));
      sY.put("1e043bc12b9a59eee047d981471a6e90", new bar.Av("2.12.0-157.0.dev"));
      sY.put("a2c4a5c11379e702d6212d85021f3c99", new bar.Av("2.12.0-150.0.dev"));
      sY.put("0737e91fac01b73d8d0690e4a5983c82", new bar.Av("2.12.0-149.0.dev"));
      sY.put("829d11a5989e6bd2526c514b9c2e410e", new bar.Av("2.12.0-142.0.dev"));
      sY.put("dd13345d143f011ba3b8584807f4d025", new bar.Av("2.12.0-135.0.dev"));
      sY.put("9e2165577cef0f0f70f9ff072107920c", new bar.Av("2.12.0-133.7.beta"));
      sY.put("292cf4f6e39475afb212e5a78867aea4", new bar.Av("2.12.0-132.0.dev"));
      sY.put("94bd0dbddf1f88e3829a99c91bc9d27f", new bar.Av("2.12.0-131.0.dev"));
      sY.put("78a6f2e6ec6819f74d64badc562b6640", new bar.Av("2.12.0-129.0.dev"));
      sY.put("eeba2af84300c0774fc21b834a789316", new bar.Av("2.12.0-120.0.dev"));
      sY.put("572c00951a549623955fb060b1e86b6b", new bar.Av("2.12.0-118.0.dev"));
      sY.put("a9c1c66ad91104d63f7e3fa49672242d", new bar.Av("2.12.0-117.0.dev"));
      sY.put("7685c3a5017ed6b38e2cad1030c58c16", new bar.Av("2.12.0-112.0.dev"));
      sY.put("565f5231f2f622fbaa386d1352bf32ad", new bar.Av("2.12.0-110.0.dev"));
      sY.put("8cd88fd0d04992e27b332af64e95f7c4", new bar.Av("2.12.0-108.0.dev"));
      sY.put("e0698682ebb674db52bab87136e64277", new bar.Av("2.12.0-107.0.dev"));
      sY.put("ef282cfaba2be55e990a99adbb79e137", new bar.Av("2.12.0-106.0.dev"));
      sY.put("d78c67363f004e5ac2be8a5856ce2b30", new bar.Av("2.12.0-105.0.dev"));
      sY.put("8809f06e2a510cdb586e29396a42168d", new bar.Av("2.12.0-103.0.dev"));
      sY.put("894f26d944c3343f8888919bbe5f82e5", new bar.Av("2.12.0-102.0.dev"));
      sY.put("e824ed60c3605f6a53dbcd6953fce01e", new bar.Av("2.12.0-101.0.dev"));
      sY.put("472ff9e451bcaea90aa71372df905f1d", new bar.Av("2.12.0-99.0.dev"));
      sY.put("0ecc30e69565a6a98ff582283d55569e", new bar.Av("2.12.0-97.0.dev"));
      sY.put("cbe01e72b3ad5dbd2d71c4d828736280", new bar.Av("2.12.0-81.0.dev"));
      sY.put("24708cb826d46f965308c9f7eeadca45", new bar.Av("2.12.0-80.0.dev"));
      sY.put("9a7ca53956616eff82b5118a5646ecd7", new bar.Av("2.12.0-78.0.dev"));
      sY.put("d17763dc99d87075293ec3c1594eff68", new bar.Av("2.12.0-74.0.dev"));
      sY.put("281f96310a2de003f9337d7e338c8f6e", new bar.Av("2.12.0-73.0.dev"));
      sY.put("759c65f3561c79ebbc9283c2d733045a", new bar.Av("2.12.0-69.0.dev"));
      sY.put("3eece5cd4ca5c541e2481762e87ae18d", new bar.Av("2.12.0-68.0.dev"));
      sY.put("29c4ef881047dbbc6ef049c9c704da3c", new bar.Av("2.12.0-63.0.dev"));
      sY.put("89a059048f2f5fa10df1fe38bfd684bf", new bar.Av("2.12.0-61.0.dev"));
      sY.put("91fadecb70e62f6f74739924eaff73e7", new bar.Av("2.12.0-58.0.dev"));
      sY.put("77a4ebec8e4ca5868f19af4bb3c1e82b", new bar.Av("2.12.0-57.0.dev"));
      sY.put("b06eb66b4930729314aa84f67834bf3d", new bar.Av("2.12.0-56.0.dev"));
      sY.put("da688876c2dd39aa500569bc4a468653", new bar.Av("2.12.0-55.0.dev"));
      sY.put("05873ef250bf08a4fe7b9a7fbcf5dcd2", new bar.Av("2.12.0-54.0.dev"));
      sY.put("a01a8abb6f307051be93a4fcab57b8c8", new bar.Av("2.12.0-52.0.dev"));
      sY.put("be01a0124d1779918b280090e24e28ff", new bar.Av("2.12.0-50.0.dev"));
      sY.put("d2b89fc7627e87abd2120518c2155bfd", new bar.Av("2.12.0-49.0.dev"));
      sY.put("cc25c384b963f988a46fcc0a944e2ebd", new bar.Av("2.12.0-48.0.dev"));
      sY.put("84280ec4214b247767e1d25484caf5a6", new bar.Av("2.12.0-45.0.dev"));
      sY.put("11657c00f86a5c4e69f15a51e844a228", new bar.Av("2.12.0-43.0.dev"));
      sY.put("c8057a556f16eca6e3518bf954b48430", new bar.Av("2.12.0-41.0.dev"));
      sY.put("6c72052441e767f51aaa5fd291edec6f", new bar.Av("2.12.0-40.0.dev"));
      sY.put("b0e7ac1825eee0e08d70ddc1d358370d", new bar.Av("2.12.0-37.0.dev"));
      sY.put("7400c73e3cf209f0f79560ff462f49ba", new bar.Av("2.12.0-34.0.dev"));
      sY.put("a2bdb58c7edf9471da9180bf8185e7f7", new bar.Av("2.12.0-31.0.dev"));
      sY.put("71b77ba1986c18019740cfa1921c9637", new bar.Av("2.12.0-28.0.dev"));
      sY.put("4dff3f9979be54b070d7e914facb2c75", new bar.Av("2.12.0-26.0.dev"));
      sY.put("b3f4559f0feca7684fbc877864fdef56", new bar.Av("2.12.0-22.0.dev"));
      sY.put("f1ad2c227437ca9a41504905af9f0135", new bar.Av("2.12.0-17.0.dev"));
      sY.put("afe6df9ee3b45b3b2200134388665276", new bar.Av("2.12.0-15.0.dev"));
      sY.put("54ee6b58437a6017f95ccdd134276a4a", new bar.Av("2.12.0-14.0.dev"));
      sY.put("1ea425f78c364db155455bd82f0ccd0d", new bar.Av("2.12.0-13.0.dev"));
      sY.put("7fbdf0c44cbce8ebeac78029d81eb299", new bar.Av("2.12.0-0.0.dev"));
      sY.put("d8564aa5f18b17528002ce2dded59639", new bar.Av("2.11.0-273.0.dev"));
      sY.put("a5129cf355ac07d2b4f4155348b184b2", new bar.Av("2.11.0-271.0.dev"));
      sY.put("b74494a298993279320dfa1482ee2966", new bar.Av("2.11.0-269.0.dev"));
      sY.put("ebe8f2d52785c59891310664840321a0", new bar.Av("2.11.0-268.0.dev"));
      sY.put("c8116cee3674abc9880f5bc73bac39db", new bar.Av("2.11.0-265.0.dev"));
      sY.put("41e99e0d4057afd8face4fceda4b3b44", new bar.Av("2.11.0-264.0.dev"));
      sY.put("7f93702fce9d22f46324db99fb24fb28", new bar.Av("2.11.0-263.0.dev"));
      sY.put("5f5dd71f0d89fecf2ed8f6e87c213275", new bar.Av("2.11.0-262.0.dev"));
      sY.put("ec0a9e6eb52b06320c2f7263e5faf2ea", new bar.Av("2.11.0-251.0.dev"));
      sY.put("036d5cda403bd97f7b16b3d8456c0e52", new bar.Av("2.11.0-245.0.dev"));
      sY.put("3a0cac9e521a5c4b7a216545ca3f4fef", new bar.Av("2.11.0-244.0.dev"));
      sY.put("2271cfbd1a08b3bb99ea8727cdd0e564", new bar.Av("2.11.0-243.0.dev"));
      sY.put("e80e75024923f9baac1520c3d68f08e1", new bar.Av("2.11.0-234.0.dev"));
      sY.put("1448a25ffd3b0f8d97bcd5eb5980feb6", new bar.Av("2.11.0-230.0.dev"));
      sY.put("86094209ffffe99e6c885d089d2cf096", new bar.Av("2.11.0-217.0.dev"));
      sY.put("953aa80d78c4d8886e3e4d784fd9d95f", new bar.Av("2.11.0-216.0.dev"));
      sY.put("c89758cbcb5e836e75a7f862876b1313", new bar.Av("2.11.0-205.0.dev"));
      sY.put("66ae3a51a52c58d3d24229ad48e7c2b9", new bar.Av("2.11.0-202.0.dev"));
      sY.put("3a311effee36c3ab1d166c745287f096", new bar.Av("2.11.0-197.0.dev"));
      sY.put("9b08f064d3e0c116ce550700f342be58", new bar.Av("2.11.0-191.0.dev"));
      sY.put("94ebc57c900519a624ff855aae194f43", new bar.Av("2.11.0-189.0.dev"));
      sY.put("49f28fbe1e16c41d8bc794b024c9171b", new bar.Av("2.11.0-187.0.dev"));
      sY.put("70cbcf7b49d7e90b8b50ec409457f1f2", new bar.Av("2.11.0-180.0.dev"));
      sY.put("0ba65875bc44afafb9ad5c4a791c3662", new bar.Av("2.11.0-160.0.dev"));
      sY.put("379d71125269ad7cb0f5bc2c24a6adb4", new bar.Av("2.11.0-159.0.dev"));
      sY.put("41534b7bc63b1ce79c3f24178ce5d538", new bar.Av("2.11.0-155.0.dev"));
      sY.put("8ee4ef7a67df9845fba331734198a953", new bar.Av("2.10.5"));
      sY.put("634619f22b76a6cb5e55c1b2982d2b34", new bar.Av("2.10.0-156.0.dev"));
      sY.put("7447242c75c9fe17e4c8485b0e896fe9", new bar.Av("2.10.0-142.0.dev"));
      sY.put("d969b3e50aa1144556fd3e52648f5b5b", new bar.Av("2.10.0-141.0.dev"));
      sY.put("ebd546b338c127fc12395d652327c084", new bar.Av("2.10.0-138.0.dev"));
      sY.put("72132ca674f40587b279ddc868c35c54", new bar.Av("2.10.0-132.0.dev"));
      sY.put("834e109ce4a610f841233e16d77812be", new bar.Av("2.10.0-129.0.dev"));
      sY.put("f52c4574b59742049e5c60af8485c151", new bar.Av("2.10.0-125.0.dev"));
      sY.put("4a05b444380cc5d274e556ae5e2710f6", new bar.Av("2.10.0-117.0.dev"));
      sY.put("2fe162c80138521e5765d58a3d6e2201", new bar.Av("2.10.0-108.0.dev"));
      sY.put("59a043f49fc5647b7c39ab1345405f42", new bar.Av("2.10.0-103.0.dev"));
      sY.put("f2011fdf164cd1e63be33926e4d071fe", new bar.Av("2.10.0-100.0.dev"));
      sY.put("b68c30cef37f1eab738d325fb34525e3", new bar.Av("2.10.0-94.0.dev"));
      sY.put("2bb44c4920951f0304459f136e9d2ed3", new bar.Av("2.10.0-88.0.dev"));
      sY.put("321da91f89f1738a101d24215764348f", new bar.Av("2.10.0-83.0.dev"));
      sY.put("f5de31057025dabaeb9262ec1b8ef33b", new bar.Av("2.10.0-76.0.dev"));
      sY.put("c8e76aad0a4cf618e281b25e74541248", new bar.Av("2.10.0-64.0.dev"));
      sY.put("826f12878266c4c3a681c384f293d3e9", new bar.Av("2.10.0-63.0.dev"));
      sY.put("b8b24830b0bad212dcbfdef86260e369", new bar.Av("2.10.0-51.0.dev"));
      sY.put("3fbb5898e1b2294b3b432e5a9baa47c3", new bar.Av("2.10.0-48.0.dev"));
      sY.put("612bf7cba778cd548f89491a0341ef12", new bar.Av("2.10.0-43.0.dev"));
      sY.put("08e18470b0860117fa4f694fce3cbcbe", new bar.Av("2.10.0-42.0.dev"));
      sY.put("dda75a81e0c79b517c3f2c004b90e7ef", new bar.Av("2.10.0-39.0.dev"));
      sY.put("31e3775542646ae106bf4af1aa255001", new bar.Av("2.10.0-35.0.dev"));
      sY.put("ba3224bb85f701224b06ada304766586", new bar.Av("2.10.0-30.0.dev"));
      sY.put("af33cdc679c2614004885065e697545a", new bar.Av("2.10.0-28.0.dev"));
      sY.put("48f21c3f973b675eaecb0cfa645f9e69", new bar.Av("2.10.0-20.0.dev"));
      sY.put("c945851a2afcc1bfa847c652cfa2f487", new bar.Av("2.10.0-18.0.dev"));
      sY.put("bdee917ada7c7050445f70d7208bdf68", new bar.Av("2.10.0-17.0.dev"));
      sY.put("3d55fd8dc2bdd2051daae4fe50d630ba", new bar.Av("2.10.0-11.0.dev"));
      sY.put("5f40b0a9f04b5018fa08a9b67fd316cd", new bar.Av("2.10.0-9.0.dev"));
      sY.put("d87fcd044a4c80e6c35920fc6cdb2942", new bar.Av("2.10.0-4.0.dev"));
      sY.put("9ca94046145400ac058738e7175a5fe9", new bar.Av("2.10.0-1.0.dev"));
      sY.put("42bba10587944f3cb20a0cd787f54f6a", new bar.Av("2.10.0-0.0.dev"));
      sY.put("04645b6182fad3d68350d84669869ce5", new bar.Av("2.9.3"));
      sY.put("8b2ca977d1d2920b9839d1b60eade6a7", new bar.Av("2.9.0-21.4.beta"));
      sY.put("4dcdf388b6d17e32f549b3f192d2e425", new bar.Av("2.9.0-20.0.dev"));
      sY.put("c4d0b6c428d41346d67b321d209ab8c8", new bar.Av("2.9.0-19.0.dev"));
      sY.put("873fa138edaf364ce8dfcb1fba236ef5", new bar.Av("2.9.0-18.0.dev"));
      sY.put("175ac6dea94fdb98d812c0ad5874180e", new bar.Av("2.9.0-17.0.dev"));
      sY.put("858ba01987f2393128b8396f92723cda", new bar.Av("2.9.0-16.0.dev"));
      sY.put("6495a3d77b8d4a4e8db8687c93cf39b7", new bar.Av("2.9.0-15.0.dev"));
      sY.put("59da07d9da5a83be4ce75b7913b63dbd", new bar.Av("2.9.0-14.1.beta"));
      sY.put("273bac478fb9a8b3213bfd965207494a", new bar.Av("2.9.0-13.0.dev"));
      sY.put("92b48f782c20c41a191a2298e8c4a537", new bar.Av("2.9.0-12.0.dev"));
      sY.put("e4d6fd3b88bcacb9e9705c12dc28fd1e", new bar.Av("2.9.0-11.0.dev"));
      sY.put("51707624b155cb159a4ad448dc0d3034", new bar.Av("2.9.0-10.0.dev"));
      sY.put("f5ea1e9940b6aaf4df2649a6d379928b", new bar.Av("2.9.0-9.0.dev"));
      sY.put("b58ead73b2c5dfec69565df469bba387", new bar.Av("2.9.0-8.2.beta"));
      sY.put("591abdc59f04644e4d7645c3f0a0f31b", new bar.Av("2.9.0-7.0.dev"));
      sY.put("da13ce52b166990d6c7f0dcf0d730ac5", new bar.Av("2.9.0-5.0.dev"));
      sY.put("decb0f253ab4d3a3946c254fad79e608", new bar.Av("2.9.0-3.0.dev"));
      sY.put("ab9dd1e23936bde7983bb4f38d07fc2b", new bar.Av("2.9.0-2.0.dev"));
      sY.put("e1d88a7096ce781476c6ef06a7a6e46d", new bar.Av("2.9.0-1.0.dev"));
      sY.put("be7d304ff826e2dfac63538e227c3cc5", new bar.Av("2.8.4"));
      sY.put("74edb834fac3fcea79d7ac2d1d6f1fb2", new bar.Av("2.8.2"));
      sY.put("9e7cb7c9394c24c2398410b902673e13", new bar.Av("2.8.0-dev.20.7"));
      sY.put("fcf5987e9905b9cb0284432dfa1ea2ff", new bar.Av("2.8.0-dev.18.0"));
      sY.put("4be4a721360df3f8539da2aa7bcadd64", new bar.Av("2.8.0-dev.17.0"));
      sY.put("f98026d2245e5193b4c4766d883cf831", new bar.Av("2.8.0-dev.16.0"));
      sY.put("bcb42ad731bb2252562cf7119e8d38bf", new bar.Av("2.8.0-dev.15.0"));
      sY.put("8df17e43f5d039756a4be463bd53f16c", new bar.Av("2.8.0-dev.12.0"));
      sY.put("6db16173a4da8708fef9c6c07c532d60", new bar.Av("2.8.0-dev.11.0"));
      sY.put("54f2930bc3bdd125afae831b5d17d784", new bar.Av("2.8.0-dev.10.0"));
      sY.put("688fcd35860eccf5e20ef41f4527d7d1", new bar.Av("2.8.0-dev.9.0"));
      sY.put("44c3a5f352253afa4e3f1348270b91ee", new bar.Av("2.8.0-dev.8.0"));
      sY.put("7e3316e180825d1f779f78c2d77a47d8", new bar.Av("2.8.0-dev.7.0"));
      sY.put("0a57eee2a0409b17fc0a090ad22f394b", new bar.Av("2.8.0-dev.6.0"));
      sY.put("e7c20657d2570e8390cf59131adde9f6", new bar.Av("2.8.0-dev.5.0"));
      sY.put("ef72dba5caa8cd19869b8f24181abfa0", new bar.Av("2.8.0-dev.3.0"));
      sY.put("803754e538cf1a438b1221a2b5faf840", new bar.Av("2.8.0-dev.2.0"));
      sY.put("3bd730fa2ec7dc63dce79b20327f0fca", new bar.Av("2.8.0-dev.1.0"));
      sY.put("b71e748aca89c711207426c407262233", new bar.Av("2.8.0-dev.0.0"));
      sY.put("20e5c4f7dc44368ac5a17643b93665f6", new bar.Av("2.7.2"));
      sY.put("903f3e0c943f024d682b10f894f2e76d", new bar.Av("2.7.0-dev.1.0"));
      sY.put("c6c72a07aeaef43fc233ec1f17a526f5", new bar.Av("2.7.0-dev.0.0"));
      sY.put("cb187597a166f2c0c64a200e22509ee3", new bar.Av("2.6.1"));
      sY.put("b7b7698b59500be00c0c42ed541ea9e3", new bar.Av("2.6.0"));
      sY.put("b4459de19d68e5bc43f6b3c6b1006444", new bar.Av("2.6.0-dev.7.0"));
      sY.put("331b2d0ddc37f27f5e2929e074a29728", new bar.Av("2.6.0-dev.6.0"));
      sY.put("d0e6d7626e06ab31bf67270b37ff292a", new bar.Av("2.6.0-dev.5.0"));
      sY.put("027b45d31921b8bfe69dce6e177254cf", new bar.Av("2.6.0-dev.4.0"));
      sY.put("90dcba6d3dd70ea4b4b1ea17be6e75e9", new bar.Av("2.6.0-dev.2.0"));
      sY.put("0793b2aae071f9974f93f44640b96d35", new bar.Av("2.6.0-dev.1.0"));
      sY.put("05ad3dfca71c916042ac40a6c0b3529a", new bar.Av("2.6.0-dev.0.0"));
      sY.put("c8562f0ee0ebc38ba217c7955956d1cb", new bar.Av("2.5.2"));
      sY.put("762228c411824d5a7ce32f844858415f", new bar.Av("2.5.0-dev.4.0"));
      sY.put("6e44a52d8990d853d90cd3de014d1149", new bar.Av("2.5.0-dev.3.0"));
      sY.put("3fcefe62f019c9481722311aafd778ef", new bar.Av("2.5.0-dev.2.1"));
      sY.put("4839fdc525cd1ea457d0b7f3ccf98b48", new bar.Av("2.5.0-dev.1.0"));
      sY.put("af58d7722c2b875c0ee60222d6655340", new bar.Av("2.5.0-dev.0.0"));
      sY.put("1d7acad1540192ac459cf60344efb7c1", new bar.Av("2.4.1"));
      sY.put("a2967d784bf01190add298db8b62285b", new bar.Av("2.3.2"));
      sY.put("0b4e4e38095461a47b6052ec747497ea", new bar.Av("2.3.2-dev.0.1"));
      sY.put("18595b5f46eab396a85f20129914639a", new bar.Av("2.3.2-dev.0.0"));
      sY.put("21331f1266c75c241be2dc4a50e2c82c", new bar.Av("2.3.1-dev.0.0"));
      sY.put("eed485c757fba5d731e4054412c99f2e", new bar.Av("2.3.0-flutter-1.5.4-hotfix.1"));
      sY.put("9e1fa667daca1ecf538db8507091794e", new bar.Av("2.2.1-dev.4.2"));
      sY.put("8466fd5caa98a9e0b9df3d5cc15f8005", new bar.Av("2.2.1-dev.3.1"));
      sY.put("1e55f60b3942291e9f22991bd568478e", new bar.Av("2.2.1-dev.2.1"));
      sY.put("cde614e2103dec94e73556e623ae89e3", new bar.Av("2.2.1-dev.1.1"));
      sY.put("67d5e890b128b2d4141263de5f1ac0d1", new bar.Av("2.2.1-dev.0.0"));
      sY.put("4e3d9b6c30a637af42ba95170603a94b", new bar.Av("2.2.0-dev.1.1"));
      sY.put("8b95096162f8ceff43ac51475a4b5f91", new bar.Av("2.2.0-dev.0.0"));
      sY.put("e53c6afe72770e2be3f9a70b8cb2faa9", new bar.Av("2.1.2-dev.0.0"));
      sY.put("db080797a69c6d94a5df0428038e3207", new bar.Av("2.1.1"));
      sY.put("3947bc0a491e1bff1e958074ad43839a", new bar.Av("2.1.1-dev.1.0"));
      sY.put("72f85f32f8b202650e37a116c3d0cc08", new bar.Av("2.1.1-dev.0.1"));
      sY.put("00cf048e5f68e211d1daee448848366f", new bar.Av("2.1.1-dev.0.0"));
      sY.put("8343f188ada07642f47c56e518f1307c", new bar.Av("2.1.0"));
      sY.put("d124ce50a30741a188e41c52c424c127", new bar.Av("2.1.0-dev.9.3"));
      sY.put("46b2bfb57b5647c5f7527ff9aa56c69b", new bar.Av("2.1.0-dev.9.1"));
      sY.put("933104e12ed4bfa2bf46e6773ce060be", new bar.Av("2.1.0-dev.8.0"));
      sY.put("62ef4dfcf98329d5284e035d0513511a", new bar.Av("2.1.0-dev.7.1"));
      sY.put("45a2b041cb2fd244807ef704d221ceba", new bar.Av("2.1.0-dev.6.0"));
      sY.put("7ec71d0b495c6fa33d252466e87863c8", new bar.Av("2.1.0-dev.5.0"));
      sY.put("e1194ff9cf248967442c89ce030d18f6", new bar.Av("2.1.0-dev.4.0"));
      sY.put("1b444eb4796616ea2f955f3f1e440801", new bar.Av("2.1.0-dev.3.1"));
      sY.put("bb5ece34bc99da99178a559928e17b47", new bar.Av("2.1.0-dev.2.0"));
      sY.put("f8bb0ff1550f7db7afb32dfce4ad4259", new bar.Av("2.1.0-dev.1.0"));
      sY.put("8f36db640f4df3bd47c6f12bb4b91a6a", new bar.Av("2.1.0-dev.0.0"));
      sY.put("19ac30c2bacca37ef7691604e75be559", new bar.Av("2.0.0"));
      sY.put("2a6006ced04e79d8aa4d1feff45be59d", new bar.Av("2.0.0-dev.69.4"));
      sY.put("087457cd4addb70eb5d531f305a3c076", new bar.Av("2.0.0-dev.69.1"));
      sY.put("30475f169e381220f01264ca2a95ad9f", new bar.Av("2.0.0-dev.68.0"));
      sY.put("ed2bcc375113e16d9c74954b28ac45c4", new bar.Av("2.0.0-dev.67.0"));
      sY.put("33fd8c6486fe1adb16aecb29fc4a5f4d", new bar.Av("2.0.0-dev.65.0"));
      sY.put("e1932f39dc1b5f4b075b85e676ddcd56", new bar.Av("2.0.0-dev.64.2"));
      sY.put("49b3c49aaf6b9e2601b92a7df7397f19", new bar.Av("2.0.0-dev.64.0"));
      sY.put("5b299a7bc29769140af5e8cdfd43ef3c", new bar.Av("2.0.0-dev.63.0"));
      sY.put("56e6e55cc2966020a89db471f1e894f7", new bar.Av("2.0.0-dev.62.0"));
      sY.put("99c57345c29b29355ed4fdc34e9bb015", new bar.Av("2.0.0-dev.61.0"));
      sY.put("20b4a3738b0f67c0804d76dc45b4695b", new bar.Av("2.0.0-dev.60.0"));
      sY.put("0dc36e031d191e441727b7449515bad2", new bar.Av("2.0.0-dev.59.0"));
      sY.put("14b9800c76e3ad4898f97e3abfbe1d1b", new bar.Av("2.0.0-dev.58.0"));
      sY.put("1a9e5187621f37e264024966ad4cabf4", new bar.Av("2.0.0-dev.57.0"));
      sY.put("22fc9961eca947d7c008153323606d1f", new bar.Av("2.0.0-dev.56.0"));
      sY.put("1b155eedbb3a2640a88d2e54d2f2d204", new bar.Av("2.0.0-dev.55.0"));
      sY.put("fe0835451013eccde26c2e4356460509", new bar.Av("2.0.0-dev.54.0"));
      sY.put("e32ae3c1ef5ecab977e16365975081dc", new bar.Av("2.0.0-dev.53.0"));
      sY.put("a70f6028cd357e70c83ea44682a0454b", new bar.Av("2.0.0-dev.52.0"));
      sY.put("22ad2109e0b48190e811d31d4015c9eb", new bar.Av("2.0.0-dev.51.0"));
      sY.put("698a4555275ce557c52c7cf5db9311b7", new bar.Av("2.0.0-dev.50.0"));
      sY.put("39646f79e9336fb65ac68c8568544c92", new bar.Av("2.0.0-dev.49.0"));
      sY.put("817c42433ca6c9dde9c69806382006d6", new bar.Av("2.0.0-dev.48.0"));
      sY.put("6c507f877f3786837891f11657c5ff12", new bar.Av("2.0.0-dev.47.0"));
      sY.put("c43eada86a2f4834d028602dc4840e01", new bar.Av("2.0.0-dev.46.0"));
      sY.put("d72bf5003e5924b61a7943f58e7b6814", new bar.Av("2.0.0-dev.45.0"));
      sY.put("8f8bcefc1534f548f00d8d817877e101", new bar.Av("2.0.0-dev.43.0"));
      sY.put("0053515318c68502ae0307040ac1746b", new bar.Av("2.0.0-dev.42.0"));
      sY.put("48af31030bbb45e2f3e620514fd8a27d", new bar.Av("2.0.0-dev.40.0"));
      sY.put("53a0d04f350a8bff14f0f7f154a19c27", new bar.Av("2.0.0-dev.39.0"));
      sY.put("75eb4b091b7048c053e2072e2292df79", new bar.Av("2.0.0-dev.36.0"));
      sY.put("f7807682d1d605859b90763262a122bc", new bar.Av("2.0.0-dev.35"));
      sY.put("482a6b63734d224fc23043bdd4914c78", new bar.Av("2.0.0-dev.34.0"));
      sY.put("667a3bf9d477f047a8d88dddf6d8bfd1", new bar.Av("2.0.0-dev.33.0"));
      sY.put("1461982fa5039fab6ecead9f19228670", new bar.Av("2.0.0-dev.32.0"));
      sY.put("a198cd299d08be868bfa76910dd89578", new bar.Av("2.0.0-dev.31.0"));
      sY.put("756114858eac47c1e25160edf4d8045d", new bar.Av("2.0.0-dev.30.0"));
      sY.put("9179c2cf7cd0dbc34c1158a481d4c6eb", new bar.Av("2.0.0-dev.29.0"));
      sY.put("6d3e3894481b838714bdbd0e455834a3", new bar.Av("2.0.0-dev.28.0"));
      sY.put("49e0432ebe02754e1880bd569c5d9713", new bar.Av("2.0.0-dev.26.0"));
      sY.put("f32521aa4ab10bbf5580b8976736b6fc", new bar.Av("2.0.0-dev.25.0"));
      sY.put("cf55788653a1ce4839207bea635112ac", new bar.Av("2.0.0-dev.24.0"));
      sY.put("01fb1806ce46d802f8b06517f05e2e1d", new bar.Av("2.0.0-dev.23.0"));
      sY.put("77daaba91fa44c67030dc12050ed09f1", new bar.Av("2.0.0-dev.21.0"));
      sY.put("3528bee2f07ae700286115162f52b43d", new bar.Av("2.0.0-dev.20.0"));
      sY.put("00baf607cf7a26d7ae75a4d73c3eb101", new bar.Av("2.0.0-dev.19.0"));
      sY.put("20dce469ff9a7d5f294c4e88f14cfe51", new bar.Av("2.0.0-dev.18.0"));
      sY.put("5d82aa21085dcd6d9c102151972d2852", new bar.Av("2.0.0-dev.17.0"));
      sY.put("41bd5eab5c21a0d6a57f3da2d31d9545", new bar.Av("2.0.0-dev.16.0"));
      sY.put("1bb3468c9a9a0f85eeeacb5a13872ba3", new bar.Av("2.0.0-dev.15.0"));
      sY.put("3734e5c88475b4401c3ebe98df87db29", new bar.Av("2.0.0-dev.14.0"));
      sY.put("42c99258b896ea28162a3634ab9893c3", new bar.Av("2.0.0-dev.13.0"));
      sY.put("8ed2b9130065c72a181a9a40e17387bd", new bar.Av("2.0.0-dev.12.0"));
      sY.put("4980a5a9e7247ed5f306c8c565d193cc", new bar.Av("2.0.0-dev.11.0"));
      sY.put("3cebf13e885ccde5bf5d36d308390ddf", new bar.Av("2.0.0-dev.10.0"));
      sY.put("cba4233252427d477117f346bcf7bc44", new bar.Av("2.0.0-dev.9.0"));
      sY.put("b533bbc0654d3869afb623cd1842146e", new bar.Av("2.0.0-dev.8.0"));
      sY.put("3768d9fa87021f5c698c9ff34f739d5d", new bar.Av("2.0.0-dev.7.0"));
      sY.put("798a48103ae3ce2c99bb30fe3ed47ff9", new bar.Av("2.0.0-dev.6.0"));
      sY.put("6e50d5430ba45ddf48fa4a40ea54b735", new bar.Av("2.0.0-dev.5.0"));
      sY.put("19d37775f0a12bb8ef148661e264f583", new bar.Av("2.0.0-dev.4.0"));
      sY.put("b8bea48c332c4705483d25c2d9cf654c", new bar.Av("2.0.0-dev.3.0"));
      sY.put("febd6f79ad2f61f82c695d3d78ef9070", new bar.Av("2.0.0-dev.2.0"));
      sY.put("53db5f61774a5fbc5ee04696b38726f8", new bar.Av("2.0.0-dev.1.0"));
      sY.put("d120342d48b35fc67901acb723bb6e9f", new bar.Av("2.0.0-dev.0.1"));
      sY.put("8ee4ef7a67df9845fba331734198a953", new bar.Av("2.10.0", 2L));
      sY.put("5b97292b25f0a715613b7a28e0734f77", new bar.Av("2.12.0", 3L));
      sY.put("e4a09dbf2bb120fe4674e0576617a0dc", new bar.Av("2.13.0", 3L));
      sY.put("9cf77f4405212c45daf608e1cd646852", new bar.Av("2.14.0", 3L));
      sY.put("adf563436d12ba0d50ea5beb7f3be1bb", new bar.Av("2.15.0", 3L));
      sY.put("d56742caf7b3b3f4bd2df93a9bbb5503", new bar.Av("2.16.0", 3L));
      sY.put("1441d6b13b8623fa7fbf61433abebd31", new bar.Av("2.17.0", 3L));
      sY.put("b0e899ec5a90e4661501f0b69e9dd70f", new bar.Av("2.18.0", 3L));
      sY.put("501ef5cbd64ca70b6b42672346af6a8a", new bar.Av("2.19.0", 3L));
      sY.put("adb4292f3ec25074ca70abcd2d5c7251", new bar.Av("2.19.1", 3L));
      sY.put("aa64af18e7d086041ac127cc4bc50c5e", new bar.Av("3.0.0", 3L));
      sY.put("90b56a561f70cd55e972cb49b79b3d8b", new bar.Av("3.0.6", 3L));
      sY.put("7dbbeeb8ef7b91338640dca3927636de", new bar.Av("3.1.0", 3L));
      sY.put("f71c76320d35b65f1164dbaa6d95fe09", new bar.Av("3.2.0", 3L));
      sY.put("ee1eb666c76a5cb7746faf39d0b97547", new bar.Av("3.3.0", 3L));
      sY.put("d20a1be77c3d3c41b2a5accaee1ce549", new bar.Av("3.4.0", 3L));
      sY.put("80a49c7111088100a233b2ae788e1f48", new bar.Av("3.5.0", 3L));
      sY.put("f956f595844a2f845a55707faaaa51e4", new bar.Av("3.6.0", 3L));
      sY.put("d91c0e6f35f0eb2e44124e8f42aa44a7", new bar.Av("3.7.0", 3L));
      sY.put("830f4f59e7969c70b595182826435c19", new bar.Av("3.8.0", 3L));
   }

   static class Av {
      String pC;
      Long A;

      public Av(String var1, long var2) {
         if (var1 == null) {
            throw new RuntimeException();
         } else {
            this.pC = var1;
            this.A = var2;
         }
      }

      public Av(String var1) {
         this.pC = var1;
      }

      long pC() {
         if (this.A != null) {
            return this.A;
         } else {
            String[] var1 = this.pC.split("\\.");

            int var2;
            try {
               var2 = Integer.parseInt(var1[0]);
               int var3 = Integer.parseInt(var1[1]);
               if (var2 == 2) {
                  if (var3 < 12) {
                     return 2L;
                  }

                  return 3L;
               }
            } catch (Exception var4) {
               return 0L;
            }

            return var2 == 3 ? 3L : 0L;
         }
      }
   }
}
