package com.pnfsoftware.jebglobal;

public class cga {
   private static final com.pnfsoftware.jeb.corei.parsers.mips.Tb[] Ek = cfs.wS;
   private static final com.pnfsoftware.jeb.corei.parsers.mips.Tb[] hK = cfs.wS;
   private static final com.pnfsoftware.jeb.corei.parsers.mips.Tb[] Er = cfs.WR;
   private static final com.pnfsoftware.jeb.corei.parsers.mips.Tb[] FE = cfs.WR;
   private static final cfk Aj = new cfm(cfn.kS, cfn.pC);
   private static final cfk[] EX = new cfk[]{cfn.ys, Aj};
   static final cfs[] pC = new cfs[]{
      new cfs("LWX", Ek, EX),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      new cfs("LHX", Ek, EX),
      cfs.pC,
      new cfs("LBUX", Ek, EX),
      cfs.pC,
      new cfs("LDX", Er, EX),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC
   };
   public static final cfs A = new cfs("BPOSGE32", cgc.pC, cfo.eP, Ek, cfl.A);
   public static final cfs kS = new cfs("BPOSGE32C", cgc.pC, cfo.eP, Ek, cfl.A);
   public static final cfs wS = new cfs("BPOSGE64", cgc.pC, cfo.eP, Er, cfl.A);
   private static final cfk[] LM = new cfk[]{cfn.kS, cfn.pC};
   public static final cfs UT = new cfs("INSV", Ek, LM);
   public static final cfs E = new cfs("DINSV", Ek, LM);
   private static final cfk[] mv = new cfk[]{cfn.ys, cfn.pC};
   public static final cfs[] sY = new cfs[]{
      new cfs("ADDU.QB", Ek, cfn.ah),
      new cfs("SUBU.QB", Ek, cfn.ah),
      cfs.pC,
      cfs.pC,
      new cfs("ADDU_S.QB", Ek, cfn.ah),
      new cfs("SUBU_S.QB", Ek, cfn.ah),
      new cfs("MULEU_S.PH.QBL", Ek, cfn.ah),
      new cfs("MULEU_S.PH.QBR", Ek, cfn.ah),
      new cfs("ADDU.PH", hK, cfn.ah),
      new cfs("SUBU.PH", hK, cfn.ah),
      new cfs("ADDQ.PH", Ek, cfn.ah),
      new cfs("SUBQ.PH", Ek, cfn.ah),
      new cfs("ADDU_S.PH", hK, cfn.ah),
      new cfs("SUBU_S.PH", hK, cfn.ah),
      new cfs("ADDQ_S.PH", Ek, cfn.ah),
      new cfs("SUBQ_S.PH", Ek, cfn.ah),
      new cfs("ADDSC", Ek, cfn.ah),
      new cfs("ADDWC", Ek, cfn.ah),
      new cfs("MODSUB", Ek, cfn.ah),
      cfs.pC,
      new cfs("RADDU.W.QB", Ek, mv),
      cfs.pC,
      new cfs("ADDQ_S.W", Ek, cfn.ah),
      new cfs("SUBQ_S.W", Ek, cfn.ah),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      new cfs("MULEQ_S.W.PHL", Ek, cfn.ah),
      new cfs("MULEQ_S.W.PHR", Ek, cfn.ah),
      new cfs("MULQ_S.PH", hK, cfn.ah),
      new cfs("MULQ_RS.PH", Ek, cfn.ah)
   };
   private static cfk[] sO = new cfk[]{cfn.kS, cfn.pC, cfl.ED};
   public static final cfs[] ys = new cfs[]{
      new cfs("CMPU.EQ.QB", Ek, cfn.ED),
      new cfs("CMPU.LT.QB", Ek, cfn.ED),
      new cfs("CMPU.LE.QB", Ek, cfn.ED),
      new cfs("PICK.QB", Ek, cfn.ah),
      new cfs("CMPGU.EQ.QB", Ek, cfn.ah),
      new cfs("CMPGU.LT.QB", Ek, cfn.ah),
      new cfs("CMPGU.LE.QB", Ek, cfn.ah),
      cfs.pC,
      new cfs("CMP.EQ.PH", Ek, cfn.ED),
      new cfs("CMP.LT.PH", Ek, cfn.ED),
      new cfs("CMP.LE.PH", Ek, cfn.ED),
      new cfs("PICK.PH", Ek, cfn.ah),
      new cfs("PRECRQ.QB.PH", Ek, cfn.ah),
      new cfs("PRECR.QB.PH", hK, cfn.ah),
      new cfs("PACKRL.PH", Ek, cfn.ah),
      new cfs("PRECRQU_S.QB.PH", Ek, cfn.ah),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      new cfs("PRECRQ.PH.W", Ek, cfn.ah),
      new cfs("PRECRQ_RS.PH.W", Ek, cfn.ah),
      cfs.pC,
      cfs.pC,
      new cfs("CMPGDU.EQ.QB", hK, cfn.ah),
      new cfs("CMPGDU.LT.QB", hK, cfn.ah),
      new cfs("CMPGDU.LE.QB", hK, cfn.ah),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      new cfs("PRECR_SRA.PH.W", hK, sO),
      new cfs("PRECR_SRA_R.PH.W", hK, sO)
   };
   private static final cfk[] os = new cfk[]{cfn.ys, cfn.kS};
   private static final cfk[] Cu = new cfk[]{cfn.ys, cfl.hK};
   private static final cfk[] hZ = new cfk[]{cfn.ys, cfl.Er};
   public static final cfs[] ld = new cfs[]{
      cfs.pC,
      new cfs("ABSQ_S.QB", hK, os),
      new cfs("REPL.QB", Ek, hZ),
      new cfs("REPLV.QB", Ek, os),
      new cfs("PRECEQU.PH.QBL", Ek, os),
      new cfs("PRECEQU.PH.QBR", Ek, os),
      new cfs("PRECEQU.PH.QBLA", Ek, os),
      new cfs("PRECEQU.PH.QBRA", Ek, os),
      cfs.pC,
      new cfs("ABSQ_S.PH", Ek, os),
      new cfs("REPL.PH", Ek, Cu),
      new cfs("REPLV.PH", Ek, os),
      new cfs("PRECEQ.W.PHL", Ek, os),
      new cfs("PRECEQ.W.PHR", Ek, os),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      new cfs("ABSQ_S.W", Ek, os),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      new cfs("BITREV", Ek, os),
      new cfs("PRECEU.PH.QBL", Ek, os),
      new cfs("PRECEU.PH.QBR", Ek, os),
      new cfs("PRECEU.PH.QBLA", Ek, os),
      new cfs("PRECEU.PH.QBRA", Ek, os)
   };
   private static final cfk[] UW = new cfk[]{cfn.ys, cfn.kS, cfl.Aj};
   private static final cfk[] PR = new cfk[]{cfn.ys, cfn.kS, cfl.FE};
   private static final cfk[] cX = new cfk[]{cfn.ys, cfn.kS, cfl.EX};
   private static final cfk[] DQ = new cfk[]{cfn.ys, cfn.kS, cfn.pC};
   public static final cfs[] gp = new cfs[]{
      new cfs("SHLL.QB", Ek, PR),
      new cfs("SHRL.QB", Ek, PR),
      new cfs("SHLLV.QB", Ek, DQ),
      new cfs("SHRLV.QB", Ek, DQ),
      new cfs("SHRA.QB", hK, PR),
      new cfs("SHRA_R.QB", hK, PR),
      new cfs("SHRAV.QB", hK, DQ),
      new cfs("SHRAV_R.QB", hK, DQ),
      new cfs("SHLL.PH", Ek, UW),
      new cfs("SHRA.PH", Ek, UW),
      new cfs("SHLLV.PH", Ek, DQ),
      new cfs("SHRAV.PH", Ek, DQ),
      new cfs("SHLL_S.PH", Ek, UW),
      new cfs("SHRA_R.PH", Ek, UW),
      new cfs("SHLLV_S.PH", Ek, DQ),
      new cfs("SHRAV_R.PH", Ek, DQ),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      new cfs("SHLL_S.W", Ek, cX),
      new cfs("SHRA_R.W", Ek, cX),
      new cfs("SHLLV_S.W", Ek, DQ),
      new cfs("SHRAV_R.W", Ek, DQ),
      cfs.pC,
      new cfs("SHRL.PH", hK, UW),
      cfs.pC,
      new cfs("SHRLV.PH", hK, DQ),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC
   };
   public static final cfs[] oT = new cfs[]{
      new cfs("ADDUH.QB", hK, cfn.ah),
      new cfs("SUBUH.QB", hK, cfn.ah),
      new cfs("ADDUH_R.QB", hK, cfn.ah),
      new cfs("SUBUH_R.QB", hK, cfn.ah),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      new cfs("ADDQH.PH", hK, cfn.ah),
      new cfs("SUBQH.PH", hK, cfn.ah),
      new cfs("ADDQH_R.PH", hK, cfn.ah),
      new cfs("SUBQH_R.PH", hK, cfn.ah),
      new cfs("MUL.PH", hK, cfn.ah),
      cfs.pC,
      new cfs("MUL_S.PH", hK, cfn.ah),
      cfs.pC,
      new cfs("ADDQH.W", hK, cfn.ah),
      new cfs("SUBQH.W", hK, cfn.ah),
      new cfs("ADDQH_R.W", hK, cfn.ah),
      new cfs("SUBQH_R.W", hK, cfn.ah),
      cfs.pC,
      cfs.pC,
      new cfs("MULQ_S.W", hK, cfn.ah),
      new cfs("MULQ_RS.W", hK, cfn.ah),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC
   };
   private static final cfk[] ZN = new cfk[]{cfn.WR, cfn.pC, cfn.kS};
   public static final cfs[] fI = new cfs[]{
      new cfs("DPA.W.PH", hK, ZN),
      new cfs("DPS.W.PH", hK, ZN),
      new cfs("MULSA.W.PH", hK, ZN),
      new cfs("DPAU.H.QBL", Ek, ZN),
      new cfs("DPAQ_S.W.PH", Ek, ZN),
      new cfs("DPSQ_S.W.PH", Ek, ZN),
      new cfs("MULSAQ_S.W.PH", Ek, ZN),
      new cfs("DPAU.H.QBR", Ek, ZN),
      new cfs("DPAX.W.PH", hK, ZN),
      new cfs("DPSX.W.PH", hK, ZN),
      cfs.pC,
      new cfs("DPSU.H.QBL", Ek, ZN),
      new cfs("DPAQ_SA.L.W", Ek, ZN),
      new cfs("DPSQ_SA.L.W", Ek, ZN),
      cfs.pC,
      new cfs("DPSU.H.QBR", Ek, ZN),
      new cfs("MAQ_SA.W.PHL", Ek, ZN),
      cfs.pC,
      new cfs("MAQ_SA.W.PHR", Ek, ZN),
      cfs.pC,
      new cfs("MAQ_S.W.PHL", Ek, ZN),
      cfs.pC,
      new cfs("MAQ_S.W.PHR", Ek, ZN),
      cfs.pC,
      new cfs("DPAQX_S.W.PH", hK, ZN),
      new cfs("DPSQX_S.W.PH", hK, ZN),
      new cfs("DPAQX_SA.W.PH", hK, ZN),
      new cfs("DPSQX_SA.W.PH", hK, ZN),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC
   };
   public static final cfs[] WR = new cfs[]{
      new cfs("APPEND", hK, sO),
      new cfs("PREPEND", hK, sO),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      new cfs("BALIGN", hK, cfn.kS, cfn.pC, cfl.LM),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC
   };
   private static final cfk[] OB = new cfk[]{cfn.kS, cfn.WR, cfl.EX};
   private static final cfk[] pF = new cfk[]{cfn.kS, cfn.WR, cfn.pC};
   private static final cfk[] Bc = new cfk[]{cfn.pC, cfn.WR};
   private static final cfk[] OI = new cfk[]{cfn.ys, cfl.hZ};
   private static final cfk[] Bf = new cfk[]{cfn.pC, cfl.Cu};
   public static final cfs[] NS = new cfs[]{
      new cfs("EXTR.W", Ek, OB),
      new cfs("EXTRV.W", Ek, pF),
      new cfs("EXTP", Ek, OB),
      new cfs("EXTPV", Ek, pF),
      new cfs("EXTR_R.W", Ek, OB),
      new cfs("EXTRV_R.W", Ek, pF),
      new cfs("EXTR_RS.W", Ek, OB),
      new cfs("EXTRV_RS.W", Ek, pF),
      cfs.pC,
      cfs.pC,
      new cfs("EXTPDP", Ek, OB),
      new cfs("EXTPDPV", Ek, pF),
      cfs.pC,
      cfs.pC,
      new cfs("EXTR_S.H", Ek, OB),
      new cfs("EXTRV_S.H", Ek, pF),
      cfs.pC,
      cfs.pC,
      new cfs("RDDSP", Ek, OI),
      new cfs("WRDSP", Ek, Bf),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      new cfs("SHILO", Ek, cfn.WR, cfl.sO),
      new cfs("SHILOV", Ek, cfn.WR, cfn.pC),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      new cfs("MTHLIP", Ek, Bc)
   };
   static final cfs[] vP = new cfs[]{
      new cfs("MFHI", cfs.E, cfn.ys, cfn.fI),
      new cfs("MTHI", cfs.E, cfn.pC, cfn.WR),
      new cfs("MFLO", cfs.E, cfn.ys, cfn.fI),
      new cfs("MTLO", cfs.E, cfn.pC, cfn.WR)
   };
   static final cfs[] xC = new cfs[]{
      new cfs("MADD", cfs.E, ZN), new cfs("MADDU", cfs.E, ZN), cfs.pC, cfs.pC, new cfs("MSUB", cfs.E, ZN), new cfs("MSUBU", cfs.E, ZN), cfs.pC, cfs.pC
   };
   static final cfs[] ED = new cfs[]{new cfs("MULT", cfs.E, ZN), new cfs("MULTU", cfs.E, ZN), cfs.pC, cfs.pC, cfs.pC, cfs.pC, cfs.pC, cfs.pC};
   public static final cfs[] Sc = new cfs[]{
      new cfs("ADDU.OB", Er, cfn.ah),
      new cfs("SUBU.OB", Er, cfn.ah),
      cfs.pC,
      cfs.pC,
      new cfs("ADDU_S.OB", Er, cfn.ah),
      new cfs("SUBU_S.OB", Er, cfn.ah),
      new cfs("MULEU_S.QH.OBL", Er, cfn.ah),
      new cfs("MULEU_S.QH.OBR", Er, cfn.ah),
      new cfs("ADDU.QH", FE, cfn.ah),
      new cfs("SUBU.QH", FE, cfn.ah),
      new cfs("ADDQ.QH", Er, cfn.ah),
      new cfs("SUBQ.QH", Er, cfn.ah),
      new cfs("ADDU_S.QH", FE, cfn.ah),
      new cfs("SUBU_S.QH", FE, cfn.ah),
      new cfs("ADDQ_S.QH", Er, cfn.ah),
      new cfs("SUBQ_S.QH", Er, cfn.ah),
      cfs.pC,
      cfs.pC,
      new cfs("ADDQ.PW", Er, cfn.ah),
      new cfs("SUBQ.PW", Er, cfn.ah),
      new cfs("RADDU.L.OB", Er, mv),
      cfs.pC,
      new cfs("ADDQ_S.PW", Er, cfn.ah),
      new cfs("SUBQ_S.PW", Er, cfn.ah),
      new cfs("ADDUH.OB", FE, cfn.ah),
      new cfs("SUBUH.OB", FE, cfn.ah),
      new cfs("ADDUH_R.OB", FE, cfn.ah),
      new cfs("SUBUH_R.OB", FE, cfn.ah),
      new cfs("MULEQ_S.PW.QHL", Er, cfn.ah),
      new cfs("MULEQ_S.PW.QHR", Er, cfn.ah),
      cfs.pC,
      new cfs("MULQ_RS.QH", Er, cfn.ah)
   };
   public static final cfs[] ah = new cfs[]{
      new cfs("CMPU.EQ.OB", Er, cfn.ED),
      new cfs("CMPU.LT.OB", Er, cfn.ED),
      new cfs("CMPU.LE.OB", Er, cfn.ED),
      new cfs("PICK.OB", Er, cfn.ah),
      new cfs("CMPGU.EQ.OB", Er, cfn.ah),
      new cfs("CMPGU.LT.OB", Er, cfn.ah),
      new cfs("CMPGU.LE.OB", Er, cfn.ah),
      cfs.pC,
      new cfs("CMP.EQ.QH", Er, cfn.ED),
      new cfs("CMP.LT.QH", Er, cfn.ED),
      new cfs("CMP.LE.QH", Er, cfn.ED),
      new cfs("PICK.QH", Er, cfn.ah),
      new cfs("PRECRQ.OB.QH", Er, cfn.ah),
      new cfs("PRECR.OB.QH", FE, cfn.ah),
      new cfs("PACKRL.PW", Er, cfn.ah),
      new cfs("PRECRQU_S.OB.QH", Er, cfn.ah),
      new cfs("CMP.EQ.PW", Er, cfn.ED),
      new cfs("CMP.LT.PW", Er, cfn.ED),
      new cfs("CMP.LE.PW", Er, cfn.ED),
      new cfs("PICK.PW", Er, cfn.ah),
      new cfs("PRECRQ.QH.PW", Er, cfn.ah),
      new cfs("PRECRQ_RS.QH.PW", Er, cfn.ah),
      cfs.pC,
      cfs.pC,
      new cfs("CMPGDU.EQ.OB", FE, cfn.ah),
      new cfs("CMPGDU.LT.OB", FE, cfn.ah),
      new cfs("CMPGDU.LE.OB", FE, cfn.ah),
      cfs.pC,
      new cfs("PRECRQ.PW.L", Er, cfn.ah),
      cfs.pC,
      new cfs("PRECR_SRA.QH.PW", FE, sO),
      new cfs("PRECR_SRA_R.QH.PW", FE, sO)
   };
   public static final cfs[] eP = new cfs[]{
      cfs.pC,
      new cfs("ABSQ_S.OB", FE, os),
      new cfs("REPL.OB", Er, hZ),
      new cfs("REPLV.OB", Er, os),
      new cfs("PRECEQU.QH.OBL", Er, os),
      new cfs("PRECEQU.QH.OBR", Er, os),
      new cfs("PRECEQU.QH.OBLA", Er, os),
      new cfs("PRECEQU.QH.OBRA", Er, os),
      cfs.pC,
      new cfs("ABSQ_S.QH", Er, os),
      new cfs("REPL.QH", Er, Cu),
      new cfs("REPLV.QH", Er, os),
      new cfs("PRECEQ.PW.QHL", Er, os),
      new cfs("PRECEQ.PW.QHR", Er, os),
      new cfs("PRECEQ.PW.QHLA", Er, os),
      new cfs("PRECEQ.PW.QHRA", Er, os),
      cfs.pC,
      new cfs("ABSQ_S.PW", Er, os),
      new cfs("REPL.PW", Er, Cu),
      new cfs("REPLV.PW", Er, os),
      new cfs("PRECEQ.L.PWL", Er, os),
      new cfs("PRECEQ.L.PWR", Er, os),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      new cfs("PRECEU.QH.OBL", Er, os),
      new cfs("PRECEU.QH.OBR", Er, os),
      new cfs("PRECEU.QH.OBLA", Er, os),
      new cfs("PRECEU.QH.OBRA", Er, os)
   };
   public static final cfs[] UO = new cfs[]{
      new cfs("SHLL.OB", Er, PR),
      new cfs("SHRL.OB", Er, PR),
      new cfs("SHLLV.OB", Er, DQ),
      new cfs("SHRLV.OB", Er, DQ),
      new cfs("SHRA.OB", FE, PR),
      new cfs("SHRA_R.OB", FE, PR),
      new cfs("SHRAV.OB", FE, DQ),
      new cfs("SHRAV_R.OB", FE, DQ),
      new cfs("SHLL.QH", Er, UW),
      new cfs("SHRA.QH", Er, UW),
      new cfs("SHLLV.QH", Er, DQ),
      new cfs("SHRAV.QH", Er, DQ),
      new cfs("SHLL_S.QH", Er, UW),
      new cfs("SHRA_R.QH", Er, UW),
      new cfs("SHLLV_S.QH", Er, DQ),
      new cfs("SHRAV_R.QH", Er, DQ),
      new cfs("SHLL.PW", Er, cX),
      new cfs("SHRA.PW", Er, cX),
      new cfs("SHLLV.PW", Er, DQ),
      new cfs("SHRAV.PW", Er, DQ),
      new cfs("SHLL_S.PW", Er, cX),
      new cfs("SHRA_R.PW", Er, cX),
      new cfs("SHLLV_S.PW", Er, DQ),
      new cfs("SHRAV_R.PW", Er, DQ),
      cfs.pC,
      new cfs("SHRL.QH", FE, UW),
      cfs.pC,
      new cfs("SHRLV.QH", FE, DQ),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC
   };
   public static final cfs[] Ab = new cfs[]{
      new cfs("DPA.W.QH", FE, ZN),
      new cfs("DPS.W.QH", FE, ZN),
      cfs.pC,
      new cfs("DPAU.H.OBL", Er, ZN),
      new cfs("DPAQ_S.W.QH", Er, ZN),
      new cfs("DPSQ_S.W.QH", Er, ZN),
      new cfs("MULSAQ_S.W.QH", Er, ZN),
      new cfs("DPAU.H.OBR", Er, ZN),
      new cfs("DPAX.W.QH", FE, ZN),
      new cfs("DPSX.W.QH", FE, ZN),
      cfs.pC,
      new cfs("DPSU.H.OBL", Er, ZN),
      new cfs("DPAQ_SA.L.PW", Er, ZN),
      new cfs("DPSQ_SA.L.PW", Er, ZN),
      new cfs("MULSAQ_S.L.PW", Er, ZN),
      new cfs("DPSU.H.OBR", Er, ZN),
      new cfs("MAQ_SA.W.QHLL", Er, ZN),
      new cfs("MAQ_SA.W.QHLR", Er, ZN),
      new cfs("MAQ_SA.W.QHRL", Er, ZN),
      new cfs("MAQ_SA.W.QHRR", Er, ZN),
      new cfs("MAQ_S.W.QHLL", Er, ZN),
      new cfs("MAQ_S.W.QHLR", Er, ZN),
      new cfs("MAQ_S.W.QHRL", Er, ZN),
      new cfs("MAQ_S.W.QHRR", Er, ZN),
      cfs.pC,
      new cfs("DMADD", Er, ZN),
      cfs.pC,
      new cfs("DMSUB", Er, ZN),
      new cfs("MAQ_S.L.PWL", Er, ZN),
      new cfs("DMADDU", Er, ZN),
      new cfs("MAQ_S.L.PWR", Er, ZN),
      new cfs("DMSUBU", Er, ZN)
   };
   public static final cfs[] rl = new cfs[]{
      new cfs("DAPPEND", hK, sO),
      new cfs("PREPENDW", hK, sO),
      cfs.pC,
      new cfs("PREPENDD", hK, sO),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      new cfs("DBALIGN", hK, cfn.kS, cfn.pC, cfl.mv),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC,
      cfs.pC
   };
   public static final cfs[] z = new cfs[]{
      new cfs("DEXTR.W", Er, OB),
      new cfs("DEXTRV.W", Er, pF),
      new cfs("DEXTP", Er, OB),
      new cfs("DEXTPV", Er, pF),
      new cfs("DEXTR_R.W", Er, OB),
      new cfs("DEXTRV_R.W", Er, pF),
      new cfs("DEXTR_RS.W", Er, OB),
      new cfs("DEXTRV_RS.W", Er, pF),
      cfs.pC,
      cfs.pC,
      new cfs("DEXTPDP", Er, OB),
      new cfs("DEXTPDPV", Er, pF),
      cfs.pC,
      cfs.pC,
      new cfs("DEXTR_S.H", Er, OB),
      new cfs("DEXTRV_S.H", Er, pF),
      new cfs("DEXTR.L", Er, OB),
      new cfs("DEXTRV.L", Er, pF),
      cfs.pC,
      cfs.pC,
      new cfs("DEXTR_R.L", Er, OB),
      new cfs("DEXTRV_R.L", Er, pF),
      new cfs("DEXTR_RS.L", Er, OB),
      new cfs("DEXTRV_RS.L", Er, pF),
      cfs.pC,
      cfs.pC,
      new cfs("DSHILO", Er, cfn.WR, cfl.os),
      new cfs("DSHILOV", Er, cfn.WR, cfn.pC),
      cfs.pC,
      cfs.pC,
      cfs.pC,
      new cfs("DMTHLIP", Er, Bc)
   };
}
