package com.pnfsoftware.jeb.util.format;

import com.pnfsoftware.jeb.client.AbstractContext;

public class HtmlFormatter {
   public static CharSequence generate(CharSequence var0, CharSequence var1, CharSequence var2, boolean var3) {
      if (var3) {
         StringBuilder var4 = new StringBuilder();
         var4.append("<h4>Generated by <a href=\"")
            .append("https://www.pnfsoftware.com")
            .append("\">JEB</a> v")
            .append(AbstractContext.app_ver)
            .append("</h4>")
            .append("\n");
         var2 = var4.append((CharSequence)var2);
      }

      StringBuilder var5 = new StringBuilder();
      var5.append("Generated by JEB v").append(AbstractContext.app_ver).append(" - ").append("https://www.pnfsoftware.com");
      return generate(var0, var1, (CharSequence)var2, var5);
   }

   public static CharSequence generate(CharSequence var0, CharSequence var1, CharSequence var2, CharSequence var3) {
      StringBuilder var4 = new StringBuilder();
      var4.append("<!DOCTYPE html>\n");
      var4.append("<html>\n\n");
      var4.append("<head>\n");
      var4.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      if (var0 != null) {
         var4.append("<title>").append(var0).append("</title>\n");
      }

      if (var1 != null) {
         var4.append("<style>\n").append(var1).append("</style>\n");
      }

      var4.append("</head>\n\n");
      var4.append("<body>\n");
      var4.append(var2).append("\n");
      var4.append("</body>\n\n");
      if (var3 != null) {
         var4.append("<!-- ").append(var3).append(" -->\n");
      }

      var4.append("</html>\n");
      return var4;
   }
}
