package com.pnfsoftware.jeb.core.units.code.asm.decompiler.ast.simulator;

import com.pnfsoftware.jeb.core.units.INativeCodeUnit;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ast.CIdentifierClass;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ast.ICIdentifier;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ast.ICMethod;
import com.pnfsoftware.jeb.core.units.code.asm.decompiler.ast.ICType;
import com.pnfsoftware.jeb.core.units.code.asm.memory.MemoryException;
import com.pnfsoftware.jeb.core.units.code.asm.type.INativeType;
import com.pnfsoftware.jeb.core.units.code.asm.type.ITypeManager;
import com.pnfsoftware.jeb.util.base.Assert;
import com.pnfsoftware.jeb.util.format.Strings;
import com.pnfsoftware.jeb.util.io.Endianness;
import java.nio.ByteBuffer;
import java.util.HashMap;
import java.util.Map;

public class CEnvironment {
   private static final long ROUTINE_CALL_DEFAULT_RETURN_VALUE = 7L;
   private static final long ARGUMENT_DEFAULT_VALUE = 13L;
   private Map parameterValues = new HashMap();
   private Map rtnReturnValues = new HashMap();
   private Map memoryAddress = new HashMap();
   private INativeCodeUnit nativeUnit;
   private ITypeManager typeManager;
   private Endianness endianness;
   private Integer defaultPointedSize;
   private boolean autoGenerateUndefinedIdentifierValue;
   private long routinePassedParametersValue = 13L;
   private Map dummyWrittenMemory = new HashMap();
   private Map globalVarValues = new HashMap();

   public CEnvironment(INativeCodeUnit var1) {
      if (var1 != null) {
         this.nativeUnit = var1;
         this.endianness = var1.getProcessor().getEndianness();
         this.typeManager = var1.getTypeManager();
      }
   }

   public static CEnvironment copy(CEnvironment var0) {
      CEnvironment var1 = new CEnvironment(var0.nativeUnit);
      var1.nativeUnit = var0.nativeUnit;
      var1.endianness = var0.endianness;
      var1.typeManager = var0.typeManager;
      var1.parameterValues = var0.parameterValues;
      var1.rtnReturnValues = var0.rtnReturnValues;
      var1.defaultPointedSize = var0.defaultPointedSize;
      var1.autoGenerateUndefinedIdentifierValue = var0.autoGenerateUndefinedIdentifierValue;
      var1.globalVarValues = new HashMap(var0.globalVarValues);
      var1.dummyWrittenMemory = new HashMap(var0.dummyWrittenMemory);
      return var1;
   }

   public int getBaseTypeSize(ICType var1) {
      String var2 = var1.getSignature();
      if (var2.endsWith("*")) {
         INativeType var3 = this.typeManager.getType(var1.getBaseTypeSignature());
         if (var3 == null) {
            throw new CSimulationException(Strings.ff("unknown base type (%s)", var2));
         } else {
            return var3.getSize();
         }
      } else if (this.defaultPointedSize != null) {
         return this.defaultPointedSize;
      } else {
         throw new CSimulationException(Strings.ff("not a pointer type (%s)", var2));
      }
   }

   public int getTypeSize(ICType var1) {
      String var2 = var1.getSignature();
      INativeType var3 = this.typeManager.getType(var2);
      if (var3 == null) {
         throw new CSimulationException(Strings.ff("unknown type (%s)", var2));
      } else {
         return var3.getSize();
      }
   }

   public void setParameterValue(ICIdentifier var1, long var2) {
      this.parameterValues.put(var1.getName(), var2);
   }

   public void setAutoGeneratedParameterValue(ICIdentifier var1) {
      this.parameterValues.put(var1.getName(), this.generateParameterValue(var1.getType()));
   }

   public boolean isParameterValueSet(ICIdentifier var1) {
      return this.parameterValues.containsKey(var1.getName());
   }

   public Long getParameterValue(ICIdentifier var1) {
      return this.getParameterValue(var1, this.autoGenerateUndefinedIdentifierValue);
   }

   public Long getParameterValue(ICIdentifier var1, boolean var2) {
      Long var3 = (Long)this.parameterValues.get(var1.getName());
      if (var3 == null && var2) {
         this.setAutoGeneratedParameterValue(var1);
         var3 = (Long)this.parameterValues.get(var1.getName());
      }

      return var3;
   }

   private Long generateParameterValue(ICType var1) {
      return 13L;
   }

   public void setRoutineReturnValue(ICMethod var1, long var2) {
      this.rtnReturnValues.put(var1.getName(), var2);
   }

   public void setAutoGeneratedRoutineReturnValue(ICMethod var1) {
      String var2 = var1.getName();
      this.rtnReturnValues.put(var2, this.generateRoutineReturnValue(var2));
   }

   public Long getRoutineReturnValue(ICMethod var1, boolean var2) {
      String var3 = var1.getName();
      Long var4 = (Long)this.rtnReturnValues.get(var3);
      if (var4 == null && var2) {
         this.setAutoGeneratedRoutineReturnValue(var1);
         var4 = (Long)this.rtnReturnValues.get(var3);
      }

      return var4;
   }

   public Long getRoutineDefaultReturnValue() {
      return 7L;
   }

   private Long generateRoutineReturnValue(String var1) {
      return this.getRoutineDefaultReturnValue();
   }

   public void setGlobalVarValue(ICIdentifier var1, long var2) {
      this.globalVarValues.put(var1.getAddress(), var2);
   }

   public Long getGlobalVarValue(ICIdentifier var1, boolean var2) {
      Assert.a(var1.getIdentifierClass() == CIdentifierClass.GLOBAL);
      long var3 = var1.getAddress();
      Long var5 = (Long)this.globalVarValues.get(var3);
      if (var5 == null && var2) {
         var5 = this.readMemory(var3, this.getTypeSize(var1.getType()));
         this.globalVarValues.put(var3, var5);
      }

      return var5;
   }

   public void writeMemory(long var1, long var3) {
      this.dummyWrittenMemory.put(var1, var3);
   }

   public Long readMemory(long var1, int var3) {
      Long var4 = (Long)this.dummyWrittenMemory.get(var1);
      if (var4 != null) {
         return var4;
      } else {
         Long.valueOf(0L);
         byte[] var5 = new byte[var3];

         try {
            this.nativeUnit.getMemory().read(var1, var3, var5, 0);

            return switch (var3) {
               case 4 -> ByteBuffer.wrap(var5).order(this.endianness.toByteOrder()).getInt() & 4294967295L;
               case 8 -> ByteBuffer.wrap(var5).order(this.endianness.toByteOrder()).getLong();
               default -> throw new CSimulationException(Strings.ff("TBI: global var size (%d)", var3));
            };
         } catch (MemoryException var6) {
            throw new CSimulationException("error when reading gvar value");
         }
      }
   }

   public void setVarAddress(ICIdentifier var1, long var2) {
      this.memoryAddress.put(var1.getName(), var2);
   }

   public Long getVarAddress(ICIdentifier var1) {
      String var2 = var1.getName();
      Long var3 = (Long)this.memoryAddress.get(var2);
      if (var3 == null) {
         if (var1.getIdentifierClass() != CIdentifierClass.LOCAL && var1.getIdentifierClass() != CIdentifierClass.GLOBAL) {
            throw new CSimulationException(Strings.ff("TBI: get address for var (%s)", var1));
         }

         var3 = var1.getAddress();
         this.memoryAddress.put(var2, var3);
      }

      return var3;
   }

   public Integer getDefaultPointedSize() {
      return this.defaultPointedSize;
   }

   public void setDefaultPointedSize(Integer var1) {
      this.defaultPointedSize = var1;
   }

   public boolean isAutoGenerateUndefinedIdentifierValue() {
      return this.autoGenerateUndefinedIdentifierValue;
   }

   public void setAutoGenerateUndefinedIdentifierValue(boolean var1) {
      this.autoGenerateUndefinedIdentifierValue = var1;
   }

   public long getPassedParameterValue(ICIdentifier var1) {
      this.routinePassedParametersValue *= 2L;
      return this.routinePassedParametersValue;
   }

   public static boolean areEquivalent(CEnvironment var0, CEnvironment var1) {
      return !var0.dummyWrittenMemory.equals(var1.dummyWrittenMemory) ? false : var0.globalVarValues.equals(var1.globalVarValues);
   }

   public void clearState() {
      this.dummyWrittenMemory.clear();
      this.globalVarValues.clear();
   }

   @Override
   public String toString() {
      return "CEnvironment [dummyWrittenMemory=" + this.dummyWrittenMemory + ", globalVarValues=" + this.globalVarValues + "]";
   }
}
