package com.pnfsoftware.jeb.core.output.text;

import com.pnfsoftware.jeb.client.AbstractContext;
import com.pnfsoftware.jeb.client.S;
import com.pnfsoftware.jeb.core.output.ItemClassIdentifiers;
import java.util.HashMap;
import java.util.Map;

public class HtmlFormatter {
   private ITextDocument doc;
   private IItemStyleInfoProvider styleprv;
   private String titledata;
   private String bodytitledata;
   private String commentdata;
   private StringBuilder cssdata;
   private Map styleidToDivclassname = new HashMap();

   public HtmlFormatter(ITextDocument var1, IItemStyleInfoProvider var2, String var3, boolean var4) {
      this.doc = var1;
      this.styleprv = var2;
      this.titledata = this.replaceHtmlChars(var3);
      String var5 = S.L("Generated by");
      this.commentdata = String.format("%s JEB v%s - %s", var5, AbstractContext.app_ver, "https://www.pnfsoftware.com");
      this.bodytitledata = "";
      if (var4) {
         this.bodytitledata = String.format("<h4>%s <a href=\"%s\">JEB</a> v%s</h4>", var5, "https://www.pnfsoftware.com", AbstractContext.app_ver);
      }

      this.cssdata = new StringBuilder("div {\n  display: inline-block;\n  margin:0;\n  padding:0;\n  border:0;\n}\n");
   }

   public String generate() {
      StringBuilder var1 = new StringBuilder("<pre>\n");
      ITextDocumentPart var2 = this.doc.getDocumentPart(this.doc.getFirstAnchor(), Integer.MAX_VALUE);

      for (ILine var4 : var2.getLines()) {
         CharSequence var5 = var4.getText();
         int var6 = 0;

         for (ITextItem var8 : var4.getItems()) {
            int var9 = var8.getOffset();
            int var10 = var8.getOffsetEnd();
            if (var9 > var6) {
               var1.append(this.replaceHtmlChars(var5.subSequence(var6, var9)));
               var6 = var9;
            }

            var1.append(String.format("<div class=\"%s\">%s</div>", this.generateCssDivStyle(var8), this.replaceHtmlChars(var5.subSequence(var6, var10))));
            var6 = var10;
         }

         if (var6 < var5.length()) {
            var1.append(this.replaceHtmlChars(var5.subSequence(var6, var5.length())));
         }

         var1.append('\n');
      }

      var1.append("</pre>\n");
      return String.format(
         "<html>\n\n<head>\n<title>%s</title>\n<style type=\"text/css\">\n%s</style>\n</head>\n\n<body>\n%s\n%s\n</body>\n\n<!-- %s -->\n</html>\n",
         this.titledata,
         this.cssdata,
         this.bodytitledata,
         var1,
         this.commentdata
      );
   }

   private String generateCssDivStyle(ITextItem var1) {
      ItemClassIdentifiers var2 = ItemClassIdentifiers.DEFAULT;
      if (var1 instanceof IVisualTextItem) {
         var2 = ((IVisualTextItem)var1).getClassId();
      }

      String var3 = (String)this.styleidToDivclassname.get(var2);
      if (var3 != null) {
         return var3;
      } else {
         StyleInfo var4 = this.styleprv.getStyle(var2);
         if (var4 == null) {
            return "";
         } else {
            String var5 = "s_" + var2.toString().toLowerCase();
            StringBuilder var6 = new StringBuilder(String.format(".%s {\n", var5));
            if (var4.getForegroundColor() != null) {
               var6.append(String.format("  color: #%06X;\n", var4.getForegroundColor()));
            }

            if (var4.getBackgroundColor() != null) {
               var6.append(String.format("  background-color: #%06X;\n", var4.getBackgroundColor()));
            }

            if (Boolean.TRUE.equals(var4.getBold())) {
               var6.append("  font-weight: bold;\n");
            }

            if (Boolean.TRUE.equals(var4.getItalic())) {
               var6.append("  font-style: italic;\n");
            }

            var6.append("}\n");
            this.cssdata.append((CharSequence)var6);
            this.styleidToDivclassname.put(var2, var5);
            return var5;
         }
      }
   }

   private String replaceHtmlChars(CharSequence var1) {
      StringBuilder var2 = new StringBuilder();

      for (int var3 = 0; var3 < var1.length(); var3++) {
         char var4 = var1.charAt(var3);
         if (var4 == '&') {
            var2.append("&amp;");
         } else if (var4 == '"') {
            var2.append("&quot;");
         } else if (var4 == '\'') {
            var2.append("&#039;");
         } else if (var4 == '<') {
            var2.append("&lt;");
         } else if (var4 == '>') {
            var2.append("&gt;");
         } else {
            var2.append(var4);
         }
      }

      return var2.toString();
   }
}
