package com.pnfsoftware.jeb.corei.parsers.sass;

import com.pnfsoftware.jeb.core.units.code.asm.processor.RegisterDescriptionEntry;
import com.pnfsoftware.jeb.core.units.code.asm.processor.arch.AbstractRegisterBank2;

public class p extends AbstractRegisterBank2 {
   public static final String[] pC = new String[]{
      "SR_LANEID",
      "SR_CLOCK",
      "SR_VIRTCFG",
      "SR_VIRTID",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "SR_ORDERING_TICKET",
      "SR_PRIM_TYPE",
      "SR_INVOCATION_ID",
      "SR_Y_DIRECTION",
      "SR_THREAD_KILL",
      "SM_SHADER_TYPE",
      "SR_DIRECTCBEWRITEADDRESSLOW",
      "SR_DIRECTCBEWRITEADDRESSHIGH",
      "SR_DIRECTCBEWRITEENABLED",
      "SR_MACHINE_ID_0",
      "SR_MACHINE_ID_1",
      "SR_MACHINE_ID_2",
      "SR_MACHINE_ID_3",
      "SR_AFFINITY",
      "SR_INVOCATION_INFO",
      "SR_WSCALEFACTOR_XY",
      "SR_WSCALEFACTOR_Z",
      "SR_TID",
      "SR_TID.X",
      "SR_TID.Y",
      "SR_TID.Z",
      null,
      "SR_CTAID.X",
      "SR_CTAID.Y",
      "SR_CTAID.Z",
      "SR_NTID",
      "SR_CirQueueIncrMinusOne",
      "SR_NLATC",
      null,
      "SR_SM_SPA_VERSION",
      "SR_MULTIPASSSHADERINFO",
      "SR_LWINHI",
      "SR_SWINHI",
      "SR_SWINLO",
      "SR_SWINSZ",
      "SR_SMEMSZ",
      "SR_SMEMBANKS",
      "SR_LWINLO",
      "SR_LWINSZ",
      "SR_LMEMLOSZ",
      "SR_LMEMHIOFF",
      "SR_EQMASK",
      "SR_LTMASK",
      "SR_LEMASK",
      "SR_GTMASK",
      "SR_GEMASK",
      "SR_REGALLOC",
      "SR_BARRIERALLOC",
      null,
      "SR_GLOBALERRORSTATUS",
      "SR_CGAERRORSTATUS",
      "SR_WARPERRORSTATUS",
      "SR_VIRTUALSMID",
      "SR_VIRTUALENGINEID",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "SR_CLOCKLO",
      "SR_CLOCKHI",
      "SR_GLOBALTIMERLO",
      "SR_GLOBALTIMERHI",
      "SR_ESR_PC",
      "SR_ESR_PC_HI",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "SR_HWTASKID",
      "SR_CIRCULARQUEUEENTRYINDEX",
      "SR_CIRCULARQUEUEENTRYADDRESSLOW",
      "SR_CIRCULARQUEUEENTRYADDRESSHIGH",
      "SR_PM0",
      "SR_PM_HI0",
      "SR_PM1",
      "SR_PM_HI1",
      "SR_PM2",
      "SR_PM_HI2",
      "SR_PM3",
      "SR_PM_HI3",
      "SR_PM4",
      "SR_PM_HI4",
      "SR_PM5",
      "SR_PM_HI5",
      "SR_PM6",
      "SR_PM_HI6",
      "SR_PM7",
      "SR_PM_HI7",
      "SR_SNAP_PM0",
      "SR_SNAP_PM_HI0",
      "SR_SNAP_PM1",
      "SR_SNAP_PM_HI1",
      "SR_SNAP_PM2",
      "SR_SNAP_PM_HI2",
      "SR_SNAP_PM3",
      "SR_SNAP_PM_HI3",
      "SR_SNAP_PM4",
      "SR_SNAP_PM_HI4",
      "SR_SNAP_PM5",
      "SR_SNAP_PM_HI5",
      "SR_SNAP_PM6",
      "SR_SNAP_PM_HI6",
      "SR_SNAP_PM7",
      "SR_SNAP_PM_HI7",
      "SR_VARIABLE_RATE",
      "SR_TTU_TICKET_INFO",
      "SR_WARPGROUP_INFO",
      "SR_WARPGROUPID",
      "SR_CgaCtaId",
      "SR_GpcLocalCgaId",
      "SR_CgaLinearMemorySlot",
      "SR_CTARegPoolSz",
      null,
      "SR_TMem",
      "SR_CONTEXT_SAVE_ADDR_LO",
      "SR_CONTEXT_SAVE_ADDR_HI",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "SRZ"
   };
   final int A = 256;
   final int kS = 8;
   final int wS = 256;
   final int UT = 8;
   final int E = 64;
   final int sY = 256;
   private static final String[] ys = new String[]{
      "SR_LANEID",
      "Lane index within warp (0–31)",
      "SR_CLOCK",
      "SM cycle counter (legacy 32-bit)",
      "SR_VIRTCFG",
      "Virtualization/config profile id (internal)",
      "SR_VIRTID",
      "Virtual engine/partition id (MIG/virt)",
      "SR_ORDERING_TICKET",
      "Per-warp scheduling/ordering ticket (internal)",
      "SR_PRIM_TYPE",
      "Graphics primitive type (tri/line/point)",
      "SR_INVOCATION_ID",
      "Shader invocation index (graphics)",
      "SR_Y_DIRECTION",
      "Framebuffer Y direction flag (graphics)",
      "SR_THREAD_KILL",
      "Per-thread kill/discard state (graphics)",
      "SM_SHADER_TYPE",
      "Shader stage type (graphics)",
      "SR_DIRECTCBEWRITEADDRESSLOW",
      "Direct CBE write address low (internal)",
      "SR_DIRECTCBEWRITEADDRESSHIGH",
      "Direct CBE write address high (internal)",
      "SR_DIRECTCBEWRITEENABLED",
      "Direct CBE write enable (internal)",
      "SR_MACHINE_ID_0",
      "Chip/SM machine id (part 0)",
      "SR_MACHINE_ID_1",
      "Chip/SM machine id (part 1)",
      "SR_MACHINE_ID_2",
      "Chip/SM machine id (part 2)",
      "SR_MACHINE_ID_3",
      "Chip/SM machine id (part 3)",
      "SR_AFFINITY",
      "SM/partition affinity hints (internal)",
      "SR_INVOCATION_INFO",
      "Extra invocation info/state (graphics)",
      "SR_WSCALEFACTOR_XY",
      "Viewport scale factor XY (graphics)",
      "SR_WSCALEFACTOR_Z",
      "Viewport scale factor Z (graphics)",
      "SR_TID",
      "Thread index packed (x,y,z)",
      "SR_TID.X",
      "threadIdx.x",
      "SR_TID.Y",
      "threadIdx.y",
      "SR_TID.Z",
      "threadIdx.z",
      "SR_CTAID.X",
      "blockIdx.x",
      "SR_CTAID.Y",
      "blockIdx.y",
      "SR_CTAID.Z",
      "blockIdx.z",
      "SR_NTID",
      "Block dimensions packed",
      "SR_CirQueueIncrMinusOne",
      "Circular queue increment-1 (internal)",
      "SR_NLATC",
      "NLATC status/flag (undocumented)",
      "SR_SM_SPA_VERSION",
      "Shader processor arch version",
      "SR_MULTIPASSSHADERINFO",
      "Multipass shader metadata (graphics)",
      "SR_LWINHI",
      "Local mem window base high (internal)",
      "SR_SWINHI",
      "Shared mem window base high (internal)",
      "SR_SWINLO",
      "Shared mem window base low (internal)",
      "SR_SWINSZ",
      "Shared mem window size (bytes)",
      "SR_SMEMSZ",
      "Shared memory size available",
      "SR_SMEMBANKS",
      "Shared mem bank count/layout",
      "SR_LWINLO",
      "Local mem window base low (internal)",
      "SR_LWINSZ",
      "Local mem window size (bytes)",
      "SR_LMEMLOSZ",
      "Local memory size (low)",
      "SR_LMEMHIOFF",
      "Local memory high offset",
      "SR_EQMASK",
      "Warp mask: equal lane",
      "SR_LTMASK",
      "Warp mask: less-than lanes",
      "SR_LEMASK",
      "Warp mask: less-than or equal lanes",
      "SR_GTMASK",
      "Warp mask: greater-than lanes",
      "SR_GEMASK",
      "Warp mask: greater-than or equal lanes",
      "SR_REGALLOC",
      "Registers allocated per thread",
      "SR_BARRIERALLOC",
      "Named barrier slots allocated",
      "SR_GLOBALERRORSTATUS",
      "Global error/exception status",
      "SR_CGAERRORSTATUS",
      "Cluster/CGA error status",
      "SR_WARPERRORSTATUS",
      "Warp error/exception status",
      "SR_VIRTUALSMID",
      "Virtual SM identifier",
      "SR_VIRTUALENGINEID",
      "Virtual engine id",
      "SR_CLOCKLO",
      "SM clock low 32-bits",
      "SR_CLOCKHI",
      "SM clock high 32-bits",
      "SR_GLOBALTIMERLO",
      "Global timer low 32-bits",
      "SR_GLOBALTIMERHI",
      "Global timer high 32-bits",
      "SR_ESR_PC",
      "Exception/ESR saved PC (low)",
      "SR_ESR_PC_HI",
      "Exception/ESR saved PC (high)",
      "SR_HWTASKID",
      "Hardware task identifier",
      "SR_CIRCULARQUEUEENTRYINDEX",
      "Circular queue entry index",
      "SR_CIRCULARQUEUEENTRYADDRESSLOW",
      "Circular queue entry addr low",
      "SR_CIRCULARQUEUEENTRYADDRESSHIGH",
      "Circular queue entry addr high",
      "SR_PM0",
      "Perf counter 0 (low)",
      "SR_PM_HI0",
      "Perf counter 0 (high)",
      "SR_PM1",
      "Perf counter 1 (low)",
      "SR_PM_HI1",
      "Perf counter 1 (high)",
      "SR_PM2",
      "Perf counter 2 (low)",
      "SR_PM_HI2",
      "Perf counter 2 (high)",
      "SR_PM3",
      "Perf counter 3 (low)",
      "SR_PM_HI3",
      "Perf counter 3 (high)",
      "SR_PM4",
      "Perf counter 4 (low)",
      "SR_PM_HI4",
      "Perf counter 4 (high)",
      "SR_PM5",
      "Perf counter 5 (low)",
      "SR_PM_HI5",
      "Perf counter 5 (high)",
      "SR_PM6",
      "Perf counter 6 (low)",
      "SR_PM_HI6",
      "Perf counter 6 (high)",
      "SR_PM7",
      "Perf counter 7 (low)",
      "SR_PM_HI7",
      "Perf counter 7 (high)",
      "SR_SNAP_PM0",
      "Snapshot perf counter 0 (low)",
      "SR_SNAP_PM_HI0",
      "Snapshot perf counter 0 (high)",
      "SR_SNAP_PM1",
      "Snapshot perf counter 1 (low)",
      "SR_SNAP_PM_HI1",
      "Snapshot perf counter 1 (high)",
      "SR_SNAP_PM2",
      "Snapshot perf counter 2 (low)",
      "SR_SNAP_PM_HI2",
      "Snapshot perf counter 2 (high)",
      "SR_SNAP_PM3",
      "Snapshot perf counter 3 (low)",
      "SR_SNAP_PM_HI3",
      "Snapshot perf counter 3 (high)",
      "SR_SNAP_PM4",
      "Snapshot perf counter 4 (low)",
      "SR_SNAP_PM_HI4",
      "Snapshot perf counter 4 (high)",
      "SR_SNAP_PM5",
      "Snapshot perf counter 5 (low)",
      "SR_SNAP_PM_HI5",
      "Snapshot perf counter 5 (high)",
      "SR_SNAP_PM6",
      "Snapshot perf counter 6 (low)",
      "SR_SNAP_PM_HI6",
      "Snapshot perf counter 6 (high)",
      "SR_SNAP_PM7",
      "Snapshot perf counter 7 (low)",
      "SR_SNAP_PM_HI7",
      "Snapshot perf counter 7 (high)",
      "SR_VARIABLE_RATE",
      "Variable-rate shading state (graphics)",
      "SR_TTU_TICKET_INFO",
      "TTU ticket/state (internal)",
      "SR_WARPGROUP_INFO",
      "Warp-group state (Hopper+)",
      "SR_WARPGROUPID",
      "Warp-group identifier (Hopper+)",
      "SR_CgaCtaId",
      "CTA id within CGA/cluster (internal)",
      "SR_GpcLocalCgaId",
      "Local CGA id within GPC (internal)",
      "SR_CgaLinearMemorySlot",
      "CGA linear memory slot (internal)",
      "SR_CTARegPoolSz",
      "CTA register pool size",
      "SR_TMem",
      "TMem state (tile/thread memory; internal)",
      "SR_CONTEXT_SAVE_ADDR_LO",
      "Context save address low",
      "SR_CONTEXT_SAVE_ADDR_HI",
      "Context save address high",
      "SRZ",
      "Zero register (reads 0, write-ignored)"
   };

   public p() {
      for (int var1 = 0; var1 < 256; var1++) {
         RegisterDescriptionEntry var2 = add(this.entries, 32, "R" + var1).grp(0, var1);
         if (var1 == 255) {
            var2.addName("RZ");
         }
      }

      for (int var4 = 0; var4 < 8; var4++) {
         RegisterDescriptionEntry var9 = add(this.entries, 1, "P" + var4).grp(2, var4);
         if (var4 == 7) {
            var9.addName("PT");
         }
      }

      for (int var5 = 0; var5 < 256; var5++) {
         RegisterDescriptionEntry var10 = add(this.entries, 32, "UR" + var5).grp(4, var5);
         if (var5 == 255) {
            var10.addName("URZ");
         }
      }

      for (int var6 = 0; var6 < 8; var6++) {
         RegisterDescriptionEntry var11 = add(this.entries, 1, "UP" + var6).grp(5, var6);
         if (var6 == 7) {
            var11.addName("UPT");
         }
      }

      for (int var7 = 0; var7 < 64; var7++) {
         add(this.entries, 4, "B" + var7).grp(3, var7);
      }

      for (int var8 = 0; var8 < 256; var8++) {
         RegisterDescriptionEntry var12 = add(this.entries, 64, "SR" + var8).grp(1, var8);
         String var3 = pC[var8];
         if (var3 != null) {
            var12.addName(var3);
         }
      }
   }
}
