package com.pnfsoftware.jeb.core.output;

import com.pnfsoftware.jeb.util.base.Assert;
import com.pnfsoftware.jeb.util.logging.GlobalLog;
import com.pnfsoftware.jeb.util.logging.ILogger;
import java.lang.ref.ReferenceQueue;
import java.lang.ref.WeakReference;
import java.util.HashMap;
import java.util.TreeMap;

public class UnitItemIdGenerator {
   private static final ILogger logger = GlobalLog.getLogger(UnitItemIdGenerator.class);
   private ReferenceQueue refQueue = new ReferenceQueue();
   private HashMap map = new HashMap();
   private TreeMap rmap = new TreeMap();

   private void expunge() {
      UnitItemIdGenerator.Ref var1;
      while ((var1 = (UnitItemIdGenerator.Ref)this.refQueue.poll()) != null) {
         Integer var2 = (Integer)this.map.remove(var1);
         Assert.a(var2 != null);
         this.rmap.remove(var2);
      }
   }

   public long generate(Object var1) {
      this.expunge();
      if (var1 == null) {
         return 0L;
      } else {
         UnitItemIdGenerator.Ref var2 = new UnitItemIdGenerator.Ref(var1, this.refQueue);
         Integer var3 = (Integer)this.map.get(var2);
         if (var3 == null) {
            var3 = this.rmap.isEmpty() ? 1 : (Integer)this.rmap.lastKey() + 1;
            this.map.put(var2, var3);
            this.rmap.put(var3, var2);
         }

         Assert.a(var3 != 0, "Too many actionable items were generated by this unit. Thank you for reporting this error.");
         return -144115188075855872L | var3.intValue() & 4294967295L;
      }
   }

   public Object retrieve(long var1) {
      this.expunge();
      if ((var1 & -144115188075855872L) != -144115188075855872L) {
         return null;
      } else {
         Integer var3 = (int)var1;
         UnitItemIdGenerator.Ref var4 = (UnitItemIdGenerator.Ref)this.rmap.get(var3);
         return var4 == null ? null : var4.get();
      }
   }

   private static class Ref extends WeakReference {
      private final int hashCode;

      Ref(Object var1, ReferenceQueue var2) {
         super(var1, var2);
         this.hashCode = var1 == null ? 0 : System.identityHashCode(var1);
      }

      @Override
      public int hashCode() {
         return this.hashCode;
      }

      @Override
      public boolean equals(Object var1) {
         if (this == var1) {
            return true;
         } else if (!(var1 instanceof UnitItemIdGenerator.Ref var2)) {
            return false;
         } else {
            Object var3 = this.get();
            return var3 != null && var3 == var2.get();
         }
      }
   }
}
