package com.pnfsoftware.jeb.core.units.code.asm.items;

import com.pnfsoftware.jeb.core.units.code.ICodeMethod;
import com.pnfsoftware.jeb.core.units.code.asm.type.IClassType;
import com.pnfsoftware.jeb.core.units.code.asm.type.INativeType;
import com.pnfsoftware.jeb.core.units.code.asm.type.IPrototypeItem;
import com.pnfsoftware.jeb.core.units.code.asm.type.IReferenceType;
import com.pnfsoftware.jeb.util.serialization.annotations.Ser;
import java.util.Collection;
import java.util.List;

@Ser
public interface INativeMethodItem extends ICodeMethod, INativeItem {
   boolean isAutoGeneratedPrototype();

   IPrototypeItem getPrototype();

   void setPrototype(IPrototypeItem var1);

   INativeMethodDataItem getData();

   default Long getMemoryAddress() {
      return this.getData() == null ? null : this.getData().getMemoryAddress();
   }

   IClassType getClassType();

   INativeClassItem getClassItem();

   boolean isVirtualMethod();

   INativeType getReturnType();

   @Override
   List getParameterTypes();

   List getParameterNames();

   String getParameterName(int var1);

   void setParameterNames(Collection var1);

   void setParameterName(int var1, String var2);

   IReferenceType getFunctionPointer();

   @Override
   List getInstructions();

   Boolean getNonReturning();

   void setNonReturning(Boolean var1);

   boolean isPlaceholderMethod();

   boolean isDetectedAsLibraryCode();

   String getFinalName();
}
