package com.pnfsoftware.jeb.core.units.code.asm.items;

import com.pnfsoftware.jeb.core.units.code.ICodeItem;
import com.pnfsoftware.jeb.util.serialization.annotations.Ser;
import java.util.Map;

@Ser
public interface INativeItem extends ICodeItem, INativeItemListenable {
   void setFlags(int var1);

   void addFlags(int var1);

   void removeFlags(int var1);

   boolean hasFlag(int var1);

   void setName(String var1);

   boolean isRenamed();

   boolean setAttribute(String var1, Object var2);

   boolean removeAttribute(String var1);

   boolean hasAttribute(String var1);

   boolean hasTrueAttribute(String var1);

   Object getAttribute(String var1, Class var2);

   Map getAttributes();

   void setAutoGenerated(boolean var1);

   boolean isAutoGenerated();

   void dispose(boolean var1);

   boolean isDisposed();
}
